### ISSUE TITLE
Savestate not working properly.

### ISSUE THREAD

**Issue by ksabariraj** [yomotsu/camera-controls#10]
Hi,

I saved the state and tried to apply that after reload. But, the camera position is completely changed. Could you please help on this?

Please see the code below.

Get State
cameraControls.saveState(); var position = cameraControls._position0.toArray(); var target = cameraControls._target0.toArray()

Apply
cameraControls._target0.fromArray(target); cameraControls._position0.fromArray(position); cameraControls.reset();

Thanks,
Sabari.

**Comment by yomotsu** [comment]
Sorry.. I don't want to do...

The `SaveState` methods just apply current positions to initial positions to reset, which are `_target0` and `_position0`.
https://github.com/yomotsu/camera-controls/blob/master/src/camera-controls.js#L419
(Usually, you should not change props started `_` manually, these are private props for the lib)

If you still have question, could you provide more info for that?

**Comment by ksabariraj** [comment]
Thanks for your details.

Basically I am trying to save the scene position in local storage and load the same position when I am refreshed the page.

Is any other way it is achievable ?

**Comment by yomotsu** [comment]
As you might be aware, `saveState` does not save the state in localStorage or so, as I mentioned.
Please do it in your app.

**Comment by ksabariraj** [comment]
ok thanks.

**Comment by yomotsu** [comment]
Do you mind providing simplified example with your problem on CodePen or somewhere, please?

**Comment by ksabariraj** [comment]
https://codepen.io/sabariraj/pen/QBwrJr

Please rotate and pan the  scene and run again for testing. (same issue occurred)

**Comment by yomotsu** [comment]
Does this work? you also need `target` and may need other props too
https://codepen.io/yomotsu/pen/RBNmqM?editors=1010

**Comment by yomotsu** [comment]
Might be, we could have `toJSON` and `fromJSON` method for `camera-controls`

**Comment by yomotsu** [comment]
Can you try [the latest build](https://github.com/yomotsu/camera-controls/tree/master/dist) with [`toJSON`](https://github.com/yomotsu/camera-controls#tojson) and [`fromJSON`](https://github.com/yomotsu/camera-controls#fromjson-json-enabletransition-)?

**Comment by ksabariraj** [comment]
Yes. I used that only.

**Comment by yomotsu** [comment]
Sorry there was a [wrong math](https://github.com/yomotsu/camera-controls/commit/8f9ff868822f17297c171dea5872055fc0832fdd#diff-365150a28bd0f13ace86934611892e9a). I updated and hope it works.

**Comment by ksabariraj** [comment]
:) Thanks. Its working fine.

**Comment by yomotsu** [comment]
Glad to hear! `toJSON` and `fromJSON` are available in camera-controls@1.3.0 👍
