### ISSUE TITLE
Dolly state not preserved when using toJSON and fromJSON

### ISSUE THREAD

**Issue by daviestar** [yomotsu/camera-controls#105]
Hello,

Thanks for a great camera!

I'm using `camera-controls` with all default settings, and storing the state in localStorage:

```jsx
const controls = new CameraControls(camera, canvas);

const cached = localStorage.getItem('controls')
if (cached !== null) {
  controls.fromJSON(cached)
}

controls.addEventListener('update', storeControls)

// simple debounce
let timeoutId = 0
function storeControls(e) {
  clearTimeout(timeoutId)
  timeoutId = window.setTimeout(() => {
    localStorage.setItem('controls', e.target.toJSON())
  }, 100)
}
```

When I dolly in and out using the mouse wheel I can see the `position` Vector3 in localStorage update.  However when I refresh the page and `fromJSON` is used, the dolly position is reset.

Cheers.

**Comment by yomotsu** [comment]
Dolly is kinda async feature.
I guess you need to wait for the dolly movement end.

`controls` happens right after user control, and still changing the camera position.

**Comment by yomotsu** [comment]
this should be solved with https://github.com/yomotsu/camera-controls/pull/106
