### ISSUE TITLE
possible infinite dolly?

### ISSUE THREAD

**Issue by msemtd** [yomotsu/camera-controls#107]
When using dolly it is limited to approaching the orbit target as would be with zoom. That limitation isn't how a real world dolly operation would behave. I'd like the ability to continue to dolly in the current direction. Is that something that could be added? Perhaps moving the target like the forward function but along the current vector.

**Comment by msemtd** [comment]
I tried to implement this upon the sleep event but I can't work out the maths! I don't think it would work when using the mouse drag to dolly either.

**Comment by yomotsu** [comment]
Since CameraControls is sort of orbit-control, dolly over the target is difficult to add.
Maybe you could use `.moveTo()` method with the front direction.

CameraControls could provide the front direction for that.

**Comment by msemtd** [comment]
I guess I'll need to fork the project for that -- or it might be possible to intercept a mouse event
