### ISSUE TITLE
webXR support for VR camera control

### ISSUE THREAD

**Issue by FuzzyWobble** [yomotsu/camera-controls#109]
[https://camera-testing-3d.glitch.me/](https://camera-testing-3d.glitch.me/)

For VR, typically you can add the scenes camera as a child of an Object3D and move the Object3D to control VR camera motion. How would I use camera-controls to control the VR camera?

I'm on r106.

Thanks.

**Comment by yomotsu** [comment]
In WebXR Device API, the camera is controlled by XRFrame of WebXR Device API, then sync with the device pose and spec such as FoV, num of sight automatically, right?

camera-controls is not designed for WebXR. You can prepare another camera for WebXR (VR) then switch the camera on enter WebXR mode.

**Comment by FuzzyWobble** [comment]
You can do this in XR:
```
user = new THREE.Object3D();
user.add( camera );
scene.add( user );
user.position.set(x,y,z); //<--- moves VR camera
```

Does that help?

**Comment by yomotsu** [comment]
As I said, you can make 2 cameras. one for camera-controls, and another one is for your VR.
When the user enters VR mode, use the another one.

Don't share the camera in both modes.

**Comment by FuzzyWobble** [comment]
Got it, thanks!

**Comment by yomotsu** [comment]
Closing then.
