### ISSUE TITLE
Not working properly with z-axis up

### ISSUE THREAD

**Issue by avalero** [yomotsu/camera-controls#11]
I am using CameraControls (camera-controls) package to manage Camera on Three.js

When space is Y-axis up (camera.up.set(0,1,0)) it works just right, but when Z axis is set up (camera.up.set(0,0,1)) it stops working as expected (the same way it works with y-axis up)

Any clue how could I make CameraControls package work z-axis up?

**Comment by Jesusbill** [comment]
Hi @yomotsu, awesome work! Kudos to you and any other contributor.
I have implemented the functionality for any camera.up vector, similarly to the code of `OrbitControls` and would like to do a PR. (5e8ba0b96c5ea6ed717608de4f3293844746d6c2)
Should I commit just the source code or build and commit also the `dist` folder in the PR?

**Comment by yomotsu** [comment]
@Jesusbill Very nice! Could you make a PR without `dist` folder, please? Since it causes a ton of code changes.

**Comment by Jesusbill** [comment]
Sure, no problem. I just did the PR.

**Comment by yomotsu** [comment]
Thanks, Jesusbill's PR was just merged.
This issue can be closed now
