### ISSUE TITLE
when using lerpLookAt, doesn't reach final destination unless t value is very high.

### ISSUE THREAD

**Issue by FuzzyWobble** [yomotsu/camera-controls#110]
Will only reach final destination if t value is 0.90 or greater. 

Otherwise it stops before reaching the destination.

For example, [here](https://camera-testing-3d.glitch.me/), I had to use a t value of 0.99 to achieve this motion.

r106

**Comment by yomotsu** [comment]
I think that is expected behavior.
`t` must be between `0` to `1` where `0` is the start position and `1` is the final destination.

**Comment by FuzzyWobble** [comment]
Ooop, I thought t was the lerp speed.
