### ISSUE TITLE
Import script not working

### ISSUE THREAD

**Issue by jozkr** [yomotsu/camera-controls#111]
Can this be used as type=module? as it doesn't seem to work.

**Comment by yomotsu** [comment]
I think it works
https://jsfiddle.net/zmdt1obw/

**Comment by jozkr** [comment]
I get: Uncaught ReferenceError: pathAnimation is not defined
    at HTMLButtonElement.onclick ((index):33)

When I put the full code in your [fiddle](https://jsfiddle.net/zmdt1obw/):

<div class="info">
	<p><a href="https://github.com/yomotsu/camera-controls">GitHub repo</a></p>
	<button onclick="moveToStartPoint()">move to the animation start point</button>
	<br>
	<button onclick="pathAnimation.start()">path animation</button>
	<br>
	<button onclick="cameraControls.reset( true )">reset</button>
</div>

<script type="module">
import * as THREE from 'https://unpkg.com/three@0.118.3/build/three.module.js';
import TWEEN from 'https://cdnjs.cloudflare.com/ajax/libs/tween.js/18.6.0/tween.esm.js';
import CameraControls from 'https://www.unpkg.com/camera-controls@1.22.1/dist/camera-controls.module.js';

CameraControls.install( { THREE } );

console.log( CameraControls );

const width  = window.innerWidth;
const height = window.innerHeight;
const clock = new THREE.Clock();
const scene  = new THREE.Scene();
const camera = new THREE.PerspectiveCamera( 60, width / height, 0.01, 100 );
camera.position.set( 0, 0, 5 );
const renderer = new THREE.WebGLRenderer( { antialias: true, stencil: false } );
renderer.setSize( width, height );
document.body.appendChild( renderer.domElement );

const cameraControls = new CameraControls( camera, renderer.domElement );

const mesh = new THREE.Mesh(
	new THREE.BoxGeometry( 1, 1, 1 ),
	new THREE.MeshBasicMaterial( { color: 0xff0000, wireframe: true } )
);
scene.add( mesh );

const gridHelper = new THREE.GridHelper( 50, 50 );
gridHelper.position.y = - 1;
scene.add( gridHelper );

const curve = new THREE.CatmullRomCurve3( [
	new THREE.Vector3( -3,  2, 1 ),
	new THREE.Vector3(  2,  2, 0 ),
	new THREE.Vector3(  -1, 0, 3 ),
	new THREE.Vector3(  2, -1, 0 ),
] );
const points = curve.getPoints( 50 );
const pathMesh = new THREE.Line(
	new THREE.BufferGeometry().setFromPoints( points ),
	new THREE.LineBasicMaterial( { color: 0x00ffff } )
);
scene.add( pathMesh );

const _tmp = new THREE.Vector3();
const pathAnimation = new TWEEN.Tween( { progress: 0 } )
	.to( { progress: 1 }, 3000 )
	.easing( TWEEN.Easing.Quadratic.Out )
	.onStart( function() {
		// disable user control while the animation
		cameraControls.enabled = false;
	} )
	.onUpdate( function( values ) {

		curve.getPoint ( values.progress, _tmp );
		const cameraX = _tmp.x;
		const cameraY = _tmp.y;
		const cameraZ = _tmp.z;
		const lookAtX = 0;
		const lookAtY = 0;
		const lookAtZ = 0;

		cameraControls.setLookAt( 
			cameraX,
			cameraY,
			cameraZ,
			lookAtX,
			lookAtY,
			lookAtZ,
			false
		);

	} )
	.onComplete( function() {
		cameraControls.enabled = true;
	} );

function moveToStartPoint() {

	curve.getPoint ( 0, _tmp );
	cameraControls.setLookAt( _tmp.x, _tmp.y, _tmp.z, 0, 0, 0, true );

}

renderer.render( scene, camera );

( function anim () {

	const delta = clock.getDelta();
	const elapsed = clock.getElapsedTime();
	const updated = cameraControls.update( delta );

	// if ( elapsed > 30 ) { return; }

	requestAnimationFrame( anim );

	TWEEN.update( elapsed * 1000 );

	if ( updated ) {

		renderer.render( scene, camera );
		console.log( 'rendered' );

	}

} )();
</script>

**Comment by jozkr** [comment]
> I think it works
> https://jsfiddle.net/zmdt1obw/

I'm using path animation j

**Comment by jozkr** [comment]
> I think it works
> https://jsfiddle.net/zmdt1obw/

It looks like we need the right version of Tween: import TWEEN from  ... - where can we get it from and test? j

**Comment by yomotsu** [comment]
That is not a problem for camera-controls then

**Comment by yomotsu** [comment]
`pathAnimation` is scoped in your code because of module mode. You can't access the function from HTML.
That is not a problem for this lib at all. Just a syntax problem.

If you still have questions about this, refer MDN please.
