### ISSUE TITLE
Updating after new tween

### ISSUE THREAD

**Issue by jozkr** [yomotsu/camera-controls#114]
I have two tweens - one using camera-controls.js and the other is using the usual tween. It works but when I initiate the second tween - and it executes - it reverts to the first one (camera/controls). What is the best way to keep the second tween after the first tweek execution so it doesn't switch?

Attaching the code - two functions:

1. First Tween

    element.addEventListener("click", functionxxx(){
    const cameraControls = new CameraControls( camera, renderer2.domElement );

    const clock = new THREE.Clock();

    const curve = new THREE.CatmullRomCurve3( 

    [
    new THREE.Vector3(400, 300, 200),
    new THREE.Vector3(-180.00670968113795, 84.52888818858534, -117.3659024309699),
    new THREE.Vector3(400, 300, 200)]
    );

    const points = curve.getPoints( 50 );
    const pathMesh = new THREE.Line(
    new THREE.BufferGeometry().setFromPoints( points ),
    new THREE.LineBasicMaterial( { color: 0x00ffff } )
    );
    scene.add( pathMesh );

    const _tmp = new THREE.Vector3();
    const pathAnimation = new TWEEN.Tween( { progress: 0 } )
    .to( { progress: 1 }, 18000 )
    .easing(TWEEN.Easing.Quadratic.Out )
    .onStart( function() {
    // disable user control while the animation
    

    cameraControls.enabled = false;
    controls.enabled = false;
  } )
  .onUpdate( function( values ) {

  curve.getPoint ( values.progress, _tmp );
  const cameraX = _tmp.x;
  const cameraY = _tmp.y;
  const cameraZ = _tmp.z;
  const lookAtX = 0;
  const lookAtY = 0;
  const lookAtZ = 0;

  cameraControls.setLookAt( 
  cameraX,
  cameraY,
  cameraZ,
  lookAtX,
  lookAtY,
  lookAtZ,
  false
  );

} )
.onComplete( function() {

controls.enabled = true;

});

renderer.render( scene, camera );

( function anim () {

const delta = clock.getDelta();
const elapsed = clock.getElapsedTime();
const updated = cameraControls.update( delta );

// if ( elapsed > 30 ) { return; }

requestAnimationFrame( anim );

TWEEN.update( elapsed * 1000 );

if ( updated ) {

console.log( 'rendered' );

}

} )();

pathAnimation.start()

});

2. Second Tween

element.addEventListener("click", functionxxx(){

function tweenCamera( targetPosition, duration ) {

controls.enabled = false;

var position = new THREE.Vector3().copy( camera.position );

var tween = new TWEEN.Tween( position )
.to( targetPosition, duration )
.easing( TWEEN.Easing.Cubic.InOut )
.onUpdate( function () {
camera.position.copy( position );
camera.lookAt( controls.target );
} )
.onComplete( function () {
camera.position.copy( targetPosition );
camera.lookAt( 400, 300, 200 );

controls.enabled = true;
} )
.start();

}

var targetPosition = new THREE.Vector3( 400, 300, 200 );
var duration = 4000;

tweenCamera( targetPosition, duration );

});

**Comment by yomotsu** [comment]
Do you mind providing a working demo? Maybe in jsfiddle or codepen.
also, use codeblock when you attach code.

see https://guides.github.com/features/mastering-markdown/

**Comment by jozkr** [comment]
There you go - https://jsfiddle.net/jozkr8/cnxm2afq/50/

If you click on Button 1 (top left)  - Tween 1 starts animating, then once it reaches the end - the Button 2 appears (top left) and it animates Tween 2 too - but as soon as Tween 2 finishes - it reverts back to Tween 1 and it should stay on Tween 2 end j

**Comment by yomotsu** [comment]
use `setLookAt( positionX, positionY, positionZ, targetX, targetY, targetZ, false )` right after second tween.

**Comment by jozkr** [comment]
This works! Thank you but how I can enable Controls as they seem to be disabled (can’t move).

J

**Comment by jozkr8** [comment]
This works! Thank you but how I can enable Controls as they seem to be disabled (can’t move).

J

**Comment by yomotsu** [comment]
I think that is not a bug of camera-controls.
You should review your code by yourself.

**Comment by jozkr** [comment]
Yes -  cameraControls.enabled = true; that works (changed from false to true). You can close this thread :)

Thank you.

Amazing work btw.
