### ISSUE TITLE
Feature Request: Sphere Boundary

### ISSUE THREAD

**Issue by flolu** [yomotsu/camera-controls#117]
It would be great to have the ability to use a sphere as a boundary.
The reason for this is showcased in this GIF:

![viewer](https://user-images.githubusercontent.com/34191949/88265277-7b774f00-cccd-11ea-88a1-652f4ba80f2b.gif)

Rotating near the object is fine.
But rotating near the boundary will result in a constant "zoom-in-zoom-out" because the boundary is a box.

**Comment by yomotsu** [comment]
Dose `.maxDistance` not work in your case?
or `colliderMeshes` with [`THREE.BackSide`](https://threejs.org/docs/#api/en/materials/Material.side) could be another option for it.

**Comment by flolu** [comment]
Yes, you are right. `maxDistance` is probably the easiest solution!

I only has the downside, that the boundary is "hard", so there is no smooth transition when reaching the boundary.
