### ISSUE TITLE
Error re: cancelable=false

### ISSUE THREAD

**Issue by ThreeDfish** [yomotsu/camera-controls#118]
I am getting the following error message a lot:

[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

The simple fix is to wrap the ``` event.preventDefault(); ``` with a test for event.cancelable, i.e.

```js
if (event.cancelable) {
    event.preventDefault();
}
```

I can create a pull request...

**Comment by yomotsu** [comment]
Nice finding👍
Waiting for your PR.

**Comment by ThreeDfish** [comment]
The error is generated in Chrome on mobile devices.  We have a large SPA that we recently switched to using these camera controls, and this error was popping up...  It doesn't occur on all events, because some events are cancelable, however, it appears that sometimes the events are not cancelable apparently due to scroll state, which causes the error.

Adding the test for cancelable fixed the errors and did not affect functionality.

**Comment by yomotsu** [comment]
Thank you for your additional comment.
It would be appreciated if you could provide a simplified demo and steps to reproduce the error as well🙇‍♂️

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
