### ISSUE TITLE
Using camera-controls with Orthographic camera

### ISSUE THREAD

**Issue by tofuness** [yomotsu/camera-controls#12]
I am just documenting this here for other users. Doesn't really need a fix (feel free to close this).

**Problem**
There is no `.fov` property for [`THREE.OrthographicCamera`](https://threejs.org/docs/#api/en/cameras/OrthographicCamera) but this following line requires that the camera has a `.fov` or else we get `NaN`:
https://github.com/yomotsu/camera-controls/blob/8e939f2c9bee19dc3633be57c6b2f05fd4843b6d/src/camera-controls.js#L282

**Workaround**
Just add a `fov` property when creating a `THREE.OrthographicCamera`.

**Comment by yomotsu** [comment]
@tofuness

Thank you for your report!
Add basic OrthographicCamera support. not perfect tho, it works without the workaround.
hope it helpful
![3](https://user-images.githubusercontent.com/212837/45835385-ed368880-bd44-11e8-8e2c-c74a132e9d6c.gif)
