### ISSUE TITLE
Change the compile target to ES6

### ISSUE THREAD

**Issue by ThreeDfish** [yomotsu/camera-controls#121]
All current browsers support ES6 and have for some time now.

I think it is way past time to change the compile target to es6.

First, any old browsers that don't support es6 are not being used anyway,

and second, any browser that is old enough not to support es6 has serious security issues.

So, no reason to not target es6

**Comment by looeee** [comment]
@yomotsu I guess this is resolved now since you have both UMD and ES builds?

**Comment by yomotsu** [comment]
Yeah, We have both thanks to rollup👍
However, the TS code is transpiled to ES5 to support the IE11.

I guess it's about time to drop IE and move to ES6 soon. (maybe by the end of this year...?)

**Comment by looeee** [comment]
Yeah IE11 end of life is in about a year so you could wait for that. But three.js doesn't support IE11 anymore so maybe it's fine to do it now?

**Comment by yomotsu** [comment]
Okay, I marked this as one of the next tasks👍

**Comment by yomotsu** [comment]
This can be closed by https://github.com/yomotsu/camera-controls/pull/246
