### ISSUE TITLE
'ReferenceError: navigator is not defined' for Next.js apps

### ISSUE THREAD

**Issue by nikhilxb** [yomotsu/camera-controls#124]
I'm trying to use this library within my Next.js app, and I'm getting a `ReferenceError: navigator is not defined` thrown by this line, since `navigator` is not defined on the server side.

https://github.com/yomotsu/camera-controls/blob/71ffdc4e797d328bdb70134b3d5832158eddb160/src/CameraControls.ts#L26

**Comment by nikhilxb** [comment]
I found a hack that fixes it.

Broken:
```js
import CameraControls from 'camera-controls';
CameraControls.install({ THREE });
```
Working:
```js
const CameraControls = typeof window !== `undefined` ? require("camera-controls").default : null;
if(CameraControls) CameraControls.install({ THREE });
```

**Comment by yomotsu** [comment]
Ah, that's right.
We should add another condition for SSR detection in camera-controls.

I'll work on it this weekend, or you can make a PR for it if you like.

**Comment by yomotsu** [comment]
I think this should be solved with https://github.com/yomotsu/camera-controls/pull/125

**Comment by nikhilxb** [comment]
Awesome, thanks!
