### ISSUE TITLE
Fit camera without changing orientation

### ISSUE THREAD

**Issue by mrsaleh** [yomotsu/camera-controls#128]
Is there any way I can achieve something like the link below by fitCamera?

https://www.ikea.com/us/en/planner/soderhamn-planner/#blank

The camera will fit the scene bounds without rotating around it

Thanks in advance

**Comment by yomotsu** [comment]
Unfortunately, currently `fitTo()` only supports 6 fixed faces😢

**Comment by yomotsu** [comment]
An easy way to achieve that, make the bounding sphere in three.js, then `.dollyTo( radius )`.
(It is not a perfect viewport fit tho)

**Comment by yomotsu** [comment]
@mrsaleh I've added an example for it. this should be what you are looking for.
https://rawcdn.githack.com/yomotsu/camera-controls/17da5e44d8c03dda9ca4c44e8d888f84e54dcbf5/examples/fit-to-bounding-sphere.html

**Comment by yomotsu** [comment]
this should be solved. closing.
