### ISSUE TITLE
Supress the need to run CameraControls.install()

### ISSUE THREAD

**Issue by ACMCMC** [yomotsu/camera-controls#129]
I am almost sure there must be a way to avoid an explicit call to `CameraControls.install()`. We could try to get a reference to THREE automatically, which would make CameraControls more user-friendly. I will try to take a look into it if that's OK :-)

**Comment by yomotsu** [comment]
Thanks for your suggestion!

Actually, `CameraControls.install()` is for `<script type="module">`.
I think camera-controls.module.js can't refer THREE from the CDN hosted script.

like:
```
<script type="module">
import * as THREE from 'https://unpkg.com/three@0.120.0/build/three.module.js';
import CameraControls from 'https://unpkg.com/browse/camera-controls@1.24.1/dist/camera-controls.module.js';

CameraControls.install( { THREE } );
</script>
```

**Comment by yomotsu** [comment]
should be solved. closing.
