### ISSUE TITLE
Set orbit point different from camera target point

### ISSUE THREAD

**Issue by nikhilxb** [yomotsu/camera-controls#130]
I'm trying to make it so that when a user clicks a part of my 3D model, the camera's orbit point is changed to that part's centerpoint _without_ moving the camera (which `setTarget()` does). The goal is for the camera to orbit around that part, even if the user pans/trucks the camera.

Is there a way to change the orbit point?

The solution from a couple years ago (https://github.com/yomotsu/camera-controls/issues/8) of setting `controls._target` and `controls._targetEnd` moves the camera and does not work after the user pans/trucks the camera.

**Comment by yomotsu** [comment]
What you want is, truck/pedestal movement but keep looking at the center point at the same time, isn't it?
But sorry, I can't imagine the movement...

Could you provide a simple demo with the old version of camera-controls?
You can grab an old version from https://unpkg.com/browse/camera-controls@1.24.1/dist/camera-controls.module.js

**Comment by nikhilxb** [comment]
@yomotsu Thank you for your help. Here is an example to aid imagining the desired behavior:

**1.** Model centered at (0, 0, 0). Camera looking at (0, 0, 0).
![model-center](https://user-images.githubusercontent.com/16842594/93687178-b3123580-fa89-11ea-8441-036bc23666b7.png)

**2.** Camera orbits around (0, 0, 0).
![around-center](https://user-images.githubusercontent.com/16842594/93687087-ff10aa80-fa88-11ea-9b63-1c0b8053ef46.gif)

**3.** User clicks a part of the model, i.e. finger (in green). Camera *does not move* ... still looking at (0, 0, 0).
![model-finger](https://user-images.githubusercontent.com/16842594/93687160-90801c80-fa89-11ea-8bad-cc0bbf71d800.png)

**4.** Camera now orbits around a different point, i.e. finger's centerpoint.
![around-finger](https://user-images.githubusercontent.com/16842594/93687088-ff10aa80-fa88-11ea-84d6-2fdde004c29e.gif)

From what I've tried with `CameraControls`, I can't get the "orbit" point to be different from the "look at" point.

**Comment by yomotsu** [comment]
Thanks for the details.
Seems what you want is offset. But It takes a little bit of time to add the feature.

In meantime, how about just rotating the model itself?

**Comment by yomotsu** [comment]
I'm working on that.
![3](https://user-images.githubusercontent.com/212837/93706553-68182100-fb62-11ea-96a8-381e37b370a1.gif)

**Comment by yomotsu** [comment]
Hey! does this look good?
https://rawcdn.githack.com/yomotsu/camera-controls/17b5aeae87fabe460f2dd1bfcbbf412fe78daa4d/examples/focal-offset.html

**Comment by nikhilxb** [comment]
Wow, you're really fast! The demo looks good. The focal-offset feature definitely yields more pleasing movement for applications like mine centered around a 3D model.

The one thing is I'm not sure how this can achieve movement like in the above screenshots 3 & 4. That orbit is centered around the finger's *3D* centerpoint (cx, cy, cz), not the target (0, 0, 0). In the current formulation, it seems that orbits always happen around target (0, 0, 0). `setFocalOffset(fx, fy)` takes a *2D* offset (fx, fy), but it's not immediately clear how to convert (cx, cy, cz) -> (fx, fy).

I imagine something like `setOrbitOrigin(ox, oy, oz)` would be more intuitive and powerful. By default, orbit origin = target, so the camera orbits around the target. But orbit origin could be set otherwise like in screenshots 3 & 4, without moving the camera. Then, orbit would happen around a different point. This achieves the same visual effect as focal offset, since during trucking the target point is translated, but the orbit origin stays at the model center. But this would also add flexibility since orbit origin could be set at any arbitrary point.

I'm not an expert on 3D camera math so I hope this makes sense?

P.S. A different example: in your cube demo, right now even with focal offset the cube always seems to rotate around its center. I'm proposing a way to enable it to rotate around one of its corner points.

**Comment by yomotsu** [comment]
Hehe thanks😄
z focal offset is actually Dolly. You can use `.dolly()` or `.dollyTo()` for it.

```js
cameraControls.setFocalOffset( fx, fy );
cameraControls.dollyTo( fz );
```

Can you try this in your app? It's available on dev branch of this repo.
If you use npm, you can grab the dev branch in your package.json:
(the hash is commit id)
```json
"dependencies": {
  "camera-controls": "git+ssh://git@github.com/yomotsu/camera-controls.git#b19ac604abcd9af1174de6315ef3f3b66c001ef4"
}
```

If you still have feature requests, feel free to ask me👍

**Comment by nikhilxb** [comment]
Hey! Testing with the dev branch, I found a solution that worked to _partially_ achieve the effect in the screenshots. Posting here for future reference:
```typescript
// Set up controls to use focal offset method for trucking.
controls.mouseButtons.right = CameraControls.ACTION.OFFSET;
controls.touches.one = CameraControls.ACTION.TOUCH_ROTATE;
controls.touches.two = CameraControls.ACTION.TOUCH_DOLLY_OFFSET;
controls.touches.three = CameraControls.ACTION.TOUCH_OFFSET;
```
```typescript
// Set (x, y, z) as the effective orbit point without the scene moving.
controls.moveTo( x, y, z, true );
controls.setFocalOffset( -x, y, true );
```
A couple of notes on this approach:

- The `moveTo()` function is used so the camera doesn't pivot as it would with `setTarget()`. By itself, the scene appears to translate. Simultaneously using `setFocalOffset()` compensates so the net effect is that scene appears not to move at all. Afterwards, as desired, the orbiting appears to occur around (x, y, z).
- The arguments to `setFocalOffset()` are `-x` and `y` (not `-y`) because of the direction y-axis is oriented.
- This solution **doesn't work** for `OrthographicCamera` since `dollyTo()` doesn't have any effect. Therefore, there is no easy way to compensate for the apparent z-translation due to `moveTo()`. This apparent translation is undetectable when the z-axis points out-of/into the screen, but grows as more of the yz-plane comes into view. Perhaps, using `PerspectiveCamera` and `dollyTo()` this problem is eliminated, but I haven't tested that approach.

**Comment by nikhilxb** [comment]
It took me a while to figure out, but I've finally developed a hack to *fully* achieve the effect in the screenshots. Posting here for future reference:
```typescript
// Instantiate vectors to reuse.
const xcol = new Vector3();
const ycol = new Vector3();
const zcol = new Vector3();
```
```typescript
// Set (x, y, z) as the effective orbit point without the scene moving.
controls.moveTo( x, y, z, true );
xcol.setFromMatrixColumn( controls._camera.matrixWorldInverse, 0 );
ycol.setFromMatrixColumn( controls._camera.matrixWorldInverse, 1 );
zcol.setFromMatrixColumn( controls._camera.matrixWorldInverse, 2 );
const fx = x * xcol.x              + z * zcol.x;
const fy = x * xcol.y + y * ycol.y + z * zcol.y;
controls.setFocalOffset( -fx, fy, true );
```

- Each column in the inverse world matrix gives the unit vector corresponding to a camera axis in world space (x right, y up, z out). They are used to determine the focal offsets needed to compensate for the lack of z-translation with `OrthographicCamera`. 
- @yomotsu: Not sure if there's an easier way, but this is the best I could come up with given the API as it stands :)

**Comment by yomotsu** [comment]
Good to hear that😄

Ideally, we should not touch `_` prefixed private params, but there is no way to achieve your case I guess...😢
I will try to figure out the best solution for it. in meantime, use your custom method.

I will publish it to npm this weekend. (plz check to see https://github.com/yomotsu/camera-controls/pull/136 as well)

**Comment by Sim3d** [comment]
Hi guys! I try to change the CameraControls target without moving the camera like nikhilxb but it's not work perfectly. In my solution (see the example below) based on the nikhilxb solution, every time I change the controls rotation, the setFocalOffset moves the scene origin to (0, 0, 0). After that, if you put the cursor on one of the cubes, this cube will be set as the Controls Target without moving the camera as expected. 

I’m not mathemagician so I try to understand the problem. Do you have an idea of what can cause this behavior?

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<title>=^.^=</title>
<link rel="stylesheet" href="./style.css">
</head>
<body>
<div class="info">
	<p>
		Update CameraControls Target without moving camera
	</p>
</div>

<script src="https://unpkg.com/three@0.118.3/build/three.min.js"></script>
<script src="../dist/camera-controls.js"></script>
<script>
CameraControls.install( { THREE: THREE } );

const loader = new THREE.FontLoader();
loader.load(
		'https://raw.githubusercontent.com/rollup/three-jsnext/master/examples/fonts/helvetiker_bold.typeface.json',
		addAxes
);

const raycaster = new THREE.Raycaster();
const mouse = new THREE.Vector2();

let controlDragging = false;

const xColumn = new THREE.Vector3();
const yColumn = new THREE.Vector3();
const zColumn = new THREE.Vector3();

const orbitalPointFocalOffset = new THREE.Vector3();

const focalOffsetPoint = new THREE.Vector3();
const orbitalPoint = new THREE.Vector3();

const pickedCubePosition = new THREE.Vector3();

const width  = window.innerWidth;
const height = window.innerHeight;
const clock = new THREE.Clock();
const scene  = new THREE.Scene();
// const camera = new THREE.PerspectiveCamera( 60, width / height, 0.01, 100 );
const camera = new THREE.OrthographicCamera( width / - 200, width / 200, height / 200, height / - 200, -100, 2000 );

camera.position.set( 20, 20, 20 );
const renderer = new THREE.WebGLRenderer();
renderer.setSize( width, height );
document.body.appendChild( renderer.domElement );

const cameraControls = new CameraControls( camera, renderer.domElement );

cameraControls.dollyToCursor = false;
cameraControls.verticalDragToForward = false;

cameraControls.mouseButtons.right = CameraControls.ACTION.OFFSET;

window.addEventListener( 'mousemove', onMouseMove, false );
window.addEventListener( 'mouseup', onMouseUp, false );

cameraControls.addEventListener( 'controlstart', onControlStart, false );
cameraControls.addEventListener( 'controlend', onControlEnd, false );

let pickedMesh = null;

const mesh1 = new THREE.Mesh(
	new THREE.BoxGeometry( 1, 1, 1 ),
	new THREE.MeshBasicMaterial( { color: 0xff0000, transparent: false, opacity: 0.25 } )
);

const mesh2 = new THREE.Mesh(
		new THREE.BoxGeometry( 1, 1, 1 ),
		new THREE.MeshBasicMaterial( { color: 0x00ff00, transparent: false, opacity: 0.25 } )
);

const mesh3 = new THREE.Mesh(
		new THREE.BoxGeometry( 1, 1, 1 ),
		new THREE.MeshBasicMaterial( { color: 0xffff00, transparent: false, opacity: 0.25 } )
);

const mesh4 = new THREE.Mesh(
		new THREE.BoxGeometry( 1, 1, 1 ),
		new THREE.MeshBasicMaterial( { color: 0xffffff, transparent: false, opacity: 0.25 } )
);

const orbitalPointMesh = new THREE.Mesh(
		new THREE.SphereGeometry( 0.25 ),
		new THREE.MeshBasicMaterial( { color: 0xf0f0f0, wireframe: false } )
);

const focalOffsetMesh = new THREE.Mesh(
		new THREE.SphereGeometry( 0.5 ),
		new THREE.MeshBasicMaterial( { color: 0x00ffff, wireframe: true } )
);

mesh1.name = 'cube_Red';
mesh2.name = 'cube_Blue';
mesh3.name = 'cube_Yellow';
mesh4.name = 'cube_White';
orbitalPointMesh.name = 'sphere_OrbitPoint';
focalOffsetMesh.name = 'sphere_FocalOffset';

const cubes = [mesh1, mesh2, mesh3, mesh4];

const redCubeCoordinate = new THREE.Vector3(3,4,2);

mesh1.position.copy(redCubeCoordinate);
mesh2.position.set(0,8,8);
mesh3.position.set(-5,-5,-5);
mesh4.position.set(1,5,15);

scene.add( mesh1 );
scene.add( mesh2 );
scene.add( mesh3 );
scene.add( mesh4 );

scene.add( orbitalPointMesh );
// scene.add( focalOffsetMesh );

render();

( function anim () {

	const delta = clock.getDelta();
	const elapsed = clock.getElapsedTime();
	const updated = cameraControls.update( delta );

	// if ( elapsed > 30 ) { return; }

	requestAnimationFrame( anim );

	if ( updated ) {
		render();
	}

} )();

function onControlStart() {
	controlDragging = true;
}

function onControlEnd() {
	controlDragging = false;
}

function setControlsTargetWithoutMovingCamera(targetPosition) {

	if (controlDragging) {
		return;
	}

	moveControlsTargetToPickedPoint(targetPosition, true);
	setCameraControlsFocalOffset(targetPosition, true);
}

function moveControlsTargetToPickedPoint(targetPosition, transition) {

	cameraControls.moveTo( targetPosition.x, targetPosition.y, targetPosition.z, transition );

	updateOrbitalPointMesh();
}

function setCameraControlsFocalOffset(targetPosition, transition) {

	// Each column in the inverse world matrix (i.e.: camera View Matrix)
	// gives the unit vector corresponding to a camera axis in world space (x right, y up, z out).
	// They are used to determine the focal offsets needed to compensate
	// for the lack of z-translation with OrthographicCamera
	xColumn.setFromMatrixColumn( camera.matrixWorldInverse, 0 );
	yColumn.setFromMatrixColumn( camera.matrixWorldInverse, 1 );
	zColumn.setFromMatrixColumn( camera.matrixWorldInverse, 2 );

	const xFocalOffset = targetPosition.x * xColumn.x + targetPosition.y * yColumn.x + targetPosition.z * zColumn.x;
	const yFocalOffset = targetPosition.x * xColumn.y + targetPosition.y * yColumn.y + targetPosition.z * zColumn.y;
	const zFocalOffset = targetPosition.x * xColumn.z + targetPosition.y * yColumn.z + targetPosition.z * zColumn.z;

	cameraControls.setFocalOffset( -xFocalOffset, yFocalOffset, -zFocalOffset, transition );

	updateFocalOffsetMesh();
}

function updateOrbitPointOnMouseMove() {

	let cubeMesh = detectCube();

	if (cubeMesh) {

		if (pickedMesh !== cubeMesh) {

			pickedMesh = cubeMesh;

			pickedCubePosition.copy(pickedMesh.position);

			setControlsTargetWithoutMovingCamera(pickedMesh.position);

		}

	} else {
		pickedMesh = null;
	}
}

function detectCube() {

	// update the picking ray with the camera and mouse position
	raycaster.setFromCamera( mouse, camera );

	// calculate objects intersecting the picking ray
	var intersects = raycaster.intersectObjects( scene.children );

	if (intersects.length > 0) {
		let objectUnderMouse = intersects[ 0 ].object;
		if (objectUnderMouse.name.startsWith('cube')) {

			updateCubesMaterial(objectUnderMouse);

			return objectUnderMouse;
		}
	} else {
		updateCubesMaterial(null);
	}

	return null;
}

function updateCubesMaterial(detectedCube) {
	cubes.forEach(cube => {
		cube.material.transparent = !!(detectedCube && detectedCube === cube);
	})
}

function updateNormalizedMouseCoordinates(event) {
	// calculate mouse position in normalized device coordinates (-1 to +1) for both components
	mouse.x = ( event.clientX / window.innerWidth ) * 2 - 1;
	mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
}

function onMouseUp( event ) {
	if (event.button === 2) {
		updateFocalOffsetMesh();
		updateOrbitalPointMesh();
	}
}

function onMouseMove( event ) {

	if (controlDragging) {
		return;
	}

	updateNormalizedMouseCoordinates(event);
	updateOrbitPointOnMouseMove();

	render();
}

function getFocalOffset() {
	cameraControls.getFocalOffset(focalOffsetPoint);
	return focalOffsetPoint;
}

function updateFocalOffsetMesh() {
	focalOffsetMesh.position.copy(getFocalOffset());
}

function updateOrbitalPointMesh() {
	orbitalPointMesh.position.copy(getTarget());
}

function getTarget() {
	cameraControls.getTarget(orbitalPoint);
	return orbitalPoint;
}

function render() {
	renderer.render( scene, camera );
}

function addAxes(font) {

	const axesMesh = createAxes(1, 0.05, font);

	scene.add( axesMesh );

	render();
}

function createAxes(height, radius, font) {
	const axes = new THREE.Group();

	axes.name = 'Axes';

	const arrowGeometry = new THREE.CylinderGeometry(0, 2 * radius, height / 5);

	// X Axis (Red)
	const xAxisMaterial = new THREE.MeshBasicMaterial({color: 0xFF0000});
	const xAxisGeometry = new THREE.CylinderGeometry(radius, radius, height);
	const xAxisMesh = new THREE.Mesh(xAxisGeometry, xAxisMaterial);
	const xArrowMesh = new THREE.Mesh(arrowGeometry, xAxisMaterial);

	xAxisMesh.add(xArrowMesh);

	xArrowMesh.position.y += height / 2;
	xAxisMesh.rotation.z  -= 90 * Math.PI / 180;
	xAxisMesh.position.x  += height / 2;

	// Y Axis (Green)
	const yAxisMaterial = new THREE.MeshBasicMaterial({color: 0x00FF00});
	const yAxisGeometry = new THREE.CylinderGeometry(radius, radius, height);
	const yAxisMesh = new THREE.Mesh(yAxisGeometry, yAxisMaterial);
	const yArrowMesh = new THREE.Mesh(arrowGeometry, yAxisMaterial);

	yAxisMesh.add(yArrowMesh);

	yArrowMesh.position.y += height / 2;
	yAxisMesh.position.y  += height / 2;

	// Z Axis (Blue)
	const zAxisMaterial = new THREE.MeshBasicMaterial({color: 0x0000FF});
	const zAxisGeometry = new THREE.CylinderGeometry(radius, radius, height);
	const zAxisMesh = new THREE.Mesh(zAxisGeometry, zAxisMaterial);
	const zArrowMesh = new THREE.Mesh(arrowGeometry, zAxisMaterial);

	zAxisMesh.add(zArrowMesh);

	zAxisMesh.rotation.x += 90 * Math.PI / 180;
	zArrowMesh.position.y += height / 2;
	zAxisMesh.position.z += height / 2;

	axes.add(xAxisMesh);
	axes.add(yAxisMesh);
	axes.add(zAxisMesh);

	var xTextMesh = new THREE.Mesh();
	var yTextMesh = new THREE.Mesh();
	var zTextMesh = new THREE.Mesh();

	xTextMesh.geometry = new THREE.ShapeBufferGeometry( font.generateShapes( 'X+', 0.2 ) );
	yTextMesh.geometry = new THREE.ShapeBufferGeometry( font.generateShapes( 'Y+', 0.2 ) );
	zTextMesh.geometry = new THREE.ShapeBufferGeometry( font.generateShapes( 'Z+', 0.2 ) );

	xTextMesh.material.color.copy(new THREE.Color(0xff0000));
	yTextMesh.material.color.copy(new THREE.Color(0x00ff00));
	zTextMesh.material.color.copy(new THREE.Color(0x0000ff));

	xTextMesh.position.x = 1.2;
	xTextMesh.position.y = -0.1;

	yTextMesh.position.x = -0.1;
	yTextMesh.position.y = 1.2;

	zTextMesh.position.x = -0.1;
	zTextMesh.position.y = 0.1;
	zTextMesh.position.z = 1.2;

	axes.add(xTextMesh);
	axes.add(yTextMesh);
	axes.add(zTextMesh);

	return axes;
}
</script>

</body>
</html>




```

**Comment by paulmelnikow** [comment]
My application is very similar to @nikhilxb, with a (human body!) model in the center and an orthographic view.

I used the work from #136 along with https://github.com/yomotsu/camera-controls/issues/130#issuecomment-697000378 and https://github.com/yomotsu/camera-controls/issues/130#issuecomment-697007648 and it seems to be working well. Thank you both for your work and for sharing!

This is my version of `setOrbitPoint`, into which I'm passing the mesh centroid.

```ts
const xcol = new THREE.Vector3()
const ycol = new THREE.Vector3()
const zcol = new THREE.Vector3()

export function setOrbitPoint(
  controls: CameraControls,
  point: [number, number, number],
  { enableTransition = true }: { enableTransition?: boolean } = {}
): void {
  const [x, y, z] = point

  // https://github.com/yomotsu/camera-controls/issues/130#issuecomment-697007648
  controls.moveTo(x, y, z, enableTransition)
  const camera = (controls as any)._camera as THREE.OrthographicCamera
  xcol.setFromMatrixColumn(camera.matrixWorldInverse, 0)
  ycol.setFromMatrixColumn(camera.matrixWorldInverse, 1)
  zcol.setFromMatrixColumn(camera.matrixWorldInverse, 2)
  const fx = x * xcol.x + z * zcol.x
  const fy = x * xcol.y + y * ycol.y + z * zcol.y
  controls.setFocalOffset(
    -fx,
    fy,
    0, // z has no effect in orthographic.
    enableTransition
  )
}
```

Would it make sense to add a `setOrbitPoint` method on CameraControls which encapsulates this logic? I'd be happy to open a PR.

**Comment by Blocovin** [comment]
Hi guys !
We try to use @paulmelnikow with "setOrbitPoint" solution but camera position jump like @paulmelnikow say.

![camera_offset](https://user-images.githubusercontent.com/39763266/119995461-e10f2880-bfcd-11eb-9a26-2ba9bed9af9f.gif)

Does anyone got a solution ?

**Comment by cederache** [comment]
@yomotsu do you have an idea about the camera jump using the setOrbitPoint solution from @paulmelnikow ?

**Comment by cederache** [comment]
I created a codepen to test the camera jump issue : https://codepen.io/cederache/pen/YzZjXWV

**Comment by ketourneau** [comment]
Does anyone have a solution ?
We would like to offer this feature to our users.
