### ISSUE TITLE
Control zoom and pan transitions independently

### ISSUE THREAD

**Issue by PerryRylance** [yomotsu/camera-controls#134]
I'm working on an orthographic project and finding that the camera reaches close zoom well before the pan finds its target, so rather than the object I'm looking to focus on being on screen during the transition, I see a close zoom of the scene panning by very quickly

Is it possible to control the timing and easing of these two transitions independently?

**Comment by yomotsu** [comment]
All transitions are merged to the one diff.
However, you can make your easing with tween libraries.
see this for example.
https://yomotsu.github.io/camera-controls/examples/easing.html

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
