### ISSUE TITLE
Support deviceorientation events for orbiting

### ISSUE THREAD

**Issue by mattrei** [yomotsu/camera-controls#14]
May be set via a flag if the orientation is solely responsible for orbiting.

**Comment by yomotsu** [comment]
How about using other contorls such as DeviceOrientationControls?https://threejs.org/examples/misc_controls_deviceorientation.html

**Comment by mattrei** [comment]
this control does not help, because it does not tackle the orbiting.
see also this [issue](https://github.com/mrdoob/three.js/issues/9047) where others try to orbit around an point via the device's orientation. However there is no complete implementation available yet.

**Comment by yomotsu** [comment]
I understand. I think its technically possible since our camera-contorls uses spherical coordinates which can be converted from device orientation alpha beta and gamma.

We could add the feature, however, I don't have much time right now. I guess I will take a look that this weekend.

**Comment by Anorak27** [comment]
Is there any implementation of this feature?

**Comment by yomotsu** [comment]
Closing this issue.
three.js has [removed the DeviceOrientationControls](https://github.com/mrdoob/three.js/pull/22654) due to the actual device issue, and Orbit rotation can not be worked with device-orientation.
