### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by nantille** [yomotsu/camera-controls#141]
Hello, this is a great repo. 

However, for me to use it in projects, I need to know what is the license for your code. Is it the same MIT as three.js? Or something else?

Could you please add a "LICENSE" file to the repository?
Thanks!

**Comment by Jesusbill** [comment]
Yes it is [MIT](https://github.com/yomotsu/camera-controls/blob/dev/package.json#L5).
I agree a LICENSE file would be more applicable.

**Comment by yomotsu** [comment]
Thanks for your advice.

> Yes it is MIT.

that's right! thank @Jesusbill as usual 😊

just added the LICENSE.
https://github.com/yomotsu/camera-controls/commit/a46b7bc820a1fcda5c9498c59c361089da17e5d4

**Comment by nantille** [comment]
That was fast. :)
Keep up the good work!
