### ISSUE TITLE
setup CI

### ISSUE THREAD

**Issue by 0b5vr** [yomotsu/camera-controls#142]
I saw you have mentioned about ci in https://github.com/yomotsu/camera-controls/pull/92

Maybe we can have a simple CI setup that comes with lint and build inspection
I can do it tbh

Which do you prefer?: GitHub Actions or CircleCI (I do have knowledge about these two) or anything else

**Comment by yomotsu** [comment]
It would be appreciated❤️
Ether is fine. maybe CircleCI?

**Comment by yomotsu** [comment]
Closing due to age.
