### ISSUE TITLE
Bug: When in IFrame orbit freeze when mouse leave iframe area

### ISSUE THREAD

**Issue by zamecnik** [yomotsu/camera-controls#144]
I upgraded from 1.19 to 1.25 and run into this issue when using cam controls in IFrame:

When holding down left mouse bttn (camera orbit, all default) and going out of IFrame - release left mouse bttn (when out of Iframe) - return with mouse to Iframe - model still orbit, even with mouse bttns released - its ok and expected behavior, but now when I click on left mouse bttn (inside Iframe) camera is freezed and orbit is not possible by left mouse bttn. 

To fix this it is needed to click on right mouse bttn. Then left mouse bttn works again. 

Before upgrade it worked ok, camera after returning to iframe with released mouse bttns did still orbit, but after left click it stopped and was possible to orbit again. Now it is freezed.

Thanks a lot for help

**Comment by yomotsu** [comment]
Thanks for your report.
Confirmed the probrem.

Ill take a look.

**Comment by yomotsu** [comment]
will be fixed✨
https://github.com/yomotsu/camera-controls/pull/145

**Comment by zamecnik** [comment]
Thanks a lot.

I tried the fixed library from dev branch and orbit works like a charm. Great job man, thanks.

Just a note - maybe it is for new ticket: Panning (right mouse bttn) has still similar issues. When panning outside of iframe -> releasing right mouse bttn (outside of iframe) -> in win OS pupup dialog will appear -> esq key to cancel it -> return with cursor to iframe area -> cam controls are in panning mode even no mouse bttn is pressed. But after any click, correct state is restored, so it is not so big deal.

But if you want to create a new ticket for it, let me know.

**Comment by yomotsu** [comment]
I've tried to fix right-click dragging buy It seems slightly different.
If you like, open another issue (but not confident I could fix it for now).
