### ISSUE TITLE
How to use the Threejs ray casting with camera controls?

### ISSUE THREAD

**Issue by bradphelan** [yomotsu/camera-controls#147]
It seems that camera-controls eats the mouse events? Any way to still get them?

**Comment by msemtd** [comment]
Working fine for me here. What exactly are you doing?

**Comment by yomotsu** [comment]
Sorry for the delay.
Thanks for your comment @msemtd.

@bradphelan Do you mind providing a simplified example?
It may depend on what event you use and the order of `addEventListener`.

**Comment by bradphelan** [comment]
I'm not sure what the problem was. I'm now using threejs.interactivity which with cameracontrols and it is working fine. You can close the issue.

**Comment by yomotsu** [comment]
Good to hear that.
Closing.
