### ISSUE TITLE
fitTo no longer accepts negative values for padding

### ISSUE THREAD

**Issue by rafaelbuiu** [yomotsu/camera-controls#148]
I have developed an experience using camera-controls in 2019. Now I am doing some enhancements and updates to the application but the current version of camera-controls is acting weird when used to define negative values for paddings when fitting an object the screen, which used to work fine on previous versions

The following code **works well but does not provide the result I am expecting** (any not negative number works fine in this example)
`controls.fitTo(scene.getObjectByName("MeshName"), true, {paddingTop: 0})`

While the following one **moves the camera to the center of the scene** instead of fitting the object in the screen (any negative number will not work properly in this example)
`controls.fitTo(scene.getObjectByName("MeshName"), true, {paddingTop: -1})`

Anything I am missing here or this is actually how the updated version of this function should behave?

**Comment by yomotsu** [comment]
`fitTo()` with negative padding works for me.
![3](https://user-images.githubusercontent.com/212837/97986426-06afc700-1e1d-11eb-9973-9235c3b4b4d9.gif)

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
