### ISSUE TITLE
Set the same action to mouse buttons disable the dragging

### ISSUE THREAD

**Issue by jbailly1** [yomotsu/camera-controls#150]
Hello, in my company we sometimes want to assign the same action to the left / right buttons.
But when I press the left and press the right button, without release the left, the dragging disabled.
To be reactivate it, I must press middle button.

I search a little bit in the camera-controls and found that in the mouseDownEvent,
if the previous state is the same that the wanted, you do not startDragging.

What we expect, is that the right button in our sample become the active button.

Waiting for your answers.
Thanks

**Comment by yomotsu** [comment]
Thanks for your report with the details.
I'll take a look.

**Comment by yomotsu** [comment]
@yomotsu 

> if the previous state is the same that the wanted, you do not startDragging.

This supposed to be, if the previous state is the same, end it. then start another.

**Comment by jbailly1** [comment]
Sorry I have a busy week.
After I test it in the dev branch the bug is not present since this [pullrequest ](https://github.com/yomotsu/camera-controls/pull/145/commits/f176df01756ed4b88852d1053a2460c93f1d5594).
Because it's not in master yet and the release version. I had that bug.
So I think we could close until the fix will be in the next release version.

**Comment by yomotsu** [comment]
Sorry for the delay too.
Good to hear that.

I just publish it. (sorry I completely forgot it😅)

**Comment by jbailly1** [comment]
No problem, thanks.
But you idea with the button state can be good.
