### ISSUE TITLE
Several examples still uses `fitTo` instead of `fitToBox`

### ISSUE THREAD

**Issue by FMS-Cat** [yomotsu/camera-controls#153]
Related: https://github.com/yomotsu/camera-controls/pull/139

**Comment by yomotsu** [comment]
Uh oh, nice finding
![image](https://user-images.githubusercontent.com/212837/101648404-1f934400-3a7d-11eb-88c8-11c9fc1911d3.png)

**Comment by yomotsu** [comment]
Thanks! should be okay now!
