### ISSUE TITLE
how can I make the camera "not targeted"

### ISSUE THREAD

**Issue by arapps3d** [yomotsu/camera-controls#156]
Hi! I am trying to implement a solution where you click on the floor of a room and the camera moves there.
The position change already works with raycasting on the floor and setPostion. 

However, the camera always looks at the center target. I simply want the cam to keep it's rotation and only set the new position. 
Exactly like the navigation in this example : https://showroom.littleworkshop.fr/

Maybe something like camera.targeted = false;
Anyone with a idea to achieve this?
Thank you very much!

**Comment by arapps3d** [comment]
ok, nevermind, i thnk i figured something out

**Comment by yomotsu** [comment]
Good to hear that!
You can also check this example
https://yomotsu.github.io/camera-controls/examples/first-person.html
