### ISSUE TITLE
WASD controls while Mouse down adds unwanted speed to movement

### ISSUE THREAD

**Issue by harrycollin** [yomotsu/camera-controls#157]
I'm trying to create a first person control where you can move around with the keyboard and have drag to look controls with the mouse. When moving and dragging at the same time you get unwanted speed boosts and instability. 

To reproduce in example: 

#1 Move forward using W
#2 Click mouse button

Example: https://codesandbox.io/s/flamboyant-https-ss4kp?file=/src/index.js

**Comment by schwampf** [comment]
Hi,

today I tried exactly the same with and I was facing the same problem. Did you maybe find a workaround?

**Comment by harrycollin** [comment]
Unfortunately not. It would be nice if it was fixed

**Comment by yomotsu** [comment]
It's actually a little bit hard to fix. However, if you are referring to the old `examples/keyboard.html`, you can fix with https://github.com/yomotsu/camera-controls/commit/372d9878d586c6fad7ba27589a2d4ee6c6cdc16f

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
