### ISSUE TITLE
Mouse scroll zoom transition option 

### ISSUE THREAD

**Issue by sungle3737** [yomotsu/camera-controls#161]
I find minZoom, maxZoom options not in README properties about zoom.

But I think there is no option which can change default zoom method when scroll mouse.

Like this [example](https://threejs.org/examples/?q=trackb#misc_controls_trackball)  - `staticMoveing` - `false`

**Comment by sungle3737** [comment]
Or more precise control of zoom

**Comment by yomotsu** [comment]
Thanks for your suggestion.
Nice finding. `.minZoom` and `.maxZoom` should be added to the Readme doc.
I'll add them later.

To change the behavior, [this example](https://yomotsu.github.io/camera-controls/examples/config.html) might be helpful.
Try to change `cameraControls.mouseButtons.wheel`.

**Comment by sungle3737** [comment]
Thanks for great example
But that example also do not has transition when I zoom camera by scrolling mouse

Can't I make camera truck or zoom **with transition** when I wheel mouse??

**Comment by yomotsu** [comment]
Sorry, unfortunately, wheel scrolling does not support smooth movement in windows.

**Comment by sungle3737** [comment]
OK, I resolved my issue by change `.dollySpeed` from 1 to 0.1

but I wish to add `.zoomSpeed` option later.
I think current zoom speed share `.dollySpeed` option
