### ISSUE TITLE
Invalid camera z-position when zooming orthographic camera with "dolly to cursor"

### ISSUE THREAD

**Issue by diredev** [yomotsu/camera-controls#162]
In my code I use an orthographic camera with the new "dolly to cursor" option enabled. Now, if the camera is pointed directly in a main direction (front, back, left, right, etc.) and the user zooms using the mouse wheel, the geometry suddendly "disappears".

This can easily be reproduced in the [orthographic camera example](https://yomotsu.github.io/camera-controls/examples/orthographic.html) too. The camera is already facing directly front-to-back, so you just need to check the "dolly to cursor" checkbox and zoom using the mouse wheel once.

Upon further investigation it seems that an invalid z value is applied to the camera position. The example code starts at z=100. Zooming the camera in "dolly to cursor" mode will change this to crazy values like 592007426553431.5, -98846975032398, etc.

**Comment by yomotsu** [comment]
Thanks for your report.

I found the probrem in the lib.
The following `quaternion.dot( camera.up )` could become almost `0`, then the z value will eventually be a large number.
https://github.com/yomotsu/camera-controls/blob/4fd90fc439d10a786c3b97032b99002b587f936e/src/CameraControls.ts#L1420

The divisor should be `1` if the length of camera direction vector is 1, i guess.

**Comment by yomotsu** [comment]
I think this has been fixed✨✨

**Comment by diredev** [comment]
I can confirm that the issue has been fixed in the new release.
Thank you for the amazingly quick fix 👍
