### ISSUE TITLE
Completely breaks upon initialising "DragControls"

### ISSUE THREAD

**Issue by sticks-stuff** [yomotsu/camera-controls#167]
Running
```javascript
import { DragControls } from 'three/examples/jsm/controls/DragControls.js';
const dragControls = new DragControls( [], camera, renderer.domElement );
```
completely stops camera-controls from working at all

**Comment by msemtd** [comment]
I would have thought that combining multiple controls is unspecified behaviour.

**Comment by yomotsu** [comment]
@sticks-stuff 
Sorry for the delay.

> combining multiple controls is unspecified behavior.

That's right. both use mouse/touch move event of `renderer.domElement` and `event.preventDefault()`.

However, I guess, you could (I've not tried though):

1. declare `new CameraControls` before another controls.
2. disable CameraControls ( `cameraControls.enabled = false` ) to release `event.preventDefault` of the CameraControls
3. then, DragControls should work.
4. When you need CameraControls, `cameraControls.enabled = true`

**Comment by yomotsu** [comment]
Closing due to lack of feedback
