### ISSUE TITLE
Emitting events ('controlend', 'sleep', etc.) is not consistent

### ISSUE THREAD

**Issue by phaseIV** [yomotsu/camera-controls#168]
Some events are not emitted consistantly, for instance when a user changes control in one motion, ie. from dragging to zooming. Sometimes zooming doesn't emit an event at all; then a dragging motion is required to get events emitting again.

**Comment by michael-erskine** [comment]
I'm using the `controlstart` and `controlend` events for just changing the onscreen cursor so they're not very important in my applications, but I use the `update`, `wake`, and `sleep` events for controlling background tasks. I haven't noticed any problems with the events not working or firing inconsistently. Can you easily repeat the problems? Also is it a dolly or a zoom action that fails to emit an event?

**Comment by looeee** [comment]
I've been using the events quite a bit over the past month and I haven't noticed any issues. @phaseIV can you provide a working example that demonstrates the issue?

**Comment by phaseIV** [comment]
Sorry, I lost track of this issue. I remember trying to improve the 'idle' behaviour of my code and these improvements must have caused the issues for camera-controls. Closing.
