### ISSUE TITLE
Ortho dollyToCursor changes target depth

### ISSUE THREAD

**Issue by ervinoro** [yomotsu/camera-controls#169]
Can be observed in the orthographic example:

- left click rotates around the center of the cube
- check dollyToCursor
- zoom in (with the cursor approximately in the middle of the cube)
- suddenly left click rotates around a point in front of or behind the cube

**Comment by roman-kh** [comment]
Apparently related to #239

**Comment by yomotsu** [comment]
I think this problem has finally been fixed at https://github.com/yomotsu/camera-controls/pull/322
