### ISSUE TITLE
How do I get object/mesh information on mouseover? Here's how I did it in OrbitControls.

### ISSUE THREAD

**Issue by cyrusadkisson** [yomotsu/camera-controls#170]
Is it possible in camera-controls to get information about objects on mouseover? Here's how I did it in OrbitControls
```
function render() {
    raycaster.setFromCamera(mouse, camera);
    // calculate objects intersecting the picking ray
    var intersects = raycaster.intersectObjects(scene.children, true);
    if (intersects.length > 0) {
        if (typeof intersects[0].object.userData.col !== "undefined") {
            // write information into a div
        }
        else $("#tileinfobodydiv").html("Mouse over a tile to see more info.");
    }
    renderer.render(scene, camera);
}
```
Thanks in advance for the help!

**Comment by yomotsu** [comment]
I think it's better to use three.js feature rather than camera-controls, just like what you do above.
Maybe `CameraContols` instance could have a getter for the camera object though.

**Comment by cyrusadkisson** [comment]
Ok yes I see that now. It's a three.js feature, not a camera feature. Got it working. Thanks!
