### ISSUE TITLE
Trackball-like behavior

### ISSUE THREAD

**Issue by robertoranon** [yomotsu/camera-controls#174]
Hi,

  is it possible to obtain a trackball-like behavior (i.e. rotating without maintaining a constant up vector)?

Thanks!

**Comment by yomotsu** [comment]
Hi,

What you are looking for is probably [ControlsTrackball](https://threejs.org/examples/#misc_controls_trackball), I guess?

**Comment by robertoranon** [comment]
Yes, precisely, that kind of behavior, I should have specified I am aware of that piece of code. However, in my application I'd like to handle the same kind of interaction with camera-controls library. I guess from your reply that this is not possible, but I think it could be integrated. Do you have any suggestion on how to do that?

**Comment by yomotsu** [comment]
Unfortunately, this lib focusing on Orbital movement😢
You could use the `ControlsTrackball` class and extend to add some methods to control, I guess.

**Comment by marcatec** [comment]
Doesn't this example show a Trackball behavior?
[z-up camera](https://yomotsu.github.io/camera-controls/examples/camera-up.html)

**Comment by robertoranon** [comment]
No, it's an orbit camera with a Z up axis. Slight difference, maybe, but the rotation of the camera in response to mouse or touch is different

**Comment by marcatec** [comment]
> No, it's an orbit camera with a Z up axis. Slight difference, maybe, but the rotation of the camera in response to mouse or touch is different

You are right. On a second try I realized the point of "Z up".
