### ISSUE TITLE
Infinity Dolly doesn't support dollyToCursor

### ISSUE THREAD

**Issue by cotlod** [yomotsu/camera-controls#175]
When enabling dollyToCursor while using infinityDolly, the way infinityDolly works cause the camera to dolly in an incorrect way.

**Comment by yomotsu** [comment]
I guess, `minDistance` is too small.
What if you set `cameraControls.minDistance = 1` or so?

**Comment by cotlod** [comment]
still happens with a value like 1.  [example](https://imgur.com/a/PgZKUBj)

**Comment by yomotsu** [comment]
closed by merge of https://github.com/yomotsu/camera-controls/pull/192
