### ISSUE TITLE
Wheel, Touch Listener is not passive

### ISSUE THREAD

**Issue by klich3** [yomotsu/camera-controls#176]
At the time of assigning Scroll / Touch Listeners, Chrome show Warnings from that Listeners are not passive.

You can solve that with:

[https://stackoverflow.com/questions/46542428/warning-added-non-passive-event-listener-to-a-scroll-blocking-touchstart-even](url)

![Captura de pantalla 2021-05-05 a las 12 16 11](https://user-images.githubusercontent.com/2700881/117126916-b7caf600-ad9b-11eb-8d70-b8e1d45c8d1e.png)

**Comment by yomotsu** [comment]
Thanks for your report.

The problem should be solved with https://github.com/yomotsu/camera-controls/commit/d57647e29fa19f583e1f7a988310d98e5969e4a3 and v1.28.2 is available
