### ISSUE TITLE
First person truck not working

### ISSUE THREAD

**Issue by farfromrefug** [yomotsu/camera-controls#177]
First thank you for your amazing lib.
i am trying to integrated it in my "map view" demo https://farfromrefug.github.io/geo-three/examples/index.html
As you can see if you run the demo the rotation is working but not the truck and i dont understand why.
Here is the code https://github.com/farfromrefug/geo-three/blob/master/examples/app.js#L1109

Would you have any idea on why the i cant "move" around?

thanks

**Comment by yomotsu** [comment]
Thanks for using the lib.
Would you mind providing a simplified and editable example that focusing on the problem exclusively?

The code you shaded is a bit long to understand whats going on😢

**Comment by farfromrefug** [comment]
@yomotsu found the issue. the reason was the "size" of my world. Due to it i had to have a much bigger truck speed.

Thanks
