### ISSUE TITLE
Having trouble with lerpLookAt

### ISSUE THREAD

**Issue by HarikalarKutusu** [yomotsu/camera-controls#181]
First of all, thank you for this nice software.

I'm pretty new (less than two months) to three.js and decided to make a virtual exhibition for an exhibition I designed (opened last week). I found out that no existing controller could do what I want and camera-controls is the best fit as far as I can see. Although it is based on orbit controls, I could manage to use it as a first-person controller. I have keyboard, mouse, nipplejs navigation but a limited number of beta testers (read family & friends) asked me if I can add a feature so that if one clicks on an exhibition panel, one would go in front of that panel with exact orientation.

While working on this, I'm stuck with a problem: Panels are two-sided (one BoxBufferGeometry, two sides with images). One side of a panel is OK, but the opposite side does not work as intended.

I uploaded it to a beta site, please visit it: http://vxtest.harikalarkutusu.com/

On PC, Right-Click a panel, it will also show the calculated normals. If you navigate to the other side and do the same, you go to the other side of the panel. The positions I get through console log's are correct, but the camera-controller goes somewhere else with lerpLookAt...

This is the relevant code after a raycaster. I kept the debug code to show the results.

```js
          const visitorPanelDistance = 1.0;
// get current values
          this._getPositions(); // gets the positions from CameraControls into curPos and curTarget
          console.log('curPos', this.curPos);
          console.log('curTar', this.curTarget);
// get mesh
          const mesh = o.object as Mesh; // o is intersects[0], I use userdata to filter out irrelevant meshes
          mesh.updateMatrixWorld(true);
          const m4 = mesh.matrixWorld;
          let meshPos = mesh.position.clone();
          meshPos.applyMatrix4(m4);
// get face normals
          const normalMx = new Matrix3().getNormalMatrix( mesh.matrixWorld );
          const face = o.face as Face;
          let normal = face.normal.clone().applyMatrix3( normalMx ).normalize();
          normal = roundVector(normal, 3);
// new visitor move target
          let visitorGoTo = meshPos.clone().add(normal.multiplyScalar(visitorPanelDistance));
          visitorGoTo = roundVector(visitorGoTo, 3);
// debug
          console.log('face.normal', face.normal);
          console.log('normal', normal);
          console.log('meshPos', meshPos);
          console.log('visitorGoTo', visitorGoTo);
// helper
          const point = o.point;
          console.log('point', point);
          const arrowHelper = new ArrowHelper(normal, point, visitorPanelDistance, '#ff00ff');
          this.glb.scene.add(arrowHelper);
          // move
          this.cameraControls.lerpLookAt (
            this.curPos.x, this.curPos.y, APP_CONF_VISITOR.eyeLevel,
            visitorGoTo.x, visitorGoTo.y, APP_CONF_VISITOR.eyeLevel, 
            visitorGoTo.x, visitorGoTo.y, APP_CONF_VISITOR.eyeLevel, 
            meshPos.x, meshPos.y, APP_CONF_VISITOR.eyeLevel, 
            1,
            true
          )
// more debug
          setTimeout(() => {
            this._getPositions();
            console.log('curPos', this.curPos);
            console.log('curTar', this.curTarget);
            console.log('meshPos', meshPos);
          }, 1000);
```

This is the debug output if you right-click the panel in front of you (red sphere shows target position 1 meter ahead):
```log
curPos Vector3 {x: -5, y: -15, z: 1.5}
curTar Vector3 {x: -5, y: -14, z: 1.5}
face.normal Vector3 {x: 0, y: -0, z: 1}
normal Vector3 {x: 0, y: -1, z: 0}
**meshPos Vector3 {x: -5, y: -6.25, z: 1.25}**
**visitorGoTo Vector3 {x: -5, y: -7.25, z: 1.25}**
point Vector3 {x: -4.832284678935199, y: -5.03999999910593, z: 1.0527591438271977}
**curPos Vector3 {x: -5, y: -7.25, z: 1.5}**
**curTar Vector3 {x: -5, y: -6.25, z: 1.5}**
meshPos Vector3 {x: -5, y: -6.25, z: 1.25}
```
The side is correct, debug data is correct, but the position is not. But if you navigate to the other side and right-click, you get:
```log
curPos Vector3 {x: -8.419492927207939, y: -1.1085569352388345, z: 1.5}
curTar Vector3 {x: -7.837601356640838, y: -1.9218233123275086, z: 1.5}
face.normal Vector3 {x: 0, y: 0, z: -1}
normal Vector3 {x: 0, y: 1, z: -0}
**meshPos Vector3 {x: -5, y: -6.25, z: 1.25}**
**visitorGoTo Vector3 {x: -5, y: -5.25, z: 1.25}**
point Vector3 {x: -5.090533736729643, y: -4.960000000894069, z: 0.9790723870309959}
**curPos Vector3 {x: -5, y: -5.25, z: 1.5}**
**curTar Vector3 {x: -5, y: -6.25, z: 1.5}**
meshPos Vector3 {x: -5, y: -6.25, z: 1.25}
```
Debug data is correct, but the position and side are wrong. As you will see, the controller is on the other side of the panel.

The result is the same if I hard-code the positions to lerpLookAt.

I'm dealing with this for a week now (among other stuff) and couldn't find out why this is happening. I looked at the source but I have to refresh my math knowledge after 40 years, which might take some time... Perhaps you could find the reason, I'll very much appreciate it.

BTW, do visit the exhibition. I prepared it for a small city museum, Museum of the Princess' Islands (Istanbul). And I'm also open to any suggestions in any aspect...

**Comment by yomotsu** [comment]
Thanks for using the lib.
However, your question is too long to understand the context...😢

If you think this is a sort of bug, would you mind preparing a simplified example just to reproduce the problem, please?

**Comment by HarikalarKutusu** [comment]
You were right, I copied one of your examples and implemented some simulated movements and they are working just fine. Must be my part of the code (probably "my other right" sort of stuff)...

If you or anybody likes to have a camera.up & lerp example, it is attached...

[test.zip](https://github.com/yomotsu/camera-controls/files/6544108/test.zip)
