### ISSUE TITLE
Method suggestion: fitToFace

### ISSUE THREAD

**Issue by HarikalarKutusu** [yomotsu/camera-controls#182]
CameraController.fitToFace(face: THREE.Face)

Current fitTo implementations do not take a direction into account. Given a face and its normal, this can be accomplished.

Just an idea...

**Comment by yomotsu** [comment]
How about using `getDistanceToFitBox( boundingRectWidth, boundingRectHeight, 0 )` to get the dolly distance?

**Comment by HarikalarKutusu** [comment]
Yes, getDistanceToFitBox will solve one part of the problem, it perfectly does that in fitToBox & fitToSphere. Result of getDistanceToFitBox will be multiplied with the normal vector, which will further be added to the face's world location to calculate destination position, with face being the target.
That would mean you would also need the mesh.matrixWorld...

CameraController.fitToFace(mesh: THREE.Mesh, face: THREE.Face)

I cannot provide a generalized algorithm thou, I'm not proficient. My current implementation uses exhibition display panels which are thin in nature. I cannot imagine what would be needed in complex geometries.

**Comment by yomotsu** [comment]
I'm not sure this feature would be nice to have a part of the lib.

- three.js does not have Face in the core.
- Face is a triangle, and I don't think fitting the triangle is useful for general use
- We already have several functions, that can be used to simulate it

Thus I think this should be done in user-land...

**Comment by HarikalarKutusu** [comment]
OK.
The suggestion was based on UX feedback. In practical applications positioning/orientiering interactively in 3D using keyboard/mouse/touch was not easy for users.
