### ISSUE TITLE
Q: About movement speed

### ISSUE THREAD

**Issue by HarikalarKutusu** [yomotsu/camera-controls#184]
If we use camera-controls interactively one can specify how much to move. On the other hand, if we use setXXX methods the movement is unnaturally rapid. As far as I can see the dampingfactor is the only parameter I can handle, but this time the acceleration/deceleration durations become unnatural.

I think a property like "animationSpeed" would be beneficial...

Or, I'm missing something.

**Comment by yomotsu** [comment]
You can use a tween lib.
See https://yomotsu.github.io/camera-controls/examples/easing.html for more details.

**Comment by HarikalarKutusu** [comment]
Yes! I forgot about that, it will be much more beneficial... Thank you...
