### ISSUE TITLE
Feature request: rotateTo only on azimuth or polar

### ISSUE THREAD

**Issue by yannbriancon** [yomotsu/camera-controls#185]
Use case: 

- I need to rotate to a specific azimuthAngle with transition without changing the polarAngle target.

Problem:

- I cannot use rotate because I don't know the delta between the current end azimuthAngle and the new one I want (_sphericalEnd is protected)
- I cannot use rotateTo because I don't know the current end polarAngle (_sphericalEnd is protected)

Proposed solutions:

- Expose _sphericalEnd to let the developer compute his delta
- (Preferred) Allow rotate and rotateTo to take only azimuthAngle or polarAngle
  - If azimuthAngle or polarAngle is undefined, keep the same _sphericalEnd

**Comment by yomotsu** [comment]
I understand. That would be good to have.

We already have a setter called `azimuthAngle` and `polarAngle`.
https://github.com/yomotsu/camera-controls/blob/4c4bf6f66c79f03affd7099065d61aa1ec194afa/src/CameraControls.ts#L754

Currently, it doesn't have the second argument thus it immoderately set the angle. maybe the setter could have the second argument as `enableTransition: boolean`.

Another idea is adding new methods like:
```
rotateAzimuthTo( azimuthAngleTo, enableTransition )
```
But I'm not confident about the name of the methods...(any suggestions...?)

**Comment by mijofr** [comment]
My suggestion would simply be to allow rotate or rotateTo to be called with something like controls.rotateTo(MATH.PI/2, null, true); A null indicates no change from current.

**Comment by yannbriancon** [comment]
@yomotsu @mijofr 
Here is a PR with my proposal https://github.com/yomotsu/camera-controls/pull/201.
I am happy to discuss other solutions.
Cheers!

**Comment by yomotsu** [comment]
@yannbriancon's PR has been merged and published into npm. (many thanks!)
Closing the issue.
