### ISSUE TITLE
[question] replacing zoom with dolly

### ISSUE THREAD

**Issue by farfromrefug** [yomotsu/camera-controls#186]
I am sorry to ask a question here. Is there a discord or anywhere where we can ask questions about `camera-controls`?

My request revolves around zoom/dolly.
Right now i am using dolly it works great however i would like to test dolly. The reason is my app compute LOD based on camera distance. Using zoom i can adapt LOD while i zoom. Also while dragging when zoomed in the dragging is multiplied by the zoom which makes it almost impossible to drag (it goes away too fast).

Right now i am using this ( my scene is pretty huge, earth size in meters):
```
const FAR = 200000;
const camera = new THREE.PerspectiveCamera(40, window.innerWidth / window.innerHeight, 100, FAR);
camera.position.set(0, 0, EPS);
const controls = new CameraControlsWithOrientation(camera, canvas);
controls.azimuthRotateSpeed = -0.15; // negative value to invert rotation direction
controls.polarRotateSpeed = -0.15; // negative value to invert rotation direction
controls.minZoom = 1;
controls.minDistance = -10000;
controls.maxDistance = 1000;
controls.truckSpeed = 1 / EPS * 60000;
controls.mouseButtons.wheel = CameraControls.ACTION.ZOOM;
controls.touches.two = CameraControls.ACTION.TOUCH_ZOOM_TRUCK;
controls.verticalDragToForward = true;
controls.saveState();
```

I tried to change `controls.mouseButtons.wheel = CameraControls.ACTION.ZOOM;` to `controls.mouseButtons.wheel = CameraControls.ACTION.DOLLY;` but then:
* i actually cant dolly in (must be related to dolly speed and camera settings).
* what bugs be is that when i wheel out the dolly actually seems to follow the path my control had while rotating.

Is that normal with dolly? is it expected? I am not sure as your [example](https://yomotsu.github.io/camera-movement-comparison/dolly-zoom.html) cant rotate.

Maybe i cant do what i want and replace the zoom with dolly in my app? :https://farfromrefug.github.io/geo-three/example/index.html

**Comment by yomotsu** [comment]
Sorry, this lib does not have the place to ask so far...
However, I can give some hints to you.

- [EPS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON) is almost zero, right?
- Thus camera will be placed almost the center by `camera.position.set(0, 0, EPS)`, and dolly which used the delta distance will not work.
- `truckSpeed` is too big by `1 / EPS * 60000` which contain "divide by almost 0".
- `minDistance` can't be a negative number. It's the distance between the focus target and the camera.

**Comment by yomotsu** [comment]
er...but as you said zoom cannot solve LOD...
Do you really need First-Person-View?

First-Person-View and dolly cannot use at the same time.
You could simulate dolly-ish movement with `instance.forward()`

**Comment by farfromrefug** [comment]
@yomotsu first thank you for your fast answer!
Could nt we create a channel for camera-controls in the three.js discord? I think it would be useful to a lot of people. You have the best controls around...

So about my question yes i need first person view. My app is a map / peak finder / explorer. And it is also used in AR so i need first person view. This is why i need the EPS value and the "huge" `truckSpeed`. thank you for explaining `minDistance` and all the rest i was not sure about what i was playing with.

So i guess i will stick to zoom in my app. Maybe i can find a way to have LOD with it.My LOD is based on camera center + distance from camera. I might be able to multiply that by the zoom factor. Will try.

Thanks a lot for clarifying it all for me!

**Comment by yomotsu** [comment]
@farfromrefug 
Thanks for using and contributing too😊

> Couldn't we create a channel for camera-controls

I'm not sure because this lib is still a kinda fun project I think...
I want to encourage to use this lib by more ppl tho...
