### ISSUE TITLE
[FEATURE REQUEST] option to "handle" zoom in dragging

### ISSUE THREAD

**Issue by farfromrefug** [yomotsu/camera-controls#187]
Right now if you dragged while zoomed the dragging is "multiplied" by the zoom factor making it hard to move around.
Could we have an option to "slow down" the dragging while zoomed?
I test it locally and replacing:
```typescript
this.rotate( theta, phi, true );
```
with 

```typescript
this.rotate( theta / _this._zoom, phi / _this._zoom, true );
```
[here](https://github.com/yomotsu/camera-controls/blob/4c4bf6f66c79f03affd7099065d61aa1ec194afa/src/CameraControls.ts#L304 ) gets the right behavior

I can create a PR i just need to figure out how to name that option

**Comment by yomotsu** [comment]
How about make `xxxInternal()` extendable?

```js
class CameraControls {
	constructor() {
		...
	},

	protected _rotateInternal( deltaX: number, deltaY: number ): void => {
		...
	}
}
```
then users can modify internal functions:

```js
class MyCameraControls extends CameraControls {
	constructor() {
		super();
	}

	_rotateInternal( deltaX: number, deltaY: number ): void => {
		// what ever
	}
}
```

**Comment by farfromrefug** [comment]
@yomotsu i was actually about to ask you to move all functions as class functions so that they can be extendable :D

**Comment by yomotsu** [comment]
We also need to move [`elementRect`](https://github.com/yomotsu/camera-controls/blob/4c4bf6f66c79f03affd7099065d61aa1ec194afa/src/CameraControls.ts#L302-L303) (and maybe others) to be private too, but It's okay for me.

Do you have some time to make a PR for it?
I could do that this weekend tho.

**Comment by farfromrefug** [comment]
@yomotsu let me know what you think https://github.com/yomotsu/camera-controls/pull/188

**Comment by yomotsu** [comment]
Handler methods can be customized by https://github.com/yomotsu/camera-controls/pull/189
Closing the issue.
