### ISSUE TITLE
update camera controls from quaternion

### ISSUE THREAD

**Issue by farfromrefug** [yomotsu/camera-controls#190]
I have implemented a subclass of `CameraControls` which also support deviceorientation.
Using this:
```
update(delta: number)
	{
		if ( this.deviceOrientationEnabled) 
		{
			var alpha = this.deviceOrientation.alpha ? this.deviceOrientation.alpha * TO_RAD + this.alphaOffsetAngle : 0; // Z
			var beta = this.deviceOrientation.beta ? this.deviceOrientation.beta * TO_RAD + this.betaOffsetAngle : 0; // X'
			var gamma = this.deviceOrientation.gamma ? this.deviceOrientation.gamma * TO_RAD + this.gammaOffsetAngle : 0; // Y''
			var orient = this.screenOrientation ? this.screenOrientation * TO_RAD : 0; // O

			if (this.screenOrientation % 180 === 0) 
			{
				if (Math.abs(this.deviceOrientation.beta) <10 && Math.abs(this.deviceOrientation.gamma) >80) 
				{
					wrongOrientation = true;
				}
				else 
				{
					wrongOrientation = false;
				}
			} 

			this.setObjectQuaternion( this._camera.quaternion, alpha, beta, gamma, orient );
			this.alpha = alpha;
			this.beta = beta;
			this.gamma = gamma;
			this.dispatchEvent( {
				type: 'update',
				originalEvent: null
			});
			return true;
		}
		else 
		{
			return super.update(delta);
		}
	}
```
I can support both modes in real time. I even added a custom rotate method which also works during device orientation and applies a "delta" to the device orientation.

Now the issue i have is that the `quaternion` of device orientation is applied directly to the camera. Thus CameraControls does not know about it. So when i stop device orientation the CameraControls jumps back to the position it was before device orentations starts.
One way to fix this would be for CameraControls to have a method to set all its parameters from a quaternion ( i mean rotate parameters obviously). Do you think that would be possible?

**Comment by yomotsu** [comment]
`this._camera` must be controlled by `this._sphericalEnd` in the lib.
convert the quaternion to polar coordinates system to get the angle, then use `cameraControls.rotate()` method.

**Comment by farfromrefug** [comment]
@yomotsu fair enough i can do it that way to.  though i am not sure on how to do `convert the quaternion to polar coordinates system` :s Sorry i am not that good yet with camera and stuff ;)

**Comment by farfromrefug** [comment]
@yomotsu so i got rotateTo to work from quaternion (returned from device orientation) however i still have an issue. Your `rotateTo` only supports 2 of the 3 axes. Anyway to apply the 3 euler angle rotation?

**Comment by yomotsu** [comment]
I think you can get the 2 angles if you use polar coordinates system.

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
