### ISSUE TITLE
Focal Offset mess up the raycaster

### ISSUE THREAD

**Issue by cederache** [yomotsu/camera-controls#191]
Hi,
I tried to use the FocalOffset with the moveTo function to set a pivot point when I click on an object (using a Raycaster)
To debug this, I add a red sphere on the intersection.point position when I double click.

The first time, it's good, the red sphere is where I clicked.
But after that, the red sphere pop at a completely different position.

Is there a function / update I should call to fix the raycaster ?

Here is a video where I do not use the focal offset
<video src="https://user-images.githubusercontent.com/3966864/121153766-a4052a80-c846-11eb-9ce4-181527e75e13.mov"></video>

Here is a video where I set the option : this.controls.mouseButtons.right = CameraControls.ACTION.OFFSET;
I made a right click between the first and the second red sphere
<video src="https://user-images.githubusercontent.com/3966864/121153790-a8c9de80-c846-11eb-990a-6f6cbbd2aab8.mov"><video>

**Comment by cederache** [comment]
The raycaster is used like this :
`this.raycaster.setFromCamera(mouseCoordsNormalized, this.viewer.camera);`

The code used after the raycaster intersectWithObjects is this :
`this.controls.moveTo(intersect.point.x, intersect.point.y, intersect.point.z, enableTransition);`

**Comment by yomotsu** [comment]
Thanks for your report. the video is really helpful, however, I cannot reproduce the problem.
Would you mind preparing the simplest working example in JSFiddle or so, please?

**Comment by cederache** [comment]
I think the solution with a camera jump issue #130 is kind of linked to this

**Comment by yomotsu** [comment]
I think it works correctly

<video src="https://user-images.githubusercontent.com/212837/121204369-d0a25c00-c8b1-11eb-8a7d-ab482b36efb5.mov"></video>

**Comment by cederache** [comment]
😮 Thanks

So the if (updated) was the issue.

But why ?
It's the same code as your focalOffset example : https://github.com/yomotsu/camera-controls/blob/42b76b7598701f22746a794c0f744ade35ecaec9/examples/focal-offset.html#L74

**Comment by Aierklk** [comment]
Is there any way to change orbit point and don't change the camera position?

**Comment by cederache** [comment]
@Aierklk That's the purpose of the #130 ;-)

**Comment by Aierklk** [comment]
> @Aierklk That's the purpose of the #130 ;-)

Thanks

**Comment by yomotsu** [comment]
maybe...?

```js
const _v3 = new THREE.Vector3();
const xcol = new THREE.Vector3();
const ycol = new THREE.Vector3();
const zcol = new THREE.Vector3();

const setOrbitPoint= ( x, y, z ) => {

	xcol.setFromMatrixColumn( cameraControls._camera.matrixWorldInverse, 0 );
	ycol.setFromMatrixColumn( cameraControls._camera.matrixWorldInverse, 1 );
	zcol.setFromMatrixColumn( cameraControls._camera.matrixWorldInverse, 2 );


	xcol.multiplyScalar(   x );
	ycol.multiplyScalar( - y );
	zcol.multiplyScalar(   z );

	_v3.copy( xcol ).add( ycol ).add( zcol );
	cameraControls.setFocalOffset( _v3.x, _v3.y, _v3.z, true );
	cameraControls.moveTo( - x, - y, - z, true );

	console.log( _v3 );
	// also need to consider the cameraControls.distance.
	// calc the diff between "current cameraControls.distance" and "distance between new orbitPoint and current camera position".
	// then apply the diff with dolly() or so...I guess

}
```

**Comment by cederache** [comment]
It seems that it does not work when I put your code in my. The orbit point is not at the intersect point but at the opposite side of the box... 🤔

I updated the codepen if you want to try : https://codepen.io/cederache/pen/YzZjXWV

https://user-images.githubusercontent.com/3966864/121703005-aaa7d200-cad2-11eb-89d4-d5012e3bd0ff.mov

**Comment by Aierklk** [comment]
@yomotsu Thanks your response.This function can set orbit,but when you move the camera to set the orbit again,the camera position will changed.I will post a video about this problem in a while.

**Comment by yomotsu** [comment]
Sorry, make negate them.

```
_xCol.multiplyScalar( - x );
_yCol.multiplyScalar(   y );
_zCol.multiplyScalar( - z );

_v3.copy( _xCol ).add( _yCol ).add( _zCol );
cameraControls.setFocalOffset( _v3.x, _v3.y, _v3.z, false );
cameraControls.moveTo( - x, - y, - z, false );
```

**Comment by Blocovin** [comment]
@yomotsu Can you share JSFiddle or CodePen example ?

It doesn't seems to work : https://codepen.io/blocovin/pen/poeQwjq.

**Comment by ketourneau** [comment]
@yomotsu Did you have time to look at this issue ?
We want to offer this feature to our users.

**Comment by ketourneau** [comment]
We solved the problem by updating the world camera matrix before raycast

```
camera.updateMatrixWorld();
raycaster.setFromCamera(coords, this.viewer.camera);
```

**Comment by yomotsu** [comment]
I think this can be closed thanks to @ketourneau 's PR: https://github.com/yomotsu/camera-controls/pull/213
