### ISSUE TITLE
Decelerate when approaching bounds

### ISSUE THREAD

**Issue by alexpineda** [yomotsu/camera-controls#193]
Is there a relatively simple approach to decelerate while approaching the box bounds so it's not a jarring stop?

**Comment by yomotsu** [comment]
Do you mean bouncing back on the edge or so? Unfortunately, there is no feature for that, I think...😢
However, If you found a nice way, I'll be happy to receive the PR.

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
