### ISSUE TITLE
Cannot change camera using mouse on 1.29.0

### ISSUE THREAD

**Issue by diredev** [yomotsu/camera-controls#199]
## Describe the bug
I cannot rotate or pan the camera at all when using mouse controls on the new version 1.29.0. Zoom using the mouse wheel works, as does changing the camera position using API commands.

## To Reproduce
Can easily be reproduced on the examples provided in the README.
Just launch the "basic" example and try to rotate or pan.

## Platform:
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, Firefox

**Comment by michael-erskine** [comment]
Confirmed. These are the event listeners on the canvas for https://yomotsu.github.io/camera-controls/examples/basic.html

![image](https://user-images.githubusercontent.com/74360165/125046625-19f2f080-e096-11eb-86a1-5cb6c87611a0.png)

**Comment by michael-erskine** [comment]
It appears that the `onMouseDown_1` handler is not added due to `isPointerEventsNotSupported`
![image](https://user-images.githubusercontent.com/74360165/125047299-bcab6f00-e096-11eb-8b67-0c024fad7857.png)

**Comment by bcomnes** [comment]
Ran into this today. `1.28.4` still working great though.

**Comment by yomotsu** [comment]
Sorry, I forgot to enable the PointerEvent start handler.
https://github.com/yomotsu/camera-controls/commit/a727d1366dae077fdb3d844c4137546c76b1ef9b

v1.29.1 should work correctly

**Comment by bcomnes** [comment]
No problem thanks for the fix! Will try it Monday.

**Comment by diredev** [comment]
I can confirm that 1.29.1 has fixed this issue 👍
