### ISSUE TITLE
minPolarAngle/maxPolarAngle

### ISSUE THREAD

**Issue by gigablox** [yomotsu/camera-controls#2]
Thanks for putting so much time into this. Really great work on this plugin.

https://threejs.org/docs/index.html#examples/controls/OrbitControls

There's a setting called minPolarAngle/maxPolarAngle where it restricts a user from rotating above and below certain restraints. Wondering how hard it would be to implement something like this in this solution?

**Comment by yomotsu** [comment]
Thanks for your request.
I've added minPolarAngle/maxPolarAngle limitation🎉
and available on ver `1.1.0`

If you are iterested, see the changes.
https://github.com/yomotsu/camera-controls/pull/3/files

**Comment by gigablox** [comment]
So cool! Thank you for this!!
