### ISSUE TITLE
problem sharing position between two cameras

### ISSUE THREAD

**Issue by tomthebearded** [yomotsu/camera-controls#202]
Hi

I have an angular component in which i create a threejs instance with a scene with a 3d object and a camera control, the 3d must always look at the camera position.
Everything works perfectly.
When i try to use the component twice in a page to have two scenes side by side i would like to share the camera positions, if i move the camera on the left scene the right camera scene should move.

I achieved this by outputting from the component the controls reference and, in the angular component that contains the two threejs components, i've done this
```
  this.controls1.value.addEventListener("control", _ => {
      const p = this.controls1.value.camera.position;
      this.controls2.value.setPosition(p.x, p.y, p.z, false);
    })
    this.controls2.value.addEventListener("control", _ => {
      const p = this.controls2.value.camera.position;
      this.controls1.value.setPosition(p.x, p.y, p.z, true);
    })
  } 
```
this is also working, but with a catch, if i enable the transition like in the second controller the other camera movement follow the first smoothly but with the transition delay.

Instead, if i disable the transition like the first controller the second camera follows the other but with an ugly stuttering effect.

Is there a way to fix this? 
If not, is it possibile to accelerate the transition movement to reduce the delay?

I've made an example available at this link
https://stackblitz.com/edit/angular-ivy-26zmbt?file=src/app/app.component.ts
If you move the camera on the left you can see the stuttering on the right, mostly when you change direction, otherwise if you move the camera on the right you can see that on left it moves without issues but the delay is too much for what i need.

Thanks in advance

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
But sorry, your question seems your app problem...
Please read the doc and ask your team member.

(You can use 'update' before rendering to sync.)

**Comment by tomthebearded** [comment]
I've tried using update but that doesn't change anything.
at least is there a way (that i have not found in the docs) to change the transition speed? that could solve my problem.

I've also noticed that if i set the dampinFactor to 0 to not have the inertia there is an issue. After the camera stop if i click anywhere (just one click) the camera moves in the previous direction like it's following the inertia that i'have disabled.

**Comment by yomotsu** [comment]
Sorry I meant 'update' event instead of 'control' event.
Anyway, the camera-controls is not a paid project and is just a personal project.
Please understand this sort of HELP would be ignored.

If you think that is a bug, please make a bug report issue.
Thanks again for using camera-controls.

**Comment by tomthebearded** [comment]
thank you!!! using update has solved the issue!
