### ISSUE TITLE
Expose speed parameter for enableTransition.

### ISSUE THREAD

**Issue by laffan** [yomotsu/camera-controls#204]
Ideally this could both be set globally @ the install step or just as as a # when the parameter is being set, (ie. `moveTo( x, y, z, 0.5 )`.

**Comment by yomotsu** [comment]
Do you mean `.dampingFactor`?

**Comment by klich3** [comment]
Iaffan, would like to say is TWEEN value for timing of transition. 

If you use GSAP, you can controll it like this:

```
gsap.to(cameracontrol.camera, {
    {x: 1, y: 1, z: 1},
    duration: 2,
    ease: "power1.inOut",
    onUpdate: () => {
         cameracontrol.moveTo(camera.position.x, camera.position.y, camera.position.z, false); //false for disable tween incorporated, for replace-it with gsap.
   }
})
```

**Comment by looeee** [comment]
Now that methods are thenable you can adjust the speed of a transform like this:

``` js
const initialDamping = controls.dampingFactor;

controls.dampingFactor = 5; // set it to whatever speed you like
await controls.moveTo( x, y, z, true);

// now reset the dampingFactor
controls..dampingFactor = initialDamping;
```

@yomotsu I wonder would it be possible to do this automatically by adding an optional extra parameter?

```
controls.moveTo( x, y, z, enableTransition, overrideDampingFactor);
```

Then `overrideDampingFactor` would be used until the promise for the transition resolves. 
Could be a problem if you perform multiple transition at once though...

**Comment by yomotsu** [comment]
@looeee
Thanks for your suggestion.

> Could be a problem if you perform multiple transition at once though...

Yeah...I concern about that too...And that would be complicated.
I think that should be done in user-land as you suggested.

**Comment by looeee** [comment]
Do you think there's way to calculate duration in seconds from a given damping speed?

**Comment by yomotsu** [comment]
> way to calculate duration in seconds

Actually, I'm not sure...Transitions can be combined with others asynchronously as you know, then the transition duration would be extended. Therefore, "duration" can not be calculated I guess...

If truly controlled "speed and duration" are needed, tween libs can be used as @klich3 mentioned here.
And I think you also have [mentioned](https://github.com/yomotsu/camera-controls/issues/206#issuecomment-903218005)

> Yeah for sure, I'm using Popmotion at the moment.

**Comment by yomotsu** [comment]
@looeee 

> way to calculate duration in seconds

Actually, I'm not sure...Transitions can be combined with others asynchronously as you know, then the transition duration would be extended. Therefore, "duration" can not be calculated I guess...

If truly controlled "speed and duration" are needed, tween libs can be used as @klich3 mentioned here.
And I think you also have [mentioned](https://github.com/yomotsu/camera-controls/issues/206#issuecomment-903218005)

> Yeah for sure, I'm using Popmotion at the moment.

**Comment by looeee** [comment]
Yeah using a third-party is a good workaround. But I was thinking about some utility function like `calculateDampingFromDuration(ms)`. Then you could say you want `lookAt` to run over 1500ms so you'd do this:

``` ts
import { calculateDampingFromDuration } from "camera-controls";

controls.dampingFactor = calculateDampingFromDuration(1500);
controls.moveTo( x, y, z, true);
```

Then the `moveTo` would take 1500ms. 

I guess the result of `calculateDampingFromDuration` would depend on the current control state and the values of  `x, y, z` so it'd be hard to calculate.

**Comment by yomotsu** [comment]
Thanks for the suggestion. it's interesting. We must have the helper, if it's possible.
However, I assume that the duration time is until the `rest` event. If so, the calculation should be complicated I guess...
The transition should be continued after until `sleep` event, but the duration is not...

**Comment by looeee** [comment]
> However, I assume that the duration time is until the rest event

Yeah, that makes it even more complicated I guess :/

**Comment by yomotsu** [comment]
Maybe someday, when we meet the best formula...😢
