### ISSUE TITLE
Orbiting Stutter on Firefox

### ISSUE THREAD

**Issue by EricMaslowski** [yomotsu/camera-controls#211]
Hello,
    First, just want to say great library. It's working great in my project outside of an issue in Firefox (91.0.2) where any interactions stutter while dragging. Automatic transitions are smooth. 

Using the "Basic" example (https://yomotsu.github.io/camera-controls/examples/basic.html) dragging on the scene rotates the view smoothly in Chrome (and Edge) both desktop and mobile, but doing the same in Firefox is choppy. It looks like the input keeps going on/off or is sampled at a very low rate. The framerate for all of my tests are 60+ fps so I'm not sure where this is coming from. The standard OrbitControls from Three.js perform smoothly.

Attached is an attempt at capturing the effect. You can see the right side jump a little as I drag (it's much more pronounced live). Left side is chrome and the right side is Firefox.
![orbit-controls-chrome-firefox_ps](https://user-images.githubusercontent.com/22778336/132286447-d4af1227-8fdf-4c66-8de0-3d8a6dbf0aaf.gif)

Outside of trying different demos and a simple example of my own, I also simplified the DOM (no overlapping DIVs, z-index, only block display types, etc.). No difference. 

A few questions:
1) is anyone else seeing something similar?
2) any thoughts on what may be causing this?

Thanks,

E.

**Comment by yomotsu** [comment]
Seems it works in both Firefox on Windows 10 and macOS for me.

https://user-images.githubusercontent.com/212837/132289587-a3a1adda-850e-485c-a175-a8115214ba67.mp4

**Comment by EricMaslowski** [comment]
Thanks for checking. I'll dig deeper into my systems then to see what might be causing this behavior. Thanks again.
