### ISSUE TITLE
Middle "WHELL" click

### ISSUE THREAD

**Issue by klich3** [yomotsu/camera-controls#212]
## Describe the bug
The problem is when I reassign whell listener to Truck, and press middle button "whell" and do move it to the side the camera control turn 90º deg to this side... and this actually is wrong.

Mouse whell has have two functions like a button and scroll. Maybe the correct way is determine what action is rewrited.
Scroll or Click + Drag.

## To Reproduce

1. Re-assign controls to truck
2. Click on mouse whell and move it to left side
3. The camera is rotate to 90º deg and is wrong

### Code

```js
this.instance.mouseButtons.left = CameraControls.ACTION.TRUCK;
this.instance.mouseButtons.wheel = CameraControls.ACTION.TRUCK;
this.instance.mouseButtons.right = CameraControls.ACTION.NONE;
this.instance.mouseButtons.shiftLeft = CameraControls.ACTION.NONE;
```

**for prevent or solve this you can set `THREE.MOUSE.MIDDLE = null;` on THREE** 

## Platform:

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]
 
Maybe others platforms... I can't tested

**Comment by yomotsu** [comment]
Did you check `this.instance.mouseButtons.middle`?

**Comment by klich3** [comment]
Yeah! Thanks its works!
I think it would be a good idea to comment on the documentation.
