### ISSUE TITLE
Frustrating, imprecise README/documentation

### ISSUE THREAD

**Issue by cyrusadkisson** [yomotsu/camera-controls#215]
**Is your feature request related to a problem? Please describe.**
The README is imprecise and hard to understand.

**Describe the solution you'd like**
A more precise README.

**Describe alternatives you've considered**
Alternative is to read the code itself and figure it all out on my own. This is sub-optimal, obviously.

**Additional context**

Examples:

1. The main "usage" example should have several comments explaining what each line does. Instead, it's just code.
2. The "properties" table should include information about the acceptable range of values. Is restThreshold 0-1? Or -inf to inf? It doesn't say.
3. The properties table should explain what each property does? What is boundaryFriction? I still don't know.
4. Methods: What is the difference between rotate and rotateTo? zoom and zoomTo? Doesn't say.
5. Methods: What are the acceptable values for each parameter? What do they do?
6. Methods: "interpolation factor" what is that?
7. No .then/.catch style examples

In general, I think more people would use this project if the README doc wasn't so confusing and hard to decipher. I'm on the verge of giving up what I was attempting myself, simply because I don't have time to trial-and-error and figure out what all these parameters do.

And this would be a shame because the project seems promising.

Side question: Is it possible to continually rotate? Or are all camera motions bound with a start+end?

**Comment by yomotsu** [comment]
Thanks for your suggestion.
I'll try to add more info.
Also, if you are interested, would you mind contributing to the project?
You could fill in the missing point of the readme.

> the project seems promising.

Thanks😊

> Side question

Please don't put extra subjects in one issue. Do you mind open another one for it?

**Comment by yomotsu** [comment]
Auto-generated doc with the table of contents has been added.
Closing the issue.
