### ISSUE TITLE
Feature request: continually rotating camera

### ISSUE THREAD

**Issue by cyrusadkisson** [yomotsu/camera-controls#216]
I'd like the camera to rotate around a single point continually. Is that even possible with this package? Seems like all camera motions are transitions from point A to point B and that a continuous movement won't work. Can you clarify?

**Comment by yomotsu** [comment]
increase `azimuthAngle` in your update loop.
```
cameraControls.azimuthAngle ++;
```

I've added  a new example for [auto-rotate](https://yomotsu.github.io/camera-controls/examples/auto-rotate.html).
