### ISSUE TITLE
Truck doesn't work

### ISSUE THREAD

**Issue by ketourneau** [yomotsu/camera-controls#218]
## Describe the bug
Truck (mouseButton right) doesn't work in 1.32.1.

## To Reproduce
Open https://yomotsu.github.io/camera-controls/examples/config.html
Try to truck

**Comment by yomotsu** [comment]
@ketourneau 

Thanks for your report.
It was just fixed with v1.32.2.

It's about time to have a unit test...

**Comment by flolu** [comment]
I was searching for the issue in my code for almost 1 hour :facepalm: 
Thanks for fixing it @yomotsu !

This can probably be closed?

**Comment by yomotsu** [comment]
Sorry for wasting your time🙇‍♂️ @flolu 

> This can probably be closed?

I think so. I'm closing this issue.
