### ISSUE TITLE
minDistance and maxDistance ignored in touch device when using TOUCH_DOLLY_OFFSET

### ISSUE THREAD

**Issue by sngazm** [yomotsu/camera-controls#219]
Thank you for creating great library. It's very useful for me. I found a problem that minDistance and maxDistance ignored in specific condition.

## Describe the bug

I wanted to fix orbit point and restrict dolly zoom distance and It's available by assigning `CameraControls.ACTION.OFFSET` to right drug and setting minDistance and maxDistance. But when it's controlled with touch device and two finger drug is assigned to `CameraControls.ACTION.TOUCH_DOLLY_OFFSET` min and max distance are ignored.

## To Reproduce
I made an example to reproduce the problem. 
https://camera-controls-test-sngazm.vercel.app/

When controlled with mouse device, minDistance and maxDistance setting works correctly, but when controlled with touch device (I tested in iPadOS Safari), two finger dolly moves ignoring both minDistance and maxDistance.

Is this intended behavior? And if there are any way to doing same restriction as mouse device, please tell me.

## Platform:

 - Device: Mobile
 - OS: iPadOS 14.7.1
 - Browser: Safari

**Comment by yomotsu** [comment]
Thanks for your report.
I confirmed the problem:

1. Open https://camera-controls-test-sngazm.vercel.app/ in iOS Safari
2. Set `minDistance` to `1` and `maxDistance` to `2`
3. Click "Two finger touch to DOLLY_OFFSET" button
4. pinch-in/out but `minDistance` and `maxDistance` is ignored

It's obviously unexpected behavior.
I'll take a look later.

**Comment by yomotsu** [comment]
Investigated:
I guess `TOUCH_DOLLY_OFFSET ` is missing here...
https://github.com/yomotsu/camera-controls/blob/7e1311fd1e8b8e2a4a0bb329192bc4e1daf95209/src/CameraControls.ts#L725-L728)

**Comment by yomotsu** [comment]
I think it was fixed by #220 and v1.32.3 will be published.

**Comment by yomotsu** [comment]
@sngazm 
Good to hear that👍

なんと...! ありがとうございます。
ポッドキャストが不慣れだったので辿たどしい話になってしまったのですが、お聞きいただけて嬉しいです😊
