### ISSUE TITLE
Different behavior on wheel events with control key down.

### ISSUE THREAD

**Issue by milesflux** [yomotsu/camera-controls#222]
I'd like to have the option of different behavior on wheel events depending on whether the control key is down or not. Basically what I'd like is to have a wheel event without the control key down control panning and a wheel event with the control key down control zoom/dolly. The reason this is desirable is most trackpads will send a wheel event with ctrl down when the user does a pinch to zoom gesture so it would be useful to have two different events in this case.

I'd be happy to put together a PR for this if this seems like a reasonable addition.

**Comment by yomotsu** [comment]
Hi @milesflux,
Thanks for your suggestion.
That makes sense. I think it's okay to add.

We have already merged a similar PR https://github.com/yomotsu/camera-controls/pull/196
This would be kind of a reference.

**Comment by milesflux** [comment]
Great I will take a look at that and put together a PR.

**Comment by yomotsu** [comment]
Closing the issue.
Now, key combination can be done in user land.
See the example for more details.
https://yomotsu.github.io/camera-controls/examples/mouse-drag-with-modifier-keys.html
