### ISSUE TITLE
Option to disable transitions.

### ISSUE THREAD

**Issue by milesflux** [yomotsu/camera-controls#224]
We'd like to have a flag to disable all automatic transitions. Right now most of the commands like truck/dolly/rotate take an `enableTransition` flag but some of the internal transitions default this to true. We'd like to have a new option to customize this behavior.

Does this seem reasonable? If so I can put together a PR.

**Comment by yomotsu** [comment]
Thanks for your suggestion, however, I think that must be done in the userland.

e.g.
```js
const state = {
  enableTransition: true,
};

cameraControls.rotate( Math.PI / 2, 0, state.enableTransition );
cameraControls.dolly( 3, state.enableTransition );
```

**Comment by yomotsu** [comment]
Sorry, I found it

https://github.com/yomotsu/camera-controls/blob/b1a7fb448510f572a2cdbe64f0aa607b8fc9362d/src/CameraControls.ts#L1987

I think you can set high `dampingFactor` and `draggingDampingFactor` to disable transition

**Comment by milesflux** [comment]
> I think you can set high `dampingFactor` and `draggingDampingFactor` to disable all smooth transitions

Thanks for the suggestion I will try that first.

**Comment by yomotsu** [comment]
Oops...actually, I just found a problem with `dampingFactor`.
If `dampingFactor` is `1`, the controls should disable smooth transitions...but there is a probrem in `update()`.

I will fix it within this week.

**Comment by milesflux** [comment]
Thanks very much and thanks for your quick response!

**Comment by yomotsu** [comment]
@milesflux 

The problem I found is fixed with https://github.com/yomotsu/camera-controls/commit/829e81ef583b73d51da380708c8d8b7a86d07032

I will publish the new version with the fix this weekend.
(But if you are in a hurry, feel free to let me know.)

After that, set `cameraControls.draggingDampingFactor = 1` to disable user dragging smooth transitions.

**Comment by yomotsu** [comment]
@milesflux
The fix has been published to NPM.
Could you try `cameraControls.draggingDampingFactor = 1` with the newest version?

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
