### ISSUE TITLE
Breaking change since v1.29.0

### ISSUE THREAD

**Issue by Sim3d** [yomotsu/camera-controls#225]
I Yomotsu!

I try to update the CameraControls libray from v1.28.4 to v1.33.0 on my project and I realized that I'm not receiving the 'originalEvent: event' from the CameraControlsEvent 'control' anymore. 

I need these original MouseEvent and WheelEvent in my Navigation logics to do some tasks on 'control' event, so for now, I cannot update the library.

Any particular reason why your decided to stop dispatching these original events?

this.dispatchEvent( {
	type: 'control',
	originalEvent: event,
} );

Can you please giving back this event to your dispatch call?

FYI, the changes comes from this Pull Request: https://github.com/yomotsu/camera-controls/pull/197

By the ways, Thanks for this great camera controls library! :)

**Comment by yomotsu** [comment]
Sorry for the change and thanks for using the lib.
I didn't think orgialEvents are used...(also it was undocumented)

We could reprvode the original events, however as you pointed, the events to listen has been changed to PointerEvents and are slightly different from MouseEvents.

Could I hear about your use case?
There may be another solution...?

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
