### ISSUE TITLE
Eradic camera movement on heavy scenes on 1.33

### ISSUE THREAD

**Issue by diredev** [yomotsu/camera-controls#227]
## Describe the bug
In our application we're displaying medium to large-ish scenes where most of the model need to be transparent. This, depending on the model used, results in bad performance on some machines (which in itself is a problem but not the point of this ticket).

Since the update to camera-controls 1.33.0 we're experiencing weird camera jumps on drag or pan on these larger scenes. The effect becomes stronger the more taxing the scene becomes and also seems to be influenced by `dampingFactor` and `draggingDampingFactor`.

This does not occur on 1.32.3, using the exact same scenarios and models.

## To Reproduce
The following fiddle should demonstrate the behavior: https://jsfiddle.net/s24frk3j/ (warning: a whole lot of cubes). 

Load the fiddle and try to rotate or pan the camera. If the effect isn't obvious, try to increase the number of objects further.

## Expected behavior
Should behave like 1.32.3 if possible.

## Platform:

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge

**Comment by yomotsu** [comment]
Thanks for your report, and sorry for the breaking-fix.
Actually, both 1.32.3 and  1.33.0 are unexpected behavior...

If you need to keep a smooth movement regardless of CPU load (FPS), set fixed delta: `cameraControls.update( 0.016 );` which means "assuming 60 FPS".
Or maybe `cameraControls.update( Math.min( 0.032, delta ) );`

Currently, too long delta time by heavy CPU load causes a bug as you reported and I will fix that soon.
(the delta time affects the interpolation factor, and if the delta is too long, interpolation may be over `1` and causes the bouncing-ish effect.)

**Comment by diredev** [comment]
Thank you for the quick fix, works like a charm now 👍 

In the end I went with just keeping the current update-logic (`update(deltaTime)`). I tried your suggestions but the normal one had the most "natural" feel to it, with the camera movement being as laggy as the rendering itself, I guess 😅
