### ISSUE TITLE
Smooth dolly on notched mouse wheels

### ISSUE THREAD

**Issue by samuelhorn** [yomotsu/camera-controls#230]
### Is your feature request related to a problem? Please describe.

I have created a scene where `cameraControls.mouseButtons.wheel = CameraControls.ACTION.DOLLY`, I also have the setting `cameraControls.dollyToCursor = true`. This enables me to dolly in to where ever I have my cursor, and it works great on trackpads and apple magic mouse. As soon a I test o a PC with a notch mouse wheel the dolly gets super choppy.

### Describe the solution you'd like

If it would be possible to add a setting like `cameraControls.smoothDolly = true`, that somehow smooths notch wheels internally, that would be awesome!

### Describe alternatives you've considered

This can be resolved by adding the setting `cameraControls.mouseButtons.wheel = CameraControls.ACTION.NONE`, and instead add an event listener to the wheel event, and in that listener run something like `cameraControls.dolly(-wheel.deltaY * 10, true)`. Then the dolly becomes smooth, but obviously the dollyToCursor no longer have any effect.

**Comment by yomotsu** [comment]
Thank you for using and your suggestion!

Actually, I think it depends on the granularity of the mouse wheel. I'm not sure this should be controlled in the lib or not...
In fact, the original OrbitControls of three.js does not handle the wheel smoothness.
Therefore, I would like to do the same as the original.

However, ours is more flexible (I think).
You can extend the `CameraControls` and change `_dollyInternal()`, to make it smooth.
Pass `true` to the second argument of `this.dollyTo( distance );` in the methods.

https://github.com/yomotsu/camera-controls/blob/22e2b6a09e8b48bcad9f5dcc79b93ef57e54b5aa/src/CameraControls.ts#L2182-L2215

Does this sound good to you...?

**Comment by samuelhorn** [comment]
Thank you for responding!

Yeah, I have already altered it like this, problem is this makes `dollyToCursor` stop working: 

```
...
zoomCamera(wheel) {
    this.controls.dolly(-wheel.deltaY * 10, true)
},
...
```

Would you have the time to elaborate how i could extend `_dollyInternal()`?

**Comment by yomotsu** [comment]
Sorry, I don't get the point of "choppy while zooming"...

Anyway, I think you can check https://github.com/yomotsu/camera-controls/issues/187
(I meant extending of TS(or ES) class)

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
