### ISSUE TITLE
Zooming should trigger re-rendering of scene

### ISSUE THREAD

**Issue by Accelyte** [yomotsu/camera-controls#232]
## Describe the bug
controls.update(delta) does not return "true" on scrolling zoom action. This causes the view to freeze when trying to zoom, unless the camera perspective is also changing.

## Code (copied from example)
```
function animate() {
    // update controls
    const delta = clock.getDelta();
    const hasControlsUpdated = controls.update(delta);

    requestAnimationFrame(animate);

    // avoid unnecessary renders
    if (controls.update(delta)) render();

    stats.update();
}
```

## Expected behavior
Zooming (scrolling) should trigger re-rendering without requiring camera perspective change (cursor dragging).

**Comment by yomotsu** [comment]
Thank you for your report!
That must be fixed.

I'll take a look later today.

**Comment by yomotsu** [comment]
I tried the following but seems to work.

1. set mouse action
```
cameraControls.mouseButtons.wheel=CameraControls.ACTION.ZOOM;
```

2. then wheel scroll.
3. the screen was updated.

How do you reproduce the problem?

**Comment by Accelyte** [comment]
Hmm, I came back to my project a couple days later and it seems to be working now. I'm not sure what fixed it, but I'll close this issue for now (until it comes up again, then I'll provide a demo...)
