### ISSUE TITLE
Add Table of Contents for Methods in readme.md

### ISSUE THREAD

**Issue by gbroques** [yomotsu/camera-controls#233]
**Is your feature request related to a problem? Please describe.**
It could be quicker to find relevant methods, or see all methods avaliable at a glance with a Table of Contents in the **Methods** section of the README.

**Describe the solution you'd like**
Add a bulleted list of links for each method, that when clicked, take you to the corresponding section.

**Describe alternatives you've considered**
I haven't considered alternatives, but I'm open to other ideas.

**Additional context**
See an example of a Table of Contents in Markdown [here](https://github.com/gbroques/ose-workbench-platform).

Additionally, I've included an "Example" below.

*Thoughts on whether a PR for this would be welcomed?*

# Example

## Methods

* [rotate( azimuthAngle, polarAngle, enableTransition )](#rotate-azimuthangle-polarangle-enabletransition-)
* [rotateAzimuthTo( azimuthAngle, enableTransition )](#rotateazimuthto-azimuthangle-enabletransition-)
* [rotatePolarTo( polarAngle, enableTransition )](#rotatepolarto-polarangle-enabletransition-)
* ... (**TODO:** add all methods)

#### `rotate( azimuthAngle, polarAngle, enableTransition )`

Rotate azimuthal angle(horizontal) and polar angle(vertical).
Every value is added to the current value.

| Name               | Type      | Description |
| ------------------ | --------- | ----------- |
| `azimuthAngle`     | `number`  | Azimuth rotate angle. In radian. |
| `polarAngle`       | `number`  | Polar rotate angle. In radian. |
| `enableTransition` | `boolean` | Whether to move smoothly or immediately |

If you want to rotate only one axis, put a angle for the axis to rotate, and `0` for another.
``` js
rotate( 20 * THREE.MathUtils.DEG2RAD, 0, true );
```

---

#### `rotateAzimuthTo( azimuthAngle, enableTransition )`

Rotate azimuthal angle(horizontal) to the given angle and keep the same polar angle(vertical) target.

| Name               | Type      | Description |
| ------------------ | --------- | ----------- |
| `azimuthAngle`     | `number`  | Azimuth rotate angle. In radian. |
| `enableTransition` | `boolean` | Whether to move smoothly or immediately |

---

#### `rotatePolarTo( polarAngle, enableTransition )`

Rotate polar angle(vertical) to the given angle and keep the same azimuthal angle(horizontal) target.

| Name               | Type      | Description |
| ------------------ | --------- | ----------- |
| `polarAngle`       | `number`  | Polar rotate angle. In radian. |
| `enableTransition` | `boolean` | Whether to move smoothly or immediately |

---

... (**TODO:** add all methods)

**Comment by yomotsu** [comment]
Thanks for your suggestion.
Maybe we should prepare an auto-generated doc with [webdoc](https://github.com/webdoc-labs/webdoc) or othres

**Comment by gbroques** [comment]
> Thanks for your suggestion. Maybe we should prepare an auto-generated doc with [webdoc](https://github.com/webdoc-labs/webdoc) or othres

That could work!

The [example they linked to](https://webdoc-labs.github.io/example-documentation/index.html) looks nice! :smile: 

---

As an aside, I wanted to mention how nice `CameraControls` are compared to `THREE.OrbitControls`.

It really helped me on the project I'm working!

**Comment by looeee** [comment]
This is  a great idea, I keep finding myself scrolling up and down through the readme. 
Can we add a TOC for the entire file at the top? 

I've used this extension before, it's quick and easy if you use VSCode. 

https://marketplace.visualstudio.com/items?itemName=huntertran.auto-markdown-toc

**Comment by yomotsu** [comment]
Here is the new [auto-generated documentation](https://camera-controls.pages.dev/classes/CameraControls) (with TOC).

**Comment by yomotsu** [comment]
I think this issue has been solved with https://github.com/yomotsu/camera-controls/issues/233#issuecomment-1110320158.
Close this issue.
