### ISSUE TITLE
Add a toggle to enable/disable user input

### ISSUE THREAD

**Issue by looeee** [yomotsu/camera-controls#235]
I'm trying to set up this:

1. Camera in position `Ap` looking at target `At`.
2. Transition camera to new view, position `Bp` looking at target `Bt`. 

I can use `controls.setLookAt` for this

``` js
await controls.setLookAt(Bp.x, Bp.y, Bp.z, Bt.x, Bt.y, Bt.z, true);
```

This will smoothly animate to the new view, however, the problem is if the user interacts with the controls during the transition, it will overwrite the final destination and the camera will end up at some unknown place. 

To prevent this I need to be able to disable interaction temporarily while keeping the controls enabled. Currently I can do that by going through all the inputs and setting them to NONE:

``` js
controls.mouseButtons.left = CameraControls.ACTION.NONE;
controls.mouseButtons.right = CameraControls.ACTION.NONE;
controls.mouseButtons.middle= CameraControls.ACTION.NONE;
// ... etc
```

And then once the transition has completed I need to re-enable everything. This is fairly tedious. Would it possible to add a new flag, say, `controls.inputEnabed = true/false`?

**Comment by yomotsu** [comment]
Happy holiday!

That's a good point.
You mean, `controls.inputEnabed` can enable/disable all user input via mouth and touch, right?
I think it would be worth having.

**Comment by looeee** [comment]
Happy holidays to you too 😁 

> You mean, controls.inputEnabed can enable/disable all user input via mouth and touch, but not for other methods, right?

Yeah exactly, so that you can control the camera in code and not have it disrupted by the user.

**Comment by yomotsu** [comment]
Sorry for the delay.
I just realized, `CameraControls` already has [`enabled` property](https://github.com/yomotsu/camera-controls#properties) to control user-input, just [like the official `OrbitControls`](https://threejs.org/docs/#examples/en/controls/OrbitControls.enabled).

Is that what we need?

**Comment by looeee** [comment]
Hmm, I thought the enabled flag was making all methods like `setTarget` etc. stop working working as well (at least in my app it seemed to do that), but I checked the code and it seems like it shouldn't - it should only disable user input right? 🤔 If so that's exactly what I want.

Maybe there was something else going wrong in my app - I'll be back from vacation in a couple of days so I'll check again then.

**Comment by yomotsu** [comment]
> it should only disable user input right?

I think so, too. But let me know if my understanding is wrong.
Anyway, enjoy your vacation☃️

**Comment by looeee** [comment]
OK, I worked out what I was doing wrong and it's really dumb 😅 

I had copied over code from an OrbitControls example and it was doing this:

``` js
if(controls.enabled) controls.update(delta);
```

🙄

**Comment by yomotsu** [comment]
Good to hear that!
Thanks for your report anyway.
