### ISSUE TITLE
Can I add an example of using camera-controls in react-three-fiber?

### ISSUE THREAD

**Issue by moshuying** [yomotsu/camera-controls#238]
I like to use the `react-three-fiber` to write code, but ` camera - controls ` doesn't seem to have very good support this, after some attempts, I realized this.
And it can work well, I just finished the basic content, all of the events and properties control, and not included in it.

**Comment by yomotsu** [comment]
That would be really appreciated!

**Comment by moshuying** [comment]
> That would be really appreciated!
> 
> Some ppl use `camera-controls` with `react-three-fiber` such as #203, and your example could help them.

Thank you for your reminder. I met someone who also encountered this problem there. Where did I submit the sample code I made, which may help him.

**Comment by yomotsu** [comment]
react-three-fiber example has been added.
https://codesandbox.io/s/react-three-fiber-camera-controls-4jjor?file=/src/App.tsx

Closing this issue.
Thanks for your request, @moshuying !
