### ISSUE TITLE
Strange behavior of dolly to cursor zoom out

### ISSUE THREAD

**Issue by fukuken1968** [yomotsu/camera-controls#239]
## Describe the bug
see the attached screenshot

## To Reproduce

1. check 'dolly to cursor'
2. rotate the mouse wheel (repeat increasing and decreasing)
3. drawing disappears at a certain timing

### Live example
https://yomotsu.github.io/camera-controls/examples/orthographic.html

## Expected behavior
Do not disappear even if zoom out in dolly to cursor mode.

## Screenshots or Video
[
](https://user-images.githubusercontent.com/98252738/150668877-f30e8c2c-fd1a-4e54-b92b-6252e417ccc6.mp4
)
## Platform:

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]

**Comment by yomotsu** [comment]
Thanks for your report.
Reproduced. It seems only happens if the camera is facing every 90deg (front, side, and so on)

**Comment by blksky** [comment]
I have the same problem.

**Comment by msemtd** [comment]
I assume that the camera position is moving and the camera far frustum is clipping the scene.

**Comment by yomotsu** [comment]
I guess the cause of the problem is here:
https://github.com/yomotsu/camera-controls/blob/c35908d208fe0d695ec7d9aa5de8ee247dc3b611/src/CameraControls.ts#L2240-L2241

We should re-consider the zoom-to-cursor (*not dolly*) in orthographic calculation...

**Comment by blksky** [comment]
Is there a solution?

**Comment by yomotsu** [comment]
Unfortunately, this is quite complex. Actually, zoom-to-cursor **in orthographic** behaves as  _dolly_, as a result, the camera moves out of the clipping plane. Users should not use zoom-to-cursor in orthographic😢
OrthographicCamera must not dolly and should use zoom instead correctly.

**Comment by yomotsu** [comment]
I think this problem has finally been fixed at https://github.com/yomotsu/camera-controls/pull/322
