### ISSUE TITLE
Recommendation for azimuth restricted by polar angle?

### ISSUE THREAD

**Issue by alexpineda** [yomotsu/camera-controls#243]
I'm making an RTS camera, and if the camera is a low angle I'd like the viewer to be able to rotate/left right almost 180 degrees (so they can get immersed in all the action), however if they are looking more top down I'd like to taper the azimuth limit, almost like a bell curve relationship. Any suggestions on doing this while supporting all the smooth transitions?

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
However, I think your question seems your app oriented question.
I hope you could figure it out by yourself.

If you find an unexpected bug, I will help with it!
