### ISSUE TITLE
using controls with on demand rendering

### ISSUE THREAD

**Issue by ashleymvanduzer** [yomotsu/camera-controls#249]
First off, thanks for building such a great tool! It's really something special.
I have come across an issue when using controls with on demand rendering with complex transitions (async await), being:

If the first method call being awaited has no movement, the promise will resolve immediately, stopping the following method calls from finishing. For example, if the zoomTo position between point a and b is the same, but the rotation is different, the zoom will resolve first and won't allow the rotation to finish. This isn't a problem when leaving the render loop active always. 

Any ideas on why this might be happening or how to work around this?

**Comment by yomotsu** [comment]
Hi Ashleymvanduzer, Thanks for your report.
I got your point.
Seems this line in zoomTo causes the problem.
https://github.com/yomotsu/camera-controls/blob/07fc3c2c8ebae2816a56a80e1cbc2f6892d20a58/src/CameraControls.ts#L1144-L1145

However, another method (such as `rotateTo`) should be continued and resolved after that, right?
Because `zoomTo` and `rotateTo` returns another Promise object.

**Comment by ashleymvanduzer** [comment]
Thank you for getting back to me! It does seem like that is the problem, thanks for pointing that out, the context is very helpful. 
Addressing your follow up question:
However, another method (such as rotateTo) should be continued and resolved after that, right?
Because zoomTo and rotateTo returns another Promise object. 
-- Right. I should have given you a little more context in terms of how I am using this, sorry about that. So, I am using the promises to know when the animations have finished, in order to tell some other code to take a screenshot at the correct time, by making use of await, then calling a callback. I am using react three fiber by the way.

Here's a little code snippet:
```
  async function animateCamera(state: any) {
    await controls.rotateTo(...cameraViewOptions[viewIndex].rotateTo as [number, number, boolean]);
    if (viewIndex < 21) {
      await controls.zoomTo(...cameraViewOptions[viewIndex].zoomTo as [number, boolean]);
    }
    
    setIsAnimating(false);
    if (callbackExecuted) return false;
    renderCallback && renderCallback(state);
    callbackExecuted = true;
  }

  useFrame((state, delta) => {
    if (isAnimating) {
      animateCamera(state) && invalidate();
    }
    controls.update(delta);
  });

```

**Comment by yomotsu** [comment]
Don't apologize, Thanks for the code!
I saw your code, but seems like, the Resolves happen one by one, doesn't it?
I mean, `rotateTo` will resolve first, after that, `zoomTo` starts and resolves (altho it may resolve immediately), then, finally the following `setIsAnimating` and others will be executed, am I correct...?

**Comment by ashleymvanduzer** [comment]
Thanks for taking a look!  Yep, you are correct, and that is exactly what I am looking to achieve.

**Comment by ashleymvanduzer** [comment]
@yomotsu just wanted to let you know, the problem was with trying to lerp with on demand rendering. I'm not sure how to do that but I figured it all out with react-spring and camera-controls is now working like a charm. Thanks again for all your help!

**Comment by yomotsu** [comment]
Good to hear that!
Let me close this then👍
