### ISSUE TITLE
Perspective camera with position(0,0,0) camera movement not working

### ISSUE THREAD

**Issue by zadinvit** [yomotsu/camera-controls#250]
## Describe the bug
I create the perspective camera and I add it to CameraControls constructor but the camera movement not working. Move to function work. But I can't pan or zoom. 
After I set the Camera to another value etc.(0,0,5) controls start working.

## To Reproduce

1. Go to createCamera with position (0,0,0)
2. Click on construct CameraControls with this camera
3. See error

### Code

```js
   camera.position.set(0, 0, 0);
   const cameraControls = new CameraControls(camera, renderer.domElement)

```

## Expected behavior

I spend a lot of time debugging code, try to fix it. I expect that controls will work with the camera in (0,0,0) position.
## Platform:

 - Device: Desktop
 - OS:  MacOS
 - Browser: Chrome

**Comment by yomotsu** [comment]
Thank you for using CameraControls.
Unfortunately, CameraControls doesn't work correctly if no distance between the camera and the center.
CameraControls uses the distance internally.

Therefore, the position of the camera has to be slightly away from the center or move the center with `setTarget()` method.
Did that make sense to you?

Maybe CameraControls should show a warning for this situation.

**Comment by zadinvit** [comment]
Hi, 
it makes sense. Warning help a lot. I spend a lot of time on this, and some warning could help me fix this quickly. 

Maybe changing some default values which are now by default set to zero, but have conditions be greater than zero could help too.
