### ISSUE TITLE
Prevent the camera from penetrating & seeing through objects

### ISSUE THREAD

**Issue by h4k1m0u** [yomotsu/camera-controls#254]
**Is your feature request related to a problem? Please describe.**
I know that [examples/boundary](https://yomotsu.github.io/camera-controls/examples/boundary.html) implements an external boundary preventing the camera from going outside that box, but I was wondering if it's already possible to instead prevent the camera from going inside objects (e.g. a box).

**Describe the solution you'd like**
Ideally, the camera should stop moving once it's too close to the meshes either after a zoom/dolly, a pan, or an orbit.

**Describe alternatives you've considered**
- Setting `minDistance` won't work if I get too close to the objects I don't want to see through, then orbit the camera.
-  [examples/collision](https://yomotsu.github.io/camera-controls/examples/collision.html) isn't exactly what I'm looking for.

Apologies in advance if this functionality has already been implemented, as I cannot find any mention of it in the issues or among `CameraControls` properties.

**Comment by yomotsu** [comment]
I think what you are looking for is a physics engine.
(like our [TPS example](https://yomotsu.github.io/meshwalk/example/5_terrain.html))
If so that is out of range of the features.

You need a collision implementation with physics libs, such as Cannon.js.

**Comment by h4k1m0u** [comment]
Thanks for getting back quickly.
But is there a way to know the new position of the camera before calling `controls.update()`, to decide whether to render from the new position or not (if too close to an object)?
I think this problem would still persist if I use a physics engine, right?

**Comment by yomotsu** [comment]
Unfortunately, there is no way to do so.
If you wish, extend the `CameraControls` class and modify `update()` method to achieve the position.

**Comment by h4k1m0u** [comment]
I understand, thanks again for your answers (and for this awesome plugin).

**Comment by h4k1m0u** [comment]
It turned out using `saveState()` and `reset(true)` accomplished exactly what I was looking for.

**Comment by OstapTelychko** [comment]
Is it really imposible to detect if camera tries to penetrate object. In collision test method raycaser send ray from origin to camera target (next mouse position). In theory to invert classis collision behaviour we need to send ray from camera position to target. But I did't managed to do that. I've been trying to replace origin with camera position, replacing target with camera positon, inerting direction but nothig works
