### ISSUE TITLE
Multiple controls with each own camera

### ISSUE THREAD

**Issue by Lyror** [yomotsu/camera-controls#256]
## Describe the bug
In my usecase I would like to use different cameras (OrthographicCamera, PerspectiveCamera) each with their own camera control. Each camera should be controllable via its own control. There is only one camera at a time in the scene. 
I just had to make it quite clumsy using two instances with one orthographic and one perspective camera. Unfortunately, after changing the camera from orthographic to perspective, it is no longer movable. I set orthographic instance to enabled = false and removed the camera from the scene and added the other to the scene. Unfortunately this did not work. Is it at all possible to create multiple instances, each with its own camera? 

## Platform:

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Comment by yomotsu** [comment]
Do you mind sharing a demo to reproduce the problem?

**Comment by Lyror** [comment]
I looked again into my code after weekend and found out that the lib works fine and I had a bug.
