### ISSUE TITLE
Object at center rotates around y-axis instead of z-axis

### ISSUE THREAD

**Issue by RobWi01** [yomotsu/camera-controls#260]
Hi sir,

I use your CameraControls library for controlling 3D images (STL files) when my 3D object is at his center, it rotates around his y-axis instead of his z-axis. Is there a way or an option to fix this?

I have attached my STLviewer code below.

Kind regards,
Rob
[PenO_Relu-master (4).zip](https://github.com/yomotsu/camera-controls/files/8564462/PenO_Relu-master.4.zip)

**Comment by yomotsu** [comment]
I think it's your application problem. Please check the examples and the documentation.
