### ISSUE TITLE
setOrbitPoint on camera position causes camera movement

### ISSUE THREAD

**Issue by Lyror** [yomotsu/camera-controls#261]
## Describe the bug
If you set the orbit point to the same position as the camera it will causes the camera to move a little back. The question why I am doing this is that I want a first person feel when rotating the camera.

### Live example

https://jsfiddle.net/Lyror/oswguhmn/48/

If you right click you will see that the camera will be moved because on every right click the orbit point will be set.

## Expected behavior
OrbitPoint should be set without moving the camera.

**Comment by Lyror** [comment]
`minDistance` must be greater then zero so I have no option. Sure I could use a value near zero but that not a solution.

In my special case here when you remove the line in setOrbitPoint `this.moveTo( targetX, targetY, targetZ, false );` it works as expected.

Yes I need to be able to rotate arround the camera itself like in a first person game.

**Comment by yomotsu** [comment]
So, can you use simply `moveTo` instead?

`setOrbitPoint` is **to change `target` and `offset` at the same time but keep the same position**. that means, what you are doing in your code is:

1: set `target` position which is orbit center to camera-position via `setOrbitPoint`
2: but camera-position will be moved due to `minDistance`, because you are setting target to camera-position.
3: the target is now previous camera-position, and current camera-position is` minDistance` away from the `target`

**Comment by Lyror** [comment]
Thank you for the first-person example. The problem with the first-person example is that it works fine as long as you don't move with the left mouse button  (pan mode). I have modified the example (https://jsfiddle.net/Lyror/hLosj1b7/4/) and commented out the mouse-down event, now when you move and left-click you no longer rotate around yourself. 

I understand that setOrbitPoint works as it should and it makes sense of course. Is there no solution for my case where you are no longer in the center and want to rotate around yourself?

**Comment by yomotsu** [comment]
Sorry but unfortunately, I can't answer every application-specific question.
Please understand that this is not a well-sponsored project nor a contract work.

There is the documentation for all methods that the lib provides:
https://github.com/yomotsu/camera-controls#methods
I hope this will help to figure it out.

**Comment by Lyror** [comment]
Okay understandable. Thank you very much for your help.
