### ISSUE TITLE
React Three Fiber integration

### ISSUE THREAD

**Issue by marcelpi** [yomotsu/camera-controls#262]
**Is your feature request related to a problem? Please describe.**
Please make this library easy to use in React Three Fiber. That would be a major time-saver as a lot of people are using R3F nowadays and there are a lot of projects developed in React.

**Describe the solution you'd like**
A component one can import and use right away, like <OrbitControls />.

I tried using it in R3F using the example you provided, but didn't manage to get it going.
Still, I would love to use it.

**Comment by DennisSmolek** [comment]
> 

So here's Pauls (creator of r3f) simple wrapper using the r3f `extend` https://codesandbox.io/s/yomotsu-camera-controls-febus

After that is on you to make it work for your project. 
I'm surprised though because the wrapper they used is fairly solid too, if a bit more verbose..

What are you trying to do that you couldnt?

**Comment by marcelpi** [comment]
> > 
> 
> So here's Pauls (creator of r3f) simple wrapper using the r3f `extend` https://codesandbox.io/s/yomotsu-camera-controls-febus
> 
> After that is on you to make it work for your project. I'm surprised though because the wrapper they used is fairly solid too, if a bit more verbose..
> 
> What are you trying to do that you couldnt?
> 
> I'm ALSO writing a r3f variant...

I managed to get it to work. I was suggesting it would be nice to have this wrapper included in the library by default, instead of having to set it up. I'm not an expert in Three and React, quite contrary, so I'm having a difficult time trying to wrap my hand around this stuff and how it works.

If I could just import a component and add it to my scene out of the box, like OrbitControls, that would be awesome.

Anyway, thanks again for your feedback.

**Comment by marcelpi** [comment]
Alright, then a .jsx version would be fine. I would use that one instead of .tsx.
I understand the part about dependencies, if it's too much overhead then skip it for now.

In the future I think more and more people will migrate towards r3f though since it's so much easier to use compared to vanilla Three.

But I also understand it's a lot of work for just one person.
Thank you again for your hard work, pulling something like this off must've been really hard.

**Comment by DennisSmolek** [comment]
> First of all, I'm happy to see this conversation. Thank you for your suggestions again. I think I should prepare a jsx version(not tsx) example of it. Also, I could add some usage of that for r3f users.
> 
> If we provide r3f ready camera-controls in this repository, we also need to add additional dependencies which are React and r3f. but I think that is too much. So, I would make another repository, but I'm not sure that I could keep it updated.
> 
> I personally encourage you to use our example https://codesandbox.io/s/react-three-fiber-camera-controls-4jjor?file=/src/camera-controls.tsx over https://codesandbox.io/s/yomotsu-camera-controls-febus
> 
> Because ours can use more instance methods via the Ref!

Can you clarify this point?

I saw the instance mentioned in your wrapper but Im not sure when you would be utilizing it.

Pauls version is very basic but also has the ref exposed so I believe most generic methods would work

**Comment by yomotsu** [comment]
@marcelpi Thanks for understanding. 

@DennisSmolek 
My wrapper component exposes Ref with forwardRef. So, you can call methods from out of `<Canvas>`.

As you can see there are `<button>`s to call camera-controls methods in my App.tsx.
I think mine is more controllable.

**Comment by yomotsu** [comment]
@marcelpi 
jsx version is available here
https://codesandbox.io/s/react-three-fiber-camera-controls-forked-6hclkb

**Comment by marcelpi** [comment]
> @marcelpi jsx version is available here https://codesandbox.io/s/react-three-fiber-camera-controls-forked-6hclkb

Thank you!

**Comment by abernier** [comment]
I have mimicked the implementation of [drei](https://github.com/pmndrs/drei#controls)'s [`OrbitControls`](https://github.com/pmndrs/drei/blob/master/src/core/OrbitControls.tsx) into that `CameraControls` (TS) impl: https://codesandbox.io/s/yomotsu-camera-controls-forked-ts-version-forked-vbgq3p?file=/src/CameraControls.tsx

It support:
- passing `ref`
- passing a custom `camera` prop
- passing a custom `domElement` prop
- calling `.dispose()` when unmounting
- only `.update()`ing when `.enabled`

**Comment by abernier** [comment]
> If we provide r3f ready camera-controls in this repository, we also need to add additional dependencies which are React and r3f. but I think that is too much. So, I would make another repository, but I'm not sure that I could keep it updated.

@yomotsu what about defining r3f dep as an **optional peer dependency**, ie:
```json
{
  "peerDependencies": { 
    "@react-three/fiber": "^7.26.0 || ^8.10.0"
  },
  "peerDependenciesMeta": {
    "@react-three/fiber": {
      "optional": true
    }
  }
}
```

From what I've understood https://github.com/npm/rfcs/issues/221, optional-peer-deps are not automatically installed, so a user `npm i camera-controls` who doesn't use r3f in his project should not be affected.

On the other side, a user using r3f could then enjoy the `<CameraControls>` component:

```tsx
import CameraControls from "camera-controls/r3f"

function App() {
  return <CameraControls />;
}
```

**Comment by CodyJasonBennett** [comment]
No need, this is why we have Drei. Happy to continue in https://github.com/pmndrs/drei/pull/1237.

**Comment by abernier** [comment]
`<CameraControls>` component is now live in `@react-three/drei` (v9.54.0)

**Comment by yomotsu** [comment]
@abernier @CodyJasonBennett That's big news for me! Thank you very much!!
I was always wondering if someone could take responsibility for r3f-ready camera-controls, because I'm not confident using r3f.

Now it's sort of official! Really appreciate it.
I will also add "for r3f users section" in our readme when drei v9.54.0 is shipped.

**Comment by abernier** [comment]
Thank you @yomotsu it'a nice to see your enthusiasm :)

After the release, @drcmda one of the author of r3f, pointed me out a small issue though...

In react, in dev mode (aka [strict-mode](https://reactjs.org/docs/strict-mode.html)) a component can be [rendered twice](https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode).

As a consequence, it is important we can disconnect and re-connect all events, once the component is re-rendered. In other words, it is particularly important the CameraControls class's constructor does not has side-effects (like binding events).

I think we could quite easily create a dedicated `.connect` method and move any events binding into it.

We could then have the following flow in React:

```
new CameraControls()
.connect()
.disconnect()
.connect()
.disconnect()
...
```

I will try submitting a PR for this ;)

**Comment by drcmda** [comment]
@yomotsu so happy to see you like it, i hope it will drive more users to this amazing library.

btw here's how we handle the constructor side effect issue with all other controls:

```jsx
class OrbitControls extends EventDispatcher {
  domElement: HTMLElement | undefined
  constructor(object: Camera, domElement?: HTMLElement) {
    this.connect = (domElement: HTMLElement): void => {
      scope.domElement = domElement
      scope.domElement.style.touchAction = 'none'
      scope.domElement.addEventListener('contextmenu', onContextMenu)
      ...
    }
    this.dispose = (): void => {
      scope.domElement?.removeEventListener('contextmenu', onContextMenu)
      scope.domElement?.removeEventListener('pointerdown', onPointerDown)
      ...
    }
    // connect events
    if (domElement !== undefined) this.connect(domElement)
```

it's entirely optional and backward compatible.

this standard way:

```jsx
const ctrl = new Controls(cam, domNode)
```

and optionally

```jsx
const ctrl = new Controls(cam)
ctrl.connect(domNode)
// later ...
ctrl.dispose()
```

this allows us to connect and re-connect to dom layers, but also takes care of this issue: https://github.com/mrdoob/three.js/issues/20575

**Comment by abernier** [comment]
Here is my try with a new `.connect` method @yomotsu https://github.com/yomotsu/camera-controls/pull/338 :)

**Comment by yomotsu** [comment]
@abernier @drcmda Thank you for pointing it out, and suggestions. (now it's ongoing!)

**Comment by abernier** [comment]
for the record, [`<CameraControls />`](https://github.com/pmndrs/drei#cameracontrols) is now part of pmndrs/drei
