### ISSUE TITLE
How to rotate by Polar angle no limit to infinity?

### ISSUE THREAD

**Issue by tankvn** [yomotsu/camera-controls#263]
## Describe the bug
I want control camera same as [ArcballControls](https://threejs.org/docs/index.html#examples/en/controls/ArcballControls) with minPolarAngle rotate to -Infinity and maxPolarAngle rotate to Infinity!

I tried set minPolarAngle < 0 and maxPolarAngle > Math.PI but it doesn't work

How can do that?

### Code
```js
cameraControls = new CameraControls( camera, renderer.domElement );
cameraControls.minPolarAngle = -Infinity;
cameraControls.maxPolarAngle = Infinity;
```

## Expected behavior
[https://threejs.org/examples/misc_controls_arcball.html](https://threejs.org/examples/misc_controls_arcball.html)

Thanks for helps!

**Comment by yomotsu** [comment]
Unfortunately, you can't do that. `polarAngle` must be between `0` and `Math.PI`.
CameraControls is a sort of OrbitControls in three.js.
