### ISSUE TITLE
Changing event dispatcher methods to protected has made it impossible to dispatch custom events

### ISSUE THREAD

**Issue by looeee** [yomotsu/camera-controls#264]
I just updated to the latest version and it broke some of my code. 

I'm using the controls to notify other parts of my app when the camera changes between orthographic and perspective

```  ts
export interface ModeChangeEvent {
	type: string;
	oldMode: '3d' | '2d';
	newMode: '3d' | '2d';
	cameraTypeWillChange?: boolean;
}

controls.dispatchEvent({
    type: 'modechangestart',
    oldMode: currentMode,
    newMode: mode,
    cameraTypeWillChange: true,
} as ModeChangeEvent);
```

I  also dispatch normal events in a couple of places - for example, I have camera gizmo in HTML and I manually dispatch `control` events in some cases when the user clicks on that:

``` ts
controls.dispatchEvent({ type: 'control' });
```

Since updating to 1.34.3 where the `dispatchEvent` method are now protected, these are both no longer possible and throw an error:

```
Property 'dispatchEvent' is protected and only accessible within class 'EventDispatcher' and its subclasses.
```

Here's a couple of ideas for this:

_**1.  Remove the protected status and handle all event stuff inside `EventDispatcher.ts` instead of inside `CameraControls.ts`**_

Is there any reason why all event dispatcher methods need to be protected within EventDispatcher and then re-declared inside CameraControls? 

Doing it this way means the `dispatchEvent` and `removeAllEventListeners` methods can no longer be used, and also you need to redeclare the `add/removeEventListener` methods inside the CameraControls file - these are just calling `super.addEventListener` and `super.removeEventListener` so doing this seems redundant. 

_**2. Add a `registerCustomEvent` method and make `dispatchEvent` accessible again**_

I guess you would do this in the same manner as add/remove, by re-declaring the methods inside `CameraControls` and calling `super`

I don't personally use  `removeAllEventListeners`  but it should probably also be made available in case other people need it.

**Comment by yomotsu** [comment]
Sorry for the [unexpected change](https://github.com/yomotsu/camera-controls/commit/c800f287569e4278c3975d4c8814034fb15ac194#diff-e802ef4a8c0f93df15cb4a1819f5bfe78db737f5e1a09818a138a2fa9f532293) and thanks for the suggestions.

I didn't think it was used. The change was to hide from [the generated docs](https://camera-controls.pages.dev/classes/CameraControls).
But it should be public as you pointed out.

I just revert it and will be available next patch.

**Comment by looeee** [comment]
Thank you for the extremely fast fix. I posted this issue, went to lunch and by the time I came back there's already a new release with a fix! That's awesome 😁 

> Also, the reason for re-declaring is to [specify the event types with CameraControlsEventMap](https://github.com/yomotsu/camera-controls/blob/a840f681e51cd2d21fc1156a824583a282c81c61/src/CameraControls.ts#L1251).
Then, VS code can suggest event types!

Ah, ok that's a good reason.

**Comment by yomotsu** [comment]
Thank you too!
Your report and suggestions are always helpful and make camera-controls better!
