### ISSUE TITLE
Inverted Drag

### ISSUE THREAD

**Issue by timothyallan** [yomotsu/camera-controls#266]
Hi there, just getting to know this great library, and came across a show stopper for me. I need the ability to invert the drag directions, and it doesn't seem like this exists currently?

OrbitControls allows for this by allowing a positive or negative `controls.rotateSpeed` variable. If you use a negative value, the rotate/drag operations are inverted.  i.e. dragging left now performs the same motion as dragging right used to etc...

**Comment by yomotsu** [comment]
There are `azimuthRotateSpeed` and `polarRotateSpeed` separately, and you can set a negative value to invert.
See:
https://github.com/yomotsu/camera-controls/blob/dev/examples/first-person.html#L61-L62

**Comment by timothyallan** [comment]
I totally missed those! Thanks for the assistance, and the camera controls :)
