### ISSUE TITLE
Could we enable a smooth transition when setBoundary is called?

### ISSUE THREAD

**Issue by kohloth** [yomotsu/camera-controls#268]
**Is your feature request related to a problem? Please describe.**

Could we enable a smooth transition when setBoundary is called?

I am creating a simulation of a parking lot with 5 floors.

Feature 1 that is working! :smiley_cat: : When a user presses Z, the camera moves down 1 floor with a smooth transition (controls.moveTo()). When the user presses A, the camera moves up one floor with a smooth transition (controls.moveTo()).

Feature 2 that is working! :smiley_cat: :To stop the camera view from being blocked by the floor above, I use controls.setBoundary to draw a box around the currently viewed floor. This means that when the user moves the camera close to the orbit target, and is looking down from above, the camera does not go too high, and does not have its view blocked by the floor above.

Problem: When using `controls.setBoundary` at the same time as `controls.moveTo`, each time the camera moves between floors, I remove the old boundary and add a new boundary. But what happens is:

1. The camera suddenly jumps further away from the target when I remove the boundary
2. The camera smoothly transitions down by 1 floor
3. The camera suddenly jumps closer to the target when I add the new boundary.

**Describe the solution you'd like**

Could the camera rotation and position have a smooth transition when its boundary is adjusted?

**Describe alternatives you've considered**

* I've tried hacking in a solution to freeze the camera's rotation and position relative to the target while the moveTo transition runs, but have not succeeded yet.
* I've tried using controls.lerpLookAt instead of controls.moveTo, but lerpLook at is limited by the boundary so I still see the sudden changes in position and rotation.

**Comment by yomotsu** [comment]
Would you mind providing a simplified demo to reproduce your problem?

**Comment by kohloth** [comment]
Sure...except I've started to create a demo, but am seeing an error that comes when instantiating the camera controls. Do you know what causes this?

https://codesandbox.io/s/camera-controls-example-tqo5ex?file=/index.js:191-208

`Cannot read properties of undefined (reading 'DEG2RAD')`

**Comment by yomotsu** [comment]
Seems the version of three.js in your code is too old and it doesn't have `THREE.MathUtils.DEG2RAD`.

**Comment by kohloth** [comment]
Ah I see now, yes codesandbox added an old version of threeJS for some reason.

I've updated the demo. https://codesandbox.io/s/magical-jennings-6lqylm?file=/src/index.js I'm afraid I can't quite get it working as I wanted, because I can't get the boundary to work now, but it is very close.

What you will see is that when you press A and Z:

* The transition between floors works smoothly (good)
* But when you rotate the camera so that it becomes high, it goes too high, and the two floors above block your view. (bad)

Now, if you enable the boundary by setting `useConstraint` to `true`, what you *should* see when you press A and Z (but won't as I can't get it to work) is that:

* The camera no longer goes too high, so your view does not get blocked by floors above (good)
* But the transitions between floors is not smooth (bad)

**Comment by yomotsu** [comment]
I think camera-controls works expected.

It seems Y of the boundary and the helper in your code are not matched.
![image](https://user-images.githubusercontent.com/212837/172114829-7100b8da-e484-4ce9-96f3-56700e2617df.png)
Please review your code again.
Then, setting `true` to `boundaryEnclosesCamera` could solve the problem.

Also, `collision` can be used in your case.
https://yomotsu.github.io/camera-controls/examples/collision.html

Lastly, sorry I can't help with specific applications issue. I hope you can understand...
