### ISSUE TITLE
Does not work when frameloop='demand'

### ISSUE THREAD

**Issue by roman-kh** [yomotsu/camera-controls#272]
## Describe the bug
The controls work only with frameloop='always', but not with 'demand'.

## To Reproduce

1. Go to [sandbox](https://codesandbox.io/s/yomotsu-camera-control-demand-1lvvhu)
2. Try to move the mouse
3. Nothing happens
4. Change frameloop to 'always'
5. Everything works perfectly

### Live example

[Demo sandbox](https://codesandbox.io/s/yomotsu-camera-control-demand-1lvvhu)

## Expected behavior
Works equally with 'always' and 'demand'

## Platform:
 - Device: Desktop, Mobile
 - OS: Windows, MacOS, Linux, Android, iOS
 - Browser: Chrome, Firefox, Safari

**Comment by yomotsu** [comment]
Thanks for your report.

I'm not good at r3f (and prefer to use three.js directly), so I think I can't give a good answer for this...
Anyway, it seems `frameloop='demand'` detects state change to re-render, right? So, you can change a state in `useFrame` if the cameraControls ref was updated, I guess.

Whether updated or not can be get with the return value of `cameraControls.update( delta )`.

**Comment by roman-kh** [comment]
When `frameloop=demand`, the frame is rendered only after `invalidate()` call.

So even though the pattern 
```
if (controls.update(delta))
    invalidate()
```
seems right, the question is when to call it.

You can't call it in `useFrame`, as there is no frame yet (it'll appear after `invalidate()`).
You can't call it in an `update` event callback, as an update event is triggered in `controls.update`.

That is probably why OrbitControls calls the `update` method after each action, from there it triggers a `'change'` event, which can be subscribed to, and in the event callback function one might call `invalidate` to render the frame.

Right now CameraControls can be used only in with regular loops (with or without drei).
It'l; be great if you can refactor code to make the controls more frame-efficient.

**Comment by roman-kh** [comment]
The problem was also mentioned in #166

**Comment by roman-kh** [comment]
The 'control' event fits the purpose for on-demand `invalidate()`.
Updated the [sandbox](https://codesandbox.io/s/yomotsu-camera-control-demand-1lvvhu) with detailed code.
