### ISSUE TITLE
Controls should react to clean mouse events (without special keys like Alt, Ctrl or Shift)

### ISSUE THREAD

**Issue by roman-kh** [yomotsu/camera-controls#273]
**Is your feature request related to a problem? Please describe.**
Now **controls** reacts to mouse events not taking into account whether any key is also being pressed at the moment.
So, for example, moving mouse and moving mouse with **ctrl** key pressed lead to the same action.

**Describe the solution you'd like**
**Controls** should react only to clean events (without any **shift**, **ctrl** or **alt** being pressed).
Or these modifiers should be configurable.

**Describe alternatives you've considered**
Right now it requires to listen to key events and disable controls which is not always possible or convenient.

Similar issues are #196 and #222.

**Comment by yomotsu** [comment]
Thanks for your suggestion.
But sorry, I don't get the meaning of "clean mouse events".
CameraContols uses pure PointerEvent(almost the same as mouse event).

What you would like to do is, remove shiftKey from the below line?
https://github.com/yomotsu/camera-controls/blob/fc2494e2c41d5c52028a029dd7e7f5cbcdabf7d6/src/CameraControls.ts#L510

**Comment by roman-kh** [comment]
When reacting to a PointerEvent you might check for modifier keys (ctrl, alt, shift) and react only if none of those are pressed.

Another, more universal way to do this might be to add an action object like this:
```
controls.actions = {
    left: CameraControls.ACTION.TRUCK,
    ctrlWheel: CameraControls.ACTION.ZOOM,
    shiftLeft: CameraControls.ACTION.ROTATE,
    ctrlRight: CameraControls.ACTION.OFFSET,
    toucheOne: CameraControls.ACTION.TOUCH_ROTATE,
    ...
}
```

Thus, if one wants to truck with _left_ or _ctrl+left_, it is easy to configure.

This is really important as one might want (or even need) to use a wheel for app-specific action, and zoom with _ctrl+wheel_.

**Comment by msemtd** [comment]
You can achieve this in your application code by disabling or altering the camera controls upon key hold and release.

**Comment by roman-kh** [comment]
Yes I can and I do. But it is quite inefficient and requires much more lines of unnecessary code.

On the other hand, now even though you set up the action to the left mouse button, it reacts to:
- mouse left
- ctrl + mouse left
- alt + mouse left
- shift + mouse left
Which is not right.

It is not accidentally that these modifiers are specified in the mouse event properties. So it might be useful to comply with the specification.

**Comment by msemtd** [comment]
Yes, like I say, we quite simply solve this in various applications by setting these _application-specific_ modes  in response to key holds and releases.

**Comment by roman-kh** [comment]
Let's imagine, you want to (or even have to) tie all actions to a left button: left - move, ctrl + left - zoom, shift + left - rotate, alt + left - reset.
Now you can see a screen full of if`s, you have to write to workaround the current behaviour. Moreover it heavily depends on the order of event listeners. 
For instance you can't disable the controls zoom action, in the app wheel event callback, as the controls callback was called earlier.
So It would be better to modify camera-controls to react only to the specified events.

**Comment by yomotsu** [comment]
As a library, I think camera-controls should only provide essential mouse events (without any keys).

- A user may want a pure mouse event without a key press
- A user may want a mouse event with a modifier key
- A user may want a mouse event with **multiple modifier keys** (like ctrl + shift + mouse event)
- A user may want a mouse event with **a letter key** press (like z + mouse event for zoom etc)

However, supporting all cases is complex. Thus I would like users to handle it, as @msemtd mentioned.
Although it may be redundant, can fit various cases.

Also, I guess we should remove `shiftLeft` bellow
https://github.com/yomotsu/camera-controls/blob/fc2494e2c41d5c52028a029dd7e7f5cbcdabf7d6/src/CameraControls.ts#L464-L474

e.g.
```js
const keyState = {
  shift: false,
};

const updateConfig = () => {

  if ( keyState.shift ) {

    cameraControls.mouseButtons.left = CameraControls.ACTION.ROTATE;

  }

}

document.addEventListener( 'keydown', ( event ) => {

  if ( event.keyCode === 16 ) keyState.shift = true;
  updateConfig();

} );

document.addEventListener( 'keyup', ( event ) => {

  if ( event.keyCode === 16 ) keyState.shift = false;
  updateConfig();

} );
```

**Comment by yomotsu** [comment]
Now, camera-controls doesn't detect the keys internally. The keys should be watched on the application side.
Added [an example using mouse modifier keys](https://yomotsu.github.io/camera-controls/examples/mouse-drag-with-modifier-keys.html).
Closing the issue.
