### ISSUE TITLE
Auto Rotation using React Three Fiber 

### ISSUE THREAD

**Issue by Kawan-edres** [yomotsu/camera-controls#278]
hello there , i love this npm what you created its so fantastic , just i have a problem i don't now how to add auto rotation to camera controls in react three fiber any one can help  ?

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
Just increase [`cameraControls.azimuthAngle`](https://github.com/yomotsu/camera-controls#properties) in `requestAnimationFrame`-tick loop.

**Comment by Kawan-edres** [comment]
thanks for your respond can you please provide a code sand box or any online editor just i want to see the code how to implement auto rotation i apprieciate your help yomotsu

**Comment by yomotsu** [comment]
Please see the example:
https://yomotsu.github.io/camera-controls/examples/auto-rotate.html

If you prefer React Three Fiber, please implement it by yourself.
Here is an essential R3F implication demo:
https://codesandbox.io/s/react-three-fiber-camera-controls-4jjor?file=/src/App.tsx

Note that, this library is not contract work or so. Thus we don't answer application-specific questions basically.
Thanks for your understanding.

**Comment by Kawan-edres** [comment]
OK how can i be come a sponsor ?

**Comment by yomotsu** [comment]
You can find the "Sponsor" button on the top page of this repository.
