### ISSUE TITLE
CameraControls.mouseButtons.middle doesn't work

### ISSUE THREAD

**Issue by ferminMZT** [yomotsu/camera-controls#285]
### Describe the bug

In the config example:
https://yomotsu.github.io/camera-controls/examples/config.html
The entry cameraControls.mouseButtons.middle doesn't work, no matter the value you assign to it.

The problem seems to be that cameraControls.mouseButtons.middle value is not taken into account.

### To Reproduce

1. Go to https://yomotsu.github.io/camera-controls/examples/config.html
2. Click on cameraControls.mouseButtons.middle and choose any value.
3. It doesn't work. In fact the central button is inoperative despite the chosen value.

### Live example

https://yomotsu.github.io/camera-controls/examples/config.html

### Expected behavior

Obviously the desired behaviour is that the selected value for the middle button must be correctly operative and working.

### Device

Desktop

### OS

Windows, Linux

### Browser

Chrome, Firefox

**Comment by yomotsu** [comment]
Thanks for your report.

I found the problem below...
the middle button should be `4`.
https://github.com/yomotsu/camera-controls/blob/b56861a550b67e49449cff3ffcb1fe99115240d4/src/types.ts#L22-L27

I will fix it later.

**Comment by yomotsu** [comment]
I think the middle button has been fixed.
Try out the dev version.
https://raw.githack.com/yomotsu/camera-controls/dev/examples/config.html

**Comment by ferminMZT** [comment]
Thank you very much for your fast response!!!.
Your control is the best and the more complete I ever see.
Best regards.

**Comment by yomotsu** [comment]
The fixed in version v1.36.0 has been released.
Closing the issue.
