### ISSUE TITLE
Zoom to Fill

### ISSUE THREAD

**Issue by Heilemann** [yomotsu/camera-controls#286]
### Is your feature request related to a problem? Please describe.

I have a situation where I need to zoom to a plane and have it fill the entire screen, leaving no room to see around it. I'm trying to do the math to make zoom to fit work, but my head exploded so...

### Describe the solution you'd like

Same as zoom to fit, just... fill 😄 

### Describe alternatives you've considered

Doing the math myself, and I suck apparently, so... It involves a proxy object which has to take into account the plane being zoomed to and the screensize, and I just can't make it work.

**Comment by yomotsu** [comment]
Thanks for your request.
I think here is the math.
![image](https://user-images.githubusercontent.com/212837/179870426-718879b8-609b-4444-90cd-d03134d78053.png)

Then now we have the angle θ.
However, `zoom` is actually a factor value of [`effectiveFOV` in three.js](https://github.com/mrdoob/three.js/blob/191a1ef699a5d53de2cd645c667e7fee184a18fd/src/cameras/PerspectiveCamera.js#L81-L86).
![image](https://user-images.githubusercontent.com/212837/179873525-be998d86-93ec-41eb-87a4-d0f0c5b23417.png)

What we need now is `this.zoom` above using the angle θ.

**Comment by yomotsu** [comment]
Sorry, Do you mean *dolly-to-fill*? I thought *zoom-to-fit* or *zoom-to-fill*.
[zoom and dolly are different](https://github.com/yomotsu/camera-controls#dolly-vs-zoom).

**Comment by yomotsu** [comment]
`cover` option has been added.
Can you try the dev version? You will see the "fit button" in the demo below.
https://raw.githack.com/yomotsu/camera-controls/dev/examples/fit-and-padding.html

Is this what you are looking for?

**Comment by Heilemann** [comment]
That looks exactly right.

**Comment by yomotsu** [comment]
Thanks for your checking.
I will publish it within this week then.

**Comment by Heilemann** [comment]
Awesome, thanks!

**Comment by yomotsu** [comment]
This feature has been added on v1.36.0.
`fitToBox()` now takes `cover` option to fill.

e.g.
```js
cameraControls.fitToBox( mesh, true, { cover: true } );
```
Closing the issue.

**Comment by Heilemann** [comment]
Thanks a lot, the turnaround on this was amazing!

**Comment by makc** [comment]
@yomotsu are there any plans for "contain" option? or maybe "fitBoxIn" method :D
