### ISSUE TITLE
CurrentAction always returns 0

### ISSUE THREAD

**Issue by Kevinparra535** [yomotsu/camera-controls#290]
### Describe the bug

When we listen to the events the `currentAction` **always returns 0**, it is supposed that for each action it does it should return the corresponding **number**, the demo of changing the cursor does not work either: [file](https://github.com/yomotsu/camera-controls/blob/dev/examples/cursor.html), [demo](https://yomotsu.github.io/camera-controls/examples/cursor.html).

### To Reproduce

1. Go to [demo](https://yomotsu.github.io/camera-controls/examples/cursor.html)
2. Click on Canva
3. See error, the cursor does not change

### Live example

https://yomotsu.github.io/camera-controls/examples/cursor.html

### Expected behavior

In version 1.33.1 it works correctly.

### Device

Desktop, Mobile

### OS

Windows

### Browser

Chrome, Firefox, Safari, Edge

**Comment by yomotsu** [comment]
Thanks for your report.
Reproduced.

I will fix it tomorrow!

**Comment by yomotsu** [comment]
The fixed version v1.36.0 has been released.
Closing the issue.
