### ISSUE TITLE
Dolly breaks setOrbitPoint

### ISSUE THREAD

**Issue by jbeard4** [yomotsu/camera-controls#292]
### Describe the bug

Calling setOrbitPoint and setting it to an object's centroid allows camera to rotate the object around its center. Then performing dolly seems to change the orbit point so that it is no longer the object's centroid. Instead it is the point where object's centroid used to be before performing dolly.  

### To Reproduce

1. Load a geometry
2. Call setOrbitPoint to set the orbit point to the center of the geometry. To simplify, assume the centroid is the origin.
3. Rotate to confirm that the geometry rotates around its centroid.
4. Dolly to move the geometry so that its centroid is no longer on the origin.
5. Rotate to confirm that the geometry rotates around the new origin, rather than the centroid of the OBJ. 

### Expected behavior

I would expect the camera to continue to rotate around the object's centroid after calling setOrbitPoint on the object's centroid, and then performing dolly.

### Screenshots or Video

First rotate object around its center (which is also the origin). Then perform camera dolly, and rotate the object again. The object rotates around the point that was previously the origin, before performing dolly:
![Screencast from 07-31-2022 01:00:15 PM](https://user-images.githubusercontent.com/586962/182041298-4a765eb0-239f-4b4e-8ebf-28ce8c2ce82f.gif)

### Device

Desktop

### OS

MacOS, Linux

### Browser

Firefox

**Comment by yomotsu** [comment]
Thanks for your report.
However, it seems to work as expected for me.
Below is what I tried according to the step you provided.

1. Open https://yomotsu.github.io/camera-controls/examples/basic.html
2. Open console.
3. Exec below code in the console.
```
mesh.position.x = 3;
cameraControls.setOrbitPoint( 3, 0, 0 );
cameraControls.dollyTo( 5, true );
```
4. Rotate to confirm the box rotates around ( 3, 0, 0 ), which is expected behavior.

Please double-check your code. If you think there is a bug, please share a **simplified woking example** to reproduce.

**Comment by jbeard4** [comment]
Hi @yomotsu, thanks for your reply, and for providing this test framework. 

I was able to follow your instructions, and can confirm `setOrbitPoint` was working as expected, as per your instructions.

I was invoking dolly using the two-finger click and drag, and was able to confirm that this does seem to break `setOrbitPoint` in the provided test framework, as seen in the below gif.

![Screen_Capture_select-area_20220803223528](https://user-images.githubusercontent.com/586962/182770393-37c334bb-0dae-486d-99cc-2b4789672ad0.gif)


Steps to reproduce are: 

1. Open https://yomotsu.github.io/camera-controls/examples/basic.html
2. Open console.
3. Exec below code in the console.

```
mesh.position.x = 3;
cameraControls.setOrbitPoint( 3, 0, 0 );
cameraControls.dollyTo( 5, true );
```

4. Rotate to confirm the box rotates around ( 3, 0, 0 ), which is expected behavior.
5. Two-finger click and drag to pan the camera.
6. One-finger click and drag to rotate the camera. Confirm that rotation is no longer around the object's center point.

Are the semantics of two-finger click and drag different than cameraControls.dolly? Is there a way to use two-finger click and drag to pan the camera so setOrbitPoint continues to work?

I would appreciate any insight you can share on this. Thank you for your help.

**Comment by yomotsu** [comment]
>  rotation is no longer around the object's center point.

I think that is correct behavior. the orbit point is translated by dragging the camera at [5]. `truck` movement will move the "center" as well.

**Comment by jbeard4** [comment]
Understood, thank you for clarifying this. Closing this issue now, as this is expected behavior and not a bug.
