### ISSUE TITLE
Camera-Controls not working with drei's Html component

### ISSUE THREAD

**Issue by Paolo-Sotorro** [yomotsu/camera-controls#293]
### Describe the bug

The controls are not working when the pointer is hovering over drei's Html component which is problematic especially when scrolling and such component moves under the pointer. 
There is no problem when OrbitControls are bein used  - the pointer events are being propagated to the canvas below html without any problems. 
I'm attahcing an example with camera-controls and orbitcontrols. 

### To Reproduce

3. See error

### Live example

https://codesandbox.io/s/react-three-fiber-camera-controls-forked-0xhzui

### Expected behavior

Controls should behave like orbticontrols - the events should be propagated to the canvas below. 

### Device

Desktop

### OS

Windows

### Browser

Chrome

**Comment by yomotsu** [comment]
Thanks for using.
That is expected behavior.
If you wish to make it transparent, set `pointer-event: none` in CSS.

**Comment by Paolo-Sotorro** [comment]
Thanks for quick response. 
Actually this is a problem for me as I need to make a onClick action on this Html so I cannot disable pointer events completely. 
Is there any way to get around this? 
BR

**Comment by yomotsu** [comment]
@Paolo-Sotorro 

the second argument for camera-controls class is the DOM element to attach mouse draggings.
https://github.com/yomotsu/camera-controls#constructor

In your code, the second arg is `renderer` canvas, which is covered by the green div element in your example that blocks all events.
https://codesandbox.io/s/react-three-fiber-camera-controls-forked-0xhzui?file=/src/camera-controls.tsx:1433-1473

Maybe you can set the parent element for the second argument for camera-controls.
e.g.
```
new CameraControls(
  yourCameraInstance,
  parentWrapperDivElementWhichContainsBothCanvasAndGreenDiv,
);
```

**Comment by yomotsu** [comment]
another option is, to set `pointer-event: none` and revert `pointer-event` to `auto` on your buttons.

e.g.
```html
<canvas>
<coverAndBlockingDiv style="pointer-events: none;">
  <button  style="pointer-events: auto;"> you can click here. </button>
</coverAndBlockingDiv>

```

**Comment by Paolo-Sotorro** [comment]
You are truly a Great Man :) Thanks!
