### ISSUE TITLE
Allow "enableTransition" to have independent "dampingFactor"

### ISSUE THREAD

**Issue by Strepto** [yomotsu/camera-controls#295]
### Is your feature request related to a problem? Please describe.

If the `dampingFactor` is `1` for accurate navigation and rotation, the `enableTransition` of `setTarget` and `setPosition` no longer has any effect as the transition will be instantly finished. I would like for this to still have an animation. 

Methods with `enableTransition` parameter, such as `setTarget` and `setPosition` has transition speed based on the `dampingFactor`. If the `dampingFactor` is 1 (disabled) the transition will be instant.

### Describe the solution you'd like

I would like to either

a: 
setTargetAnimated(Vec3 target, number animationTime)

or 

b: 
Add a `transitionDampingFactor` or `transitionTime` that can be used if the previous interaction was a `setTarget` with `enableTransition = true` (or similar for other setA, setB etc) 

### Additional context

Thank you for a great library :)

I might be able to create a PR for this if you find an acceptable idea for a solution.

**Comment by yomotsu** [comment]
camera-controls combine all movements into one, then move gradually using damping.
`dampingFactor` is the essence, and I think we can't separate.

If you wish specific animation that ignore `dampingFactor`, use a tween library.
see https://yomotsu.github.io/camera-controls/examples/path-animation.html

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
