### ISSUE TITLE
how to update camera-controls when camera apply quaternion 

### ISSUE THREAD

**Issue by yasuomang** [yomotsu/camera-controls#297]
### Describe the bug

after my camera apply  quaternion and use setLookAt function to set target,once i control camera,the CameraControls jumps a little.

### To Reproduce

1. camera apply  quaternion
2. use setLookAt function to set target
3.  rotate or dolly
4. the CameraControls jumps

### Expected behavior

behavior as I do not  apply  quaternion to my camera

**Comment by yomotsu** [comment]
You can't modify the camera state directly as long as you use the camera-controls.
To change camera state (such as quaternions), use a camera-controls methods.

What you are doing is like, modifying DOM directly in a React component (VDOM).

**Comment by yasuomang** [comment]
> You can't modify the camera state directly as long as you use the camera-controls. To change camera state (such as quaternions), use a camera-controls methods.
> 
> What you are doing is like, modifying DOM directly in a React component (VDOM).

But  I do not find the camera-controls methods which is use to modify the camera quaternions.

**Comment by yomotsu** [comment]
There are several methods to change the rotations (quaternions).
Please check [the documentation](https://camera-controls.pages.dev/classes/CameraControls) and [examples](https://github.com/yomotsu/camera-controls#examples)

**Comment by yasuomang** [comment]
> 

I like camera-controls. And I use setLookAt()  after change camera quaternion.It will case the CameraControls jump.But if I remove the camera quaternion code,it is good for me. So I thought I do not use the CameraControls method to modify the camera quaternions.Forgive my bad English.

**Comment by yasuomang** [comment]
> There are several methods to change the rotations (quaternions) such as `setLookAt()`, `setTarget()` and more. Please check [the documentation](https://camera-controls.pages.dev/classes/CameraControls) and [examples](https://github.com/yomotsu/camera-controls#examples)
> 
> If you really wish to control the camera directly, you can't use camera-controls anymore...

I like camera-controls. And I use setLookAt()  after change camera quaternion.It will case my camera jump.But if I remove the camera quaternion code,it works fine. So I thought I do not use the CameraControls method to modify the camera quaternions.Forgive my bad English.

**Comment by yomotsu** [comment]
In camera-controls, the camera is **always** face to the `target`.
That means, the camera rotation(quaternion) is automatically caused by the angle between the camera and the target.

If you need "set quaternion", calculate the direction(angle) of the given quaternion, then set the direction to the target position via `setTarget()`. Then the camera will look at the target position using the angle of the given quaternion.

**Comment by yasuomang** [comment]
> In camera-controls, the camera is **always** face to the `target`. That means, the camera rotation(quaternion) is automatically caused by the angle between the camera and the target.
> 
> If you need "set quaternion", calculate the direction(angle) of the given quaternion, then set the direction to the target position via `setTarget()`. Then the camera will look at the target position using the angle of the given quaternion.

I know what you mean, I think I should create a code-open demo，thank for your reply, Please give me some time

**Comment by yasuomang** [comment]
> In camera-controls, the camera is **always** face to the `target`. That means, the camera rotation(quaternion) is automatically caused by the angle between the camera and the target.
> 
> If you need "set quaternion", calculate the direction(angle) of the given quaternion, then set the direction to the target position via `setTarget()`. Then the camera will look at the target position using the angle of the given quaternion.

https://codepen.io/yasuomang/pen/ExEGoKy , this is the link . If you click the `change camera quaternion`  button, and dolly,the camera seems rotate a liitle.

**Comment by yomotsu** [comment]
Thanks for the demo, however, I don't get the point. the code contains unnecessary features I think...
I don't understand your situation.

What I can say so far are:

Don't do this
```
camera.quaternion.copy(_tempQuaternion)
```
if you wish to rotate the camera, use camera-controls methods instead.

and you need to enable update
```
// const updated = cameraControls.update( delta );
```

**Comment by yasuomang** [comment]
> Thanks for the demo, however, I don't get the point. the code contains unnecessary features I think, and I don't understand your situation. Why do you need to set quaternion directly...? As I said, the camera can be rotated using camera-controls methods.
> 
> What I can say so far are:
> 
> Don't do this (use camera-controls methods instead.)
> 
> ```
> camera.quaternion.copy(_tempQuaternion)
> ```
> 
> and you need to enable update
> 
> ```
> // const updated = cameraControls.update( delta );
> ```

Because I want to rotate the camera (quaternion),and use the raycaster, send a ray from camera to the canvas center ,get the first point (maybe collide a mesh),and set the first point as target.

**Comment by yasuomang** [comment]
> Thanks for the demo, however, I don't get the point. the code contains unnecessary features I think, and I don't understand your situation. Why do you need to set quaternion directly...? As I said, the camera can be rotated using camera-controls methods.
> 
> What I can say so far are:
> 
> Don't do this (use camera-controls methods instead.)
> 
> ```
> camera.quaternion.copy(_tempQuaternion)
> ```
> 
> and you need to enable update
> 
> ```
> // const updated = cameraControls.update( delta );
> ```

https://codepen.io/yasuomang/pen/ExEGoKy?editors=1010 , I click `change camera quaternion` and log the camera quaternion, then click `change camera quaternion` button and log the camera quaternion, there are different between two quaternion.Is I use correct camera-controls methods to  rotate the camera ?

**Comment by yasuomang** [comment]
> > Thanks for the demo, however, I don't get the point. the code contains unnecessary features I think, and I don't understand your situation. Why do you need to set quaternion directly...? As I said, the camera can be rotated using camera-controls methods.
> > What I can say so far are:
> > Don't do this (use camera-controls methods instead.)
> > ```
> > camera.quaternion.copy(_tempQuaternion)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and you need to enable update
> > ```
> > // const updated = cameraControls.update( delta );
> > ```
> 
> https://codepen.io/yasuomang/pen/ExEGoKy?editors=1010 , I click `change camera quaternion` and log the camera quaternion, and then click `reset` button, then click `change camera quaternion` button and log the camera quaternion, there are different between two quaternion.Is I use correct camera-controls methods to rotate the camera ?

The issue is that use camera-controls methods to apply camera quaternion, get different result compared to set quaternion directly .

**Comment by yoanngueny** [comment]
Hi @yasuomang 

As Yomotsu explained it's not possible to update the internal camera directly.
So there are no methods to use Quaternion in Camera-Controls.
You should use the "target" system to rotate your camera correctly.

I've followed the [solution of Yomotsu](https://github.com/yomotsu/camera-controls/issues/297#issuecomment-1219258658) and it works for me.

So here is a pseudo code way to "convert quaternion to a target"
```
// create a temporary target because we need "translateOnAxis" that is only present in Object3D
const target = new Object3D()
// apply my quaternion to this target
target.rotation.setFromQuaternion(myQuaternion)
// translate just of little bit on the opposite z axis
target.translateOnAxis(new Vector3(0, 0, -1), .01)
// set my temporary target position
this._cameraMainManager.controls.setTarget(
  target.position.x,
  target.position.y,
  target.position.z,
  false
)
```

**Comment by yomotsu** [comment]
@yoanngueny Thanks for your help. That is exactly what I meant!

**Comment by yasuomang** [comment]
> Hi @yasuomang
> 
> As Yomotsu explained it's not possible to update the internal camera directly. There are no methods to use Quaternion in Camera-Controls. You should use the "target" system to rotate your camera correctly.
> 
> I've followed the [solution of Yomotsu](https://github.com/yomotsu/camera-controls/issues/297#issuecomment-1219258658) and it works for me.
> 
> So here is a pseudo code way to "convert quaternion to a target"
> 
> ```
> // create a temporary target because we need "translateOnAxis" that is only present in Object3D
> const target = new Object3D()
> // apply my quaternion to this target
> target.rotation.setFromQuaternion(myQuaternion)
> // translate just of little bit on the opposite z axis
> target.translateOnAxis(new Vector3(0, 0, -1), .01)
> // set my temporary target position
> this._cameraMainManager.controls.setTarget(
>   target.position.x,
>   target.position.y,
>   target.position.z,
>   false
> )
> ```

But `myQuaternion ` will not equal to `camera quaternion` after `setTarget()` .This` is where I'm confused.@yomotsu @yoanngueny

**Comment by yomotsu** [comment]
I think now you know what `setTarget()` can do.
Please try to solve your situation by yourself!

**Comment by yasuomang** [comment]
> I think now you know what `setTarget()` can do. Please try to solve your situation by yourself!

In other words, I just rotate camera  z  axis with  `Math.PI/2`, so the target will not change. Now the camera rotation will not apply `Math.PI/2` because the target is the same.

**Comment by yomotsu** [comment]
Do you mean that, to make the camera keeps looking opposite the target position, or outside of the spherical?

**Comment by yasuomang** [comment]
> Do you mean that, to make the camera keeps looking opposite the target position, or outside of the spherical?

 Make the camera keeps looking opposite the target position. 
**First**
![image](https://user-images.githubusercontent.com/62331159/186381065-52cb6da9-264f-4569-a791-3282e11bc898.png)
** Flip Camera**
![image](https://user-images.githubusercontent.com/62331159/186380950-1063c090-da8e-4dd2-9759-b24669e63d07.png)

The target will not change.But I can not get the same rotation after camera-control update.

**Comment by yasuomang** [comment]
> What about using `camera.up`? see https://yomotsu.github.io/camera-controls/examples/camera-up.html

It is an uncertain angle, and  using `camera.up` will change `lookAt()` system. There is a similar issue for orbit-control.https://discourse.threejs.org/t/rotate-camera-and-update-orbitcontrol-with-the-new-camera-rotation/33476/10
I think it is a `lookAt()` issue.
