### ISSUE TITLE
Camera target is not kept within boundaries with dollyToCursor enabled

### ISSUE THREAD

**Issue by tampiland** [yomotsu/camera-controls#298]
### Describe the bug

I am trying to visualize objects on a flat square surface without being able to dolly through the surface. I chose this library mainly to enable dolly to cursor.

To limit camera movement I created a boundary for the camera target, an almost flat box just above the surface. I also set min/maxDistance and min/maxPolarAngle.

It all works well with dollyToCursor disabled, but when I enable it the boundary doesn't seem to be applied at all times. I can dolly through the surface, or not reach all the way down.

When I visualize the camera target it looks like it's not keept withing the boundary when dollyToCursor is enabled.

### To Reproduce

1. Set a boundary
2. Set max/minDistance
3. Set max/minPolarAngle
4. Visualize camera target and boundary
5. Set dollyToCursor to false
6. See how the camera target is kept within boundary when dollying back and forth
7. Set dollyToCursor to true
8. See how the camera target is not kept within boundary when dollying back and forth, cursor not centered

### Live example

https://codesandbox.io/s/serene-danny-htvh17

### Expected behavior

The boundary should be applied to the camera target when dollyToCursor is enabled.

### Screenshots or Video

The camera target (red) is way outside the boundary which is located on top of the gray surface.
![image](https://user-images.githubusercontent.com/55835438/186140275-ebe16bf0-60a0-48c6-b099-e4051feaf930.png)

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by yomotsu** [comment]
@tampiland 

Thanks for your report.
I confirmed the problem, thanks to your live example.

I also have made a PR for this. Is the video in the below PR looking good as expected?
https://github.com/yomotsu/camera-controls/pull/299

**Comment by tampiland** [comment]
@yomotsu 

Thank you for the swift response. The video seems to be the result I was looking for. Great!

**Comment by yomotsu** [comment]
@tampiland Thank you for confirming. I just published a patched version.
