### ISSUE TITLE
Traditional FPS Example

### ISSUE THREAD

**Issue by alexpineda** [yomotsu/camera-controls#300]
### Is your feature request related to a problem? Please describe.

In the FPS example the camera doesn't "look at" the mouse cursor (and essentially, rotate the target around the camera position). I would love an example of a more traditional FPS controller as I'm trying to implement one and failing :(

### Describe alternatives you've considered

I could use the three built in FPS controller but I'd like to keep a uniform interface since the cameras are plugins that other people author and control.

**Comment by yomotsu** [comment]
Thanks for your suggestion.

I think the behavior you suggested requires `PointerLock` to prevent mouse cursor leaving the browser, which is out of the scope of camera-controls.
The behavior can be done with camera-controls but will be complex to show as an example.

If I need both TPS and FPS in one project, I would use both camera-controls and another FPS, then switch them by scene.

**Comment by alexpineda** [comment]
Ok no worries then. Still a very useful library!

**Comment by yomotsu** [comment]
Thanks for understanding.
If you find other suggestions or requests, feel free to post issues.

Closing this issue for now.
