### ISSUE TITLE
CameraControls.ACTION.TOUCH_ROTATE_ZOOM

### ISSUE THREAD

**Issue by tampiland** [yomotsu/camera-controls#301]
### Is your feature request related to a problem? Please describe.

I really want one-finger touch mapped to truck, leaving me with no other option than to use both two and three fingers to add rotate and zoom. Three fingers messes with some devices.

Preferably I'd like to go from:

cameraControls.touches.one = CameraControls.ACTION.TOUCH_TRUCK;
cameraControls.touches.two = CameraControls.ACTION.TOUCH_ROTATE;
cameraControls.touches.three = CameraControls.ACTION.TOUCH_ZOOM;

to:

cameraControls.touches.one = CameraControls.ACTION.TOUCH_TRUCK;
cameraControls.touches.two = CameraControls.ACTION.TOUCH_ROTATE_ZOOM;

### Describe the solution you'd like

A combined touch setting for rotate and zoom, name it:

CameraControls.ACTION.TOUCH_ROTATE_ZOOM

or

CameraControls.ACTION.TOUCH_ZOOM_ROTATE

### Describe alternatives you've considered

Sacrifice dolly to cursor and leave this library completely.

**Comment by yomotsu** [comment]
Thanks for your request. The option you suggested is missing obviously...I just added  `TOUCH_DOLLY_ROTATE` and `TOUCH_ZOOM_ROTATE` https://github.com/yomotsu/camera-controls/pull/302.

Is the below example what you expected?
(Check `cameraControls.touches.two` option in the demo)
https://raw.githack.com/yomotsu/camera-controls/dev/examples/config.html

I will publish the updated version soon as well.

**Comment by tampiland** [comment]
That’s perfect, thank you!

**Comment by tampiland** [comment]
@yomotsu When do you think you will publish an updated version?

**Comment by yomotsu** [comment]
I'm very sorry I completely forgot that since I've been busy recently.
I just published v1.37.0, available on npm!

**Comment by tampiland** [comment]
Thanks @yomotsu ! 
Unfortunately I must bother you with asking if you might have missed adding the new types to types.d.ts? I get this error when trying to use the types in typescript:

`TS2339: Property 'TOUCH_DOLLY_ROTATE' does not exist on type 'Readonly<{ readonly NONE: 0; readonly ROTATE: 1; readonly TRUCK: 2; readonly OFFSET: 4; readonly DOLLY: 8; readonly ZOOM: 16; readonly TOUCH_ROTATE: 32; readonly TOUCH_TRUCK: 64; readonly TOUCH_OFFSET: 128; ... 5 more ...; readonly TOUCH_ZOOM_OFFSET: 8192; }>'.`

**Comment by yomotsu** [comment]
sorry, for that.
I got another error to it and fixed it with v1.37.1. could you please try again?

**Comment by tampiland** [comment]
Thank you! Now I get no errors, however, TOUCH_DOLLY_ROTATE seems to be exactly like TOUCH_ZOOM_ROTATE, i.e. it zooms instead of doing dolly.

**Comment by yomotsu** [comment]
Oops, I found a problem in the code...I will fix it tonight (or tomorrow)!

**Comment by yomotsu** [comment]
@tampiland 
I think that was fixed with https://github.com/yomotsu/camera-controls/pull/304.
Can you check the below behavior?
https://raw.githack.com/yomotsu/camera-controls/issues-301-2/examples/config.html

**Comment by tampiland** [comment]
I think so too. Tried it a bit on my phone and DOLLY_ROTATE now seems seems to do what it should. Good work!

**Comment by tampiland** [comment]
Tried it in my project now and it works like a charm! Thanks!

**Comment by yomotsu** [comment]
Good to hear that!
