### ISSUE TITLE
Mesh walk with raect-three-fiber

### ISSUE THREAD

**Issue by ChanderShekharKestone** [yomotsu/camera-controls#305]
Hi any one have mesh walk example with react-three-fiber. Like below
[https://yomotsu.github.io/walkthrough/](https://yomotsu.github.io/walkthrough/).
Or any suggestion how i can achive.

**Comment by ChanderShekharKestone** [comment]
> Thanks for trying the demo. The TPS game-ish collisiton is not a part of this lib. Although [I made it](https://github.com/yomotsu/meshwalk), it's not maintained anymore... Unfortunately, I can't do anything for now...

Thanks for reply.
Please suggest me how i use (https://yomotsu.github.io/walkthrough) in react.

**Comment by yomotsu** [comment]
Sorry, I can't work for your spesific project...
This issue is for bug reports and feature requests for camera-controls.

**Comment by ChanderShekharKestone** [comment]
Thanks and i dont' know how to add feature requests for camera-controls.
