### ISSUE TITLE
Does not work with Gizmo

### ISSUE THREAD

**Issue by promontis** [yomotsu/camera-controls#307]
### Describe the bug

When you click on the surface areas of the gizmo, it should rotate to the correct position, which it does not. 

### To Reproduce

Compare https://codesandbox.io/s/yomotsu-camera-control-demand-forked-xsb3q5 (which is using camera-controls) to https://drei.pmnd.rs/?path=/story/gizmos-gizmohelper--gizmo-helper-story (which is using orbit controls).

### Live example

https://codesandbox.io/s/yomotsu-camera-control-demand-forked-xsb3q5

### Expected behavior

Rotate to the correct position

**Comment by yomotsu** [comment]
I think that is `GizmoViewcube` problem.
Do you mind opening an issue in their repository?

**Comment by yomotsu** [comment]
I think this request is out of scope.
Let me close this issue.
