### ISSUE TITLE
Is that possible to use 'position' and 'target' to save the cameraControls state?

### ISSUE THREAD

**Issue by lintonfirst** [yomotsu/camera-controls#308]
### Is your feature request related to a problem? Please describe.

To save the cameraControls state, it needs to save three parameters: 'position','target' and 'focaloffset'.

When I need to display the same viewport with another Controls(such as THREE.OrbitControls, which simply uses 'position' and 'target' ),Is there a way to conversion the three parameters('position','target' and 'focaloffset') into two parameters('position','target')?

### Describe the solution you'd like

Could you provide an auxiliary function to support such conversion?

```
conversion(outPosition: THREE.Vector3,outTarget: THREE.Vector3)
```

using this function,I can render the same viewport without setting 'focaloffset'.

### Additional context

I'm not sure that such feature is feasible.
Thanks for providing the controls with so many nice features

**Comment by yomotsu** [comment]
Although our CameraControls and THREE.OrbitControls look similar, ours is not compatible with that, as you mentioned.
If you need the conversion, you should make one in userland.

**Comment by lintonfirst** [comment]
Thanks for your reply.
However, it seems hard to convert in the userland.I dont't know how to compose the exposed methods to realize it.
Is there any tip of the conversion?

**Comment by yomotsu** [comment]
You can just use `getPosition()`, `getTarget()`, `getFocalOffset()` (also set methods), or `toJSON()` and `fromJSON()`.
For more detail, you can read [the docs](https://github.com/yomotsu/camera-controls#methods).

Regarding `focalOffset`,
I think `THREE.OrbitControls` can't reproduce `focalOffset`.
If you need `focalOffset` in `THREE.OrbitControls`, send a feature request to three.js repository.
