### ISSUE TITLE
saveState and _focalOffset0

### ISSUE THREAD

**Issue by makc** [yomotsu/camera-controls#310]
### Is your feature request related to a problem? Please describe.

I have noticed that saveState() does not save _focalOffset0 - is it intentional? because, for example, reset() does use it - how safe is to use saveState() and reset() in pair?

**Comment by yomotsu** [comment]
Hi @makc,
Thanks for your report.
I didn't notice it. it's not intentional obviously. because `focalOffset` is a relatively new property. `saveState()` should write `_focalOffset0` as you mentioned.

**Comment by yomotsu** [comment]
Closing the issue.
This has been fixed with v1.37.3.
