### ISSUE TITLE
Shifted raycaster when using focalOffset

### ISSUE THREAD

**Issue by tobgebert-JvM** [yomotsu/camera-controls#312]
Kinda stuck with how to properly counter a focalOffset inside a raycaster. These two things don't seem to match. I've tried different ways of adding getFocalOffset's values to the pointer before raycaster.setFromCamera, but unfortunately it's not that simple. Any hints would be greatly appreciated!

**Comment by yomotsu** [comment]
I'm sorry I can't answer every single question.
Please use issues for a bug report or feature request.

If you think there is a bug in CameraControls, please report the problem.
