### ISSUE TITLE
focalOffset causes raycaster to miss

### ISSUE THREAD

**Issue by tobgebert-JvM** [yomotsu/camera-controls#313]
### Describe the bug

Using focalOffset with raycaster.setFromCamera() leads to unexpected behaviour.

### To Reproduce

1. set a focalOffset like (0.5,0,0)
2. use a raycaster using setFromCamera
3. raycast hit is now shifted sideways

### Live example

[codesandbox](https://j0whtz.csb.app/)

### Expected behavior

Raycaster should hit things where they are.

**Comment by yomotsu** [comment]
Thanks for your report however I can't reproduce your problem.
Do you mind providing a SIMPLIFIED working example, please?

**Comment by tobgebert-JvM** [comment]
Updated with live example link.

**Comment by yomotsu** [comment]
Here is the *SOLUTION*!

call `camera.updateMatrixWorld();` before `raycaster.setFromCamera(pointer, camera);`
https://codesandbox.io/s/camcontrols-raycast-offset-forked-fnpikb?file=/index.html:2525-2552

**Comment by tobgebert-JvM** [comment]
Thanks! I realized it also works if the raycast call comes after the render call, but that wasn't going to work well in our application. UpdateMatrixWorld does the trick though, can't see any performance impact either (felt like there could be).
