### ISSUE TITLE
Rotate around courser point

### ISSUE THREAD

**Issue by EberleAutomatischeSysteme** [yomotsu/camera-controls#314]
### Is your feature request related to a problem? Please describe.

For our project we are looking for a camera controller for Three.js that works like a CAD program.

### Describe the solution you'd like

The rotation should be done over the hitpoint of the object without moving the rotation point into the center of the scene.

### Additional context

Is such an extension generally possible for this controller?

**Comment by yomotsu** [comment]
do you mean this example?
(click to set orbit point)
https://yomotsu.github.io/camera-controls/examples/click-to-set-orbit-point.html

**Comment by EberleAutomatischeSysteme** [comment]
Yes this is exactly what I was looking for. 
Thanks for the answer. In this case, this featur request has quickly settled ^^

**Comment by yomotsu** [comment]
let me close the issue then
