### ISSUE TITLE
How to store current camera position + target before transitioning

### ISSUE THREAD

**Issue by sameerul97** [yomotsu/camera-controls#315]
### Describe the bug

How can I correctly store the camera position + angles when clicking one of the image and return back to it after i click close button (bottom right)?. Camera moves to clicked mesh (image) using `fitToBox(mesh,....)` and `rotateTo(...)`. 

i tried storing the camera position onClick event by using `getPosition(vec)` and `getTarget(tarVec)`. However that doesn't work as expected. Target seems to rotate back to original position, but camera position is wrong. Trying to store the position, instead of using `reset()` as i want to keep track of existing position + camera rotation before user clicks the image. 

### To Reproduce

1. Go to 'https://codesandbox.io/s/react-three-fiber-camera-controls-forked-7zo7xn?file=/src/App.tsx'
2. Notice you can see pink cone infront of the camera
3. Click on 'any of the image'
4. Click on the close button (bottom right)
5. Camera animates to position but not to original position
6. Expect to see the pink cone again.

### Live example

https://codesandbox.io/s/react-three-fiber-camera-controls-forked-7zo7xn?file=/src/App.tsx

### Expected behavior

After clicking close button is it possible to have the camera back in it's original position + rotation. Eg: If the user interacted with the camera by panning left, i would like to store that value and return back to its original value. 

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by yomotsu** [comment]
Thanks for using camera-controls (also providing the example).
What about using `toJSON()` to save the state and `fromJSON( json, enableTransition )` to restore the state?

**Comment by sameerul97** [comment]
@yomotsu  Thanks for the suggestion :) . But that didn't work as well. Now the [CodeSandBox](https://codesandbox.io/s/react-three-fiber-camera-controls-forked-7zo7xn?file=/src/App.tsx)  contains `toJson()` and `fromJson(pos,true)`. Camera ends back in wrong angle. If you click Torus geometry (Right side green ring) and click close, camera ends back in different angle. Tried setting a timeout before moving the camera but no joy.

**Comment by sameerul97** [comment]
Have investigated the issue bitmore, can confirm that camera only ends back in different position when using `fitToBox(...p) method to animate the camera`. [Line 55, used `moveTo()`](https://codesandbox.io/s/react-three-fiber-camera-controls-forked-7zo7xn?file=/src/App.tsx) and clicked close button. Now the camera ends back in correct position.  Feel free to close the isssue, i will look out for alternate solution.

**Comment by yomotsu** [comment]
Good to hear that.
Closing the issue as completed.
