### ISSUE TITLE
setOrbitPoint make world position transform to screen position wrong

### ISSUE THREAD

**Issue by LuckyTeresa** [yomotsu/camera-controls#319]
### Describe the bug

I  reproduced this question in  exampls/focal-offset.html

### To Reproduce

1、Added an axesHelper to scene, and axesHelper's position is (0,0,0) 
2、open in browser and open the consoler
3、execute the code below
4、execute  controls.setOrbitPoint(10,10,0)
5、execute the code again
axesHelper doesn't move, but it's screen position changed.

### Code

```js
var halfHeight = window.innerHeight / 2;
var halfWidth = window.innerWidth / 2;
var p = new THREE.Vector3(0,0,0);
var target =  new THREE.Vector2();
var vector = p.project(camera);
target.x = Math.round(vector.x * halfWidth + halfWidth);
target.y = Math.round(-vector.y * halfHeight + halfHeight);
console.log(target);
```

### Expected behavior

world position transfrom to screen position  can be correct after set orbitPoint

### Screenshots or Video

[](url)
![企业微信截图_16673854244179](https://user-images.githubusercontent.com/33902263/199469112-bcf6ae79-15c7-4434-9134-77e7d83a5ec8.png)

### Device

Desktop

### OS

Windows

### Browser

Chrome

**Comment by yomotsu** [comment]
Thanks for using camera controls and a detailed report.

What about this?:
```js
var halfHeight = window.innerHeight / 2;
var halfWidth = window.innerWidth / 2;
var p = new THREE.Vector3(0,0,0);
var target =  new THREE.Vector2();
camera.updateMatrixWorld() // ADDED: update matrix before using camera matrix
var vector = p.project(camera);
target.x = Math.round(vector.x * halfWidth + halfWidth);
target.y = Math.round(-vector.y * halfHeight + halfHeight);
console.log(target);
```

**Comment by LuckyTeresa** [comment]
It works well,thank you very much!!  I had try to update the matrix in other event but doesn't work.Thanks again!

**Comment by LuckyTeresa** [comment]
It works well,thank you very much!! I had try to update the matrix in other event but doesn't work.Thanks again!

**Comment by LuckyTeresa** [comment]
It works well,thank you very much!! I had try to update the matrix in other event but doesn't work.Thanks again!

**Comment by LuckyTeresa** [comment]
It works well,thank you very much!! I had try to update the matrix in other event but doesn't work.Thanks again!
