### ISSUE TITLE
Making R3F aware of the controls 

### ISSUE THREAD

**Issue by Paolo-Sotorro** [yomotsu/camera-controls#324]
HI,

How can I make R3F aware of the custom-controls? 
I want to use them with Drei's TransformControls which automatically disables the default controls if they were set with 'makedefault' property.

I've tried already setting it with useThree -> set() but it doesn't seem to be working.

**Comment by yomotsu** [comment]
Thanks for your report. However, I think you'd be better off asking in the R3D repository.

**Comment by yomotsu** [comment]
Closing due to lack of feedback.

**Comment by makc** [comment]
maybe [this](https://codeworkshop.dev/blog/2020-04-03-adding-orbit-controls-to-react-three-fiber/) still works

**Comment by drcmda** [comment]
here's a running example: https://codesandbox.io/s/yomotsu-camera-controls-febus

cc doesn't need much, just the install and update every frame:

```jsx
import { Canvas, extend, useFrame, useThree } from '@react-three/fiber'
import CameraControls from 'camera-controls'

CameraControls.install({ THREE })
extend({ CameraControls })

function Controls() {
  const ref = useRef()
  const camera = useThree((state) => state.camera)
  const gl = useThree((state) => state.gl)
  useFrame((state, delta) => ref.current.update(delta))
  return <cameraControls ref={ref} args={[camera, gl.domElement]} />
}
```
