### ISSUE TITLE
How do I make an object look the same size when switching between an orthogonal camera and a perspective camera

### ISSUE THREAD

**Issue by yuehaozeng** [yomotsu/camera-controls#326]
Using position.copy() does not change the distance between the camera and the object when switching cameras.

**Comment by yuehaozeng** [comment]
For example: https://codesandbox.io/s/loving-https-y7sco9?file=/src/App.js

**Comment by yomotsu** [comment]
Sorry, I don't get your point...🥲
Please use the issue template.
