### ISSUE TITLE
How to keep the view when switching the camera 

### ISSUE THREAD

**Issue by yuehaozeng** [yomotsu/camera-controls#327]
### Is your feature request related to a problem? Please describe.

I have two cameras ( OrthographicCamera and PerspectiveCamera ) in my scene and I need to keep the same view when I switch cameras.

### Additional context

https://user-images.githubusercontent.com/115784721/206627622-ba7b771f-77c8-4218-9990-1e5df9d2a85b.mp4

**Comment by yuehaozeng** [comment]
I've already solved the problem. I used the camera.position.copy() and cameraControl.dollyTo() to solve the problem

**Comment by yomotsu** [comment]
Sorry for the delay, and good to hear that😊
Keep up the good work!

Let me close this issue.
