### ISSUE TITLE
How can I bring up the camera control like sketchfab, thank you! I saw that there are many parameters, and I tried to adjust it, but there was no such effect as sketchfab controlling the camera.

### ISSUE THREAD

**Issue by ezewu** [yomotsu/camera-controls#328]
How can I bring up the camera control like sketchfab, thank you! I saw that there are many parameters, and I tried to adjust it, but there was no such effect as sketchfab controlling the camera.

**Comment by yomotsu** [comment]
Sorry, I can't help with building your application...
I think you could research a bit more.
If you find missing features on camera-controls, please open a feature request. I will consider that then.

**Comment by ezewu** [comment]
OK, thanks

**Comment by yomotsu** [comment]
Thanks for your understanding🙇‍♂️
Let me close this issue.
