### ISSUE TITLE
Zoom in and zoom out with damping

### ISSUE THREAD

**Issue by ezewu** [yomotsu/camera-controls#329]
### Is your feature request related to a problem? Please describe.

Zoom in and zoom out with damping

### Describe the solution you'd like

The zoom-in and zoom-out camera on the mobile phone and the computer has a damping function

### Additional context

Same requirements as the author of this issue            https://github.com/mrdoob/three.js/issues/13080

**Comment by yomotsu** [comment]
Thanks for your feature request.
Actually, zoom already has a smooth move option.
Set `true` to the 2nd argument of `zoom()` and `zoomTo()` makes the camera movent smoothly.

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
