### ISSUE TITLE
dispatchEvent needs more returned value

### ISSUE THREAD

**Issue by Dod-Annie** [yomotsu/camera-controls#33]
camera-controls dispatchEvent provides some returned values as {type:'xxx',originalEvent:event}.I am making a viewcube to control my model.so I need more values such as "phi,theta . . ." to support me to control the viewcube's camera.

**Comment by yomotsu** [comment]
How about adding setters to get `phi`, `theta` or others?

e.g:
```js
cameraControls.addEventListener( 'change', () => {
  const phi = cameraControls.phi;
  ...
} );
```

**Comment by yomotsu** [comment]
Now the lib has getters of them.
Closing this issue.
