### ISSUE TITLE
Touch-Rotate like Google Maps

### ISSUE THREAD

**Issue by mihkuno** [yomotsu/camera-controls#330]
### Is your feature request related to a problem? Please describe.

_touches.two: ACTION.TOUCH_DOLLY_ROTATE_ - requires both fingers to move in the same horizontal direction in order to rotate.

- rotating with two fingers going around in a circle is the common way. 

### Describe the solution you'd like

Add another option to rotate the camera with both fingers going in a circle like the video shown below.

Expected Behavior:

https://user-images.githubusercontent.com/26486389/208478416-b9885563-630c-49c6-bddc-f4eb233021cc.mp4

Available Options:

https://user-images.githubusercontent.com/26486389/208484341-d74525a0-7387-4a41-9c28-5462edc110d0.mp4

### Describe alternatives you've considered

I just recently started working with threejs.. abstracting 3d math.. how the library works internally is pretty complicated for me  @_@

### Additional context

People who often rotate images in their gallery would get confused rotating the camera control using the current available option.

I'm using the library to render and explore someone else's blender made university campus map on a website for others to see. Unfortunately, some people who have used it got confused rotating the map in their phone. At the mean time I just added a tutorial overlay.

I really appreciate your help on this :)

**Comment by yomotsu** [comment]
I appreciate your suggestion! That might be expected for some applications.
However, camera-controls is focus on orbit rotation control, as described in the readme:
https://github.com/yomotsu/camera-controls#orbit-rotations

I think it's better to make another camera controls lib (or might be already exists)

**Comment by JPBotelho** [comment]
I am also looking for something like this, were you able to find another library?
