### ISSUE TITLE
What is the easing function that is used with the damping ratio to tween between camera LookAts?

### ISSUE THREAD

**Issue by kitaedesigns** [yomotsu/camera-controls#333]
### Is your feature request related to a problem? Please describe.

It seems that there's a particular type of easing being applied along with the damping ratio for LookAt, it would be great to know and be able to change what that easing is as it seems to be affected drastically by different damping ratio values. Please see the video link for an example. But when damping ratio is very low, like 0.1, the time it takes for the LookAt to complete the end of its tween is much longer. It seems like it's an EaseOut function right now. 

[](https://www.loom.com/share/ed26df37a81d49988b9719da29566f56)

CODE

position_tween = new TWEEN.Tween({x:camera.position.x,y:camera.position.y,z:camera.position.z}).to({
		x: moments[i].position.position.x,
		y: moments[i].position.position.y,
		z: moments[i].position.position.z
	}, params.animationTime*1000)
	.onUpdate(function(object){
		console.log(object)
		cameraControls.setLookAt( object.x, object.y, object.z, moments[i].target.position.x, moments[i].target.position.y, moments[i].target.position.z, true )
	})
	.start()

### Describe the solution you'd like

We are using tween.js to tween the position but being able to change the LookAt easing between cameras would be very helpful.  Something like EaseInOut or the ability to change that easing function would be preferable.

**Comment by kitaedesigns** [comment]
https://www.loom.com/share/ed26df37a81d49988b9719da29566f56

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
Actually, it is not easing. it is damping, is used [here](https://github.com/yomotsu/camera-controls/blob/44a88ba913137c58b90ee2d33f7109b1a26b9ad6/src/CameraControls.ts#L2199).

For more details about damping factor, please check the [docs](https://github.com/yomotsu/camera-controls#properties).
If you wish to apply an easing, please check [the easing example](https://yomotsu.github.io/camera-controls/examples/easing.html)

**Comment by kitaedesigns** [comment]
Yes, we've been playing with the damping ratio. If we want to use easing for the LookAt with tween.js instead of the damping ratio is that possible? We put the Damping Ratio on a slider and at lower values, there's too much damping at the end of the LookAt animations, they take very long to complete. I am realizing now that Damping Ratio mimics the physics of a spring so the beginning of the animation will always be much faster than the end.

**Comment by yomotsu** [comment]
You can't use damping and easing at the same time.

Technically possible. While using easing, you need to **disable the transition option** of camera-contols's methods, like [the easing example](https://yomotsu.github.io/camera-controls/examples/easing.html) I mentioned. Also, you don't need the change damping factor value.

**Comment by kitaedesigns** [comment]
Ok thank you, will try and play with damping more then.

**Comment by yomotsu** [comment]
I think this has been solved.
Let me close this issue.
