### ISSUE TITLE
`setTarget` does not take `minPolarAngle` and `maxPolarAngle` into account

### ISSUE THREAD

**Issue by virgilbugnariu** [yomotsu/camera-controls#335]
### Describe the bug

I'm not sure this is a bug or the indented behaviour. The fact that the camera jumps immediately after you start orbiting makes me think that this is not the intended behaviour.

I was able to poke around and came up with a fix but before I submit a PR I wanted to discuss whether this is the right approach. In my situation it works as expected.

### To Reproduce

I have prepared a codesandbox to better visualise the issue: https://codesandbox.io/s/react-three-fiber-camera-controls-forked-i1zysn?file=/src/App.tsx

* The first issue I saw when trying to set up the codesandbox was that min/max polar angle is not set initially and is only applied when you start to orbit. While this is not an issue on my side, maybe it's worth mentioning this as well.

1. Orbit around a bit in order to overcome the above mentioned issue.
2. Press the `set target to 1,1,1` button. 
3. The target is changed as expected, however if you pay attention when you start to orbit around the target, it will jump so that the min/max polar angle constraints are applied.

### Live example

https://codesandbox.io/s/react-three-fiber-camera-controls-forked-i1zysn?file=/src/App.tsx

### Expected behavior

I expect these constraints to be taken into consideration even when the target has changed. 

The following changes did the trick:

```typescript
setLookAt(
  positionX: number, positionY: number, positionZ: number,
  targetX: number, targetY: number, targetZ: number,
  enableTransition: boolean = false,
): Promise<void> {
  const target = _v3B.set( targetX, targetY, targetZ );
  const position = _v3A.set( positionX, positionY, positionZ );
  
  this._targetEnd.copy( target );
  this._sphericalEnd.setFromVector3( position.sub( target ).applyQuaternion( this._yAxisUpSpace ) );
  
  // Adding these two lines fixed the issue. The same approach is used in the `rotateTo` method.
  this._sphericalEnd.phi = THREE.MathUtils.clamp( this.polarAngle, this.minPolarAngle, this.maxPolarAngle );
  
  this.normalizeRotations();
  
  this._needsUpdate = true;
// ...
}
```

**Comment by yomotsu** [comment]
Thank you for your detailed report. the example and code were beneficial.

> min/max polar angle is not set initially

That's right! The initial `polarAngle` should be changed in the constructor( or right before the first `.update()` ) if min or max is set.

Regarding `setTarget()`, I think your approach is correct. However, I have a concern that some users may expect `setLookAt()` should exactly set the target position and the camera position regardless of settings.

Can we do the fix in `setTarget()`, like the one below?

```diff
	setTarget( targetX: number, targetY: number, targetZ: number, enableTransition: boolean = false ): Promise<void> {

		const pos = this.getPosition( _v3A );
- 		return this.setLookAt(
+ 		const promise this.setLookAt(
			pos.x, pos.y, pos.z,
			targetX, targetY, targetZ,
			enableTransition,
		);
+ 		// see https://github.com/yomotsu/camera-controls/issues/335
+ 		this._sphericalEnd.phi = THREE.MathUtils.clamp( this.polarAngle, this.minPolarAngle, this.maxPolarAngle );
+ 		return promise;

	}
```

**Comment by virgilbugnariu** [comment]
Moving it into `setTarget` works for me.
I've updated my fork and I'll submit the PR.

Thank you :)
