### ISSUE TITLE
Controls are disabled with Drei `<Html/>` component

### ISSUE THREAD

**Issue by vincentdchn** [yomotsu/camera-controls#337]
### Describe the bug

First of all, thank you for the library ! 

I've found a bug when using `<Html/>` Drei component. It seems controls is disabled or something. 
I don't think it's an issue related to Drei because OrbitControls still works with `<Html/>` component. 

Any ideas ? 

### To Reproduce

1. Go to the codesandbox link
2. You can move the camera
3. Click on the `toggle occlude` button
4. You can't move the camera with the mouse but still can with the `rotate theta 45deg` button

### Live example

https://codesandbox.io/s/react-three-fiber-camera-controls-forked-re42do?file=/src/App.tsx

### Expected behavior

The camera should continue to be usable with drag event.

### Screenshots or Video

https://user-images.githubusercontent.com/78725068/213728568-3918cd20-2e2c-4536-9aae-8fda93551711.mov

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by yomotsu** [comment]
That is an intended behavior.
If you wish to disable the button, please set disable attribute to the button manually.

**Comment by yomotsu** [comment]
That is an intended behavior.
Mouse events are blocked by the covered div element.
Try changing the 2nd argument of CameraControls constructor to be an ancestor element such as `<body>`.

**Comment by vincentdchn** [comment]
Thanks for your reply. 

So I changed this : 

``` typescript
export const CameraControls = forwardRef<CameraControlsDefault, unknown>((_, ref) => {

	const cameraControls = useRef<CameraControlsDefault | null>(null);
	const camera = useThree((state) => state.camera);
	const renderer = useThree((state) => state.gl);

	useFrame((_, delta) => cameraControls.current?.update(delta));
	useEffect(() => () => cameraControls.current?.dispose(), []);

	return (
		<cameraControlsDefault
			ref={mergeRefs<CameraControlsDefault>(cameraControls, ref)}
			args={[camera, renderer.domElement]}
		/>
	);
});
```

into this : 
``` typescript
export const CameraControls = forwardRef<CameraControlsDefault, unknown>((_, ref) => {

	const cameraControls = useRef<CameraControlsDefault | null>(null);
	const camera = useThree((state) => state.camera);
	const body = document.body;

	useFrame((_, delta) => cameraControls.current?.update(delta));
	useEffect(() => () => cameraControls.current?.dispose(), []);

	return <cameraControlsDefault ref={mergeRefs<CameraControlsDefault>(cameraControls, ref)} args={[camera, body]} />;
});
```

And it seems to be working, thanks ! 
Do you have any explanation why we need to pass this array with a DOMElement inside ?

**Comment by yomotsu** [comment]
Please read the [documentation](https://github.com/yomotsu/camera-controls#constructor) or [source code](https://github.com/yomotsu/camera-controls/blob/dev/src/CameraControls.ts#L398-L405)

<img width="721" alt="image" src="https://user-images.githubusercontent.com/212837/213822049-da3ee726-fa87-485f-b15f-c618745b1981.png">

**Comment by vincentdchn** [comment]
Damn, you're right. I must have skimmed over that part. Thank you very much for your time.
