### ISSUE TITLE
Truck boundaries limit

### ISSUE THREAD

**Issue by rafaelbuiu** [yomotsu/camera-controls#34]
Hello! Thank you for putting the effort to have this. It is great.

I've been trying to modify it a bit in order to implement bound limits to the **truck** function, but I couldn't find a "nice" way to put it together. I always mess up with something.
 
I am working in a map that needs to be panned within the boundaries oif the model,  but nothing I do does the purpose.

Any tip or advice?

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
Since this is 3D thing and more complicated than 2D, I need more info of your problem.
I'm not sure if I could help, but could you provide more details for it?

**Comment by rafaelbuiu** [comment]
@yomotsu Thanks for replying!
Sure, sorry about that.

I am building a map oriented application that will load a FBX file which is a piece of land that has an end (edge) like you can see in the image below

![fbx-file](https://user-images.githubusercontent.com/6061404/53544459-7f865800-3b3f-11e9-8b7d-e8222b973951.jpg)

I am trying to find a way to limit the truck function in order to always have the model in the viewport, avoiding the overscrolling to out of the model..

I could find a possible solution in the OrbitControls with the following code, but couldn't be able to implement to camera-controls.

```
var newX = this.target.x + pan.x;
var newY = this.target.y + pan.y;
if (newX <= this.maxXPan && newX >= this.minXPan 
        && newY <= this.maxYPan && newY >= this.minYPan) {
    this.target.add( pan );
}
```

Thanks for your help!

**Comment by yomotsu** [comment]
Sorry for the delay.
Originally `camera-controls` was based on `THREE.OrbitControls`, then we added several features. Thus, `camera-controls` has similar one too, but it is called [`this._targetEnd`](https://github.com/yomotsu/camera-controls/blob/master/src/camera-controls.js#L533), as you may already know.

So, I guess you could do the same thing in `camera-controls`.

**Comment by rafaelbuiu** [comment]
@yomotsu that's what I was looking for.. I don't know how i didn't see that before..

I am glad you like it. It will be released in a public website. I will come back here to share the URL for the final application.

I actually had to increment a little bit in order to make it work. Something to submit a PR, maybe?

Adding  the restriction and checking by the position of the object in the scene, I was able to set boundaries for it to be only panned within it.

```
controls.maxTruckX
controls.minTruckY
controls.maxForwardX
controls.minForwardY
```
_PS: There was no need to add it to the update function._

**Comment by yomotsu** [comment]
Glad to hear that. Looking forward to seeing your app 👀

Plus, thanks for the suggestion.
Having boundaries limitation would be nice but it is actually complicated. We must consider Z axis and the dolly distance from the center (`targetEnd`) to the camera, if we add the feature generally.
But PRs are always welcome.

**Comment by yomotsu** [comment]
FYI: @FMS-Cat and I are considering to support basic boundary feature👍

**Comment by rafaelbuiu** [comment]
This is great!! Thank you and @FMS-Cat for the effort..

**Comment by yomotsu** [comment]
@rafaelbuiu 
camera-controls supports boundary feature, huge thanks to @FMS-Cat
Check this example https://yomotsu.github.io/camera-controls/examples/boundary.html

I hope you like it.

**Comment by rafaelbuiu** [comment]
@yomotsu Hello! It took sometime to launch the project but it is finally live. I ended up not using your fix to the problem and using mine solution instead just because of development timings as it was already in approval stages. I hope you like it!

[https://dwtc.com/en/neighbourhood-map](https://dwtc.com/en/neighbourhood-map)
