### ISSUE TITLE
move from lerp to unity damp?

### ISSUE THREAD

**Issue by drcmda** [yomotsu/camera-controls#340]
### Is your feature request related to a problem? Please describe.

lerp has a couple of problems, it can under circumstance appear jerky, it doesn't carry velocity and is as such not interruptible, and it doesn't have maxVelocity to anticipate long distances.

unit damp solves all of these: https://github.com/pmndrs/maath#easing it is also very comfortable to use.

a couple of use cases:

- point a -> b is only, say, 5 units apart, looks great. but a -> c is 100 units apart, and it suddenly races there there with huge frame skips. **solution**: damp has maxVelocity, it would limit the amount of units it can travel per second always ensuring smooth movement.

- it moves from point a -> b, suddenly in the middle of it the user interrupts and wants to move to point d, lerp will now stop dead and then race over there. **solution**: with damp each animation has velocity and momentum, breaking midway and moving somewhere else will lead to inertia. imagine throwing out a sling and pulling it back in the real world, it won't screech to complete halt and suddenly move backwards. it will stretch out some more until reach inertia, then move back. damp uses an approximation for performance reason, it is not a real physics sim.

### How?

if you would like to consider it, we use maath as a math kitchen sink, but you could inline the functions if you don't want a dependency. but let's assume the dependency:

```diff
import { easing } from 'maath'

- someVec.lerp(someOtherVec, lerpRatio)
+ easing.lerp3(someVec, someOtherVec, timeInSeconds, delta, optionalMaxVelocity, optionalEasing)
```

**Comment by yomotsu** [comment]
Thanks for your suggestion.
So, cameraControls's methods with the [maath-damp](https://github.com/pmndrs/maath/blob/90317077d86b6aca9a5a5708bd15007b4c89c7c9/packages/maath/src/easing.ts#L29) would be like:
`cameraControls.rotate( angleInRadian, smoothTimeInNumber )`?

I considered that deeply, however I have some concerns.
Could we discuss the following situations?

- What if I run `cameraControls.rotate( deg30, time10sec )` 3 times within 1 sec?
  Should it be at 90 deg?
- What if I run `cameraControls.rotate( Math.PI, time10sec )` and `cameraControls.rotate( - Math.PI, time10sec )` at the same time?
  Should both damps finish immediately?
- What if I run `cameraControls.rotate( Math.PI, time10sec )` and `cameraControls.rotate( - Math.PI, time20sec )` at the same time?
  Should the first 10sec will move slowly, then last another 10 sec should head to -180 deg?
- What if I run `cameraControls.rotate( deg30, time10sec )` then start mouse dragging right after that?
  Should the rotate be stopped?
- Could we handle complex mouse dragging and wheels?

And can we do the belows with maath-damp?

**Comment by drcmda** [comment]
damp per se would not change how lerp works, it just does it a little better but mathematically lerp and damp both come to the same conclusion or result. the main difference between them is just that damp stores velocity, so it has inertia.

i would expect cameraControls.rotate(deg30, time10sec) with damp to have the same outcome as with lerp.

**Comment by yomotsu** [comment]
I understand. In fact, we already have [a tween example](https://yomotsu.github.io/camera-controls/examples/easing.html).
However, I don't know how to combine multiple tweens to be one, as I mentioned https://github.com/yomotsu/camera-controls/issues/340#issuecomment-1401304944

Is there any way to do that...?

**Comment by yomotsu** [comment]
Thanks for clarifying. I kinda understand, and I agree with you that we should use smoothDamp.
It may take some time but worth changing.

Can we use [simpler smoothDamp](https://gist.github.com/stakira/1ac34b257e219c1f5c36376b9d7fba5a) function?
Because camera-controls only [changes numbers internally](https://github.com/yomotsu/camera-controls/blob/2a6517a2a0e1070943a8e72ba6e40d032840448f/src/CameraControls.ts#L2212-L2239), but not for color and other types.

**Comment by yomotsu** [comment]
So far, it works well😊
<video src="https://user-images.githubusercontent.com/212837/214361382-e2ba4a9b-d037-4991-bddf-df712c3e876b.mp4"></video>

**Comment by drcmda** [comment]
oh that was really quick!

**Comment by yomotsu** [comment]
Almost there!

🔽 The latest example is available at the link below
Try changing `smoothTime`, `draggingSmoothTime`, `maxSpeed` via the dev tool console.
https://raw.githack.com/yomotsu/camera-controls/dev/examples/basic.html

![image](https://user-images.githubusercontent.com/212837/214631225-42abdbd6-67d3-4db3-8ed8-4623bdd29146.png)

**Comment by abernier** [comment]
wow I've tested it, I don't know if I'm biased, but it feels so much smoother!

**Comment by yomotsu** [comment]
Thank you for checking it!
Really helpful, because I have no testers🥲

I feel more confident now.

**Comment by yomotsu** [comment]
@drcmda @abernier 

camera-controls now uses SmoothDamp for its transition.
This change is not compatible with previous versions, thus new camera-contols has been published as [v2.0.0](https://github.com/yomotsu/camera-controls/releases/tag/v2.0.0)
already available on NPM and others.

**Comment by abernier** [comment]
I've just tested the "basic" demo, this is insane how smooth it is! Congrats Yomotsu 🙌🏻 I also tried "stress-testing" the buttons `rotate theta 45 deg` and it behaves flawlessly (not choppy/jerky at all)

I will update the `CameraControls` drei component soon with this last version

**Comment by abernier** [comment]
https://github.com/pmndrs/drei/pull/1253

**Comment by yomotsu** [comment]
Let me close this issue.
SmoothDamp has been supported since v2, as well as in drei.

Thanks again for the feature request.
