### ISSUE TITLE
set position bugged after 1.37.5

### ISSUE THREAD

**Issue by VegarRingdalAibel** [yomotsu/camera-controls#345]
### Describe the bug

Hi

Tried to create sample showing setPosition is broken after 1.37.5

# To Reproduce

See animated gifs

# Live example

https://codesandbox.io/s/musing-mccarthy-zqneho?file=/src/index.js

You can switch between version here
![image](https://user-images.githubusercontent.com/94840334/214896018-bf9a5830-da6d-462f-8988-6f377733931e.png)

# Expected behavior

To use correct position and target, not using the offset its doing now after 1.37.5

### Screenshots or Video

# Bugged behavior

Bugged: I save 4 target/positions, but when I move camera, it stays in same position and not the one I saved

![chrome_aciXKCEYKi](https://user-images.githubusercontent.com/94840334/214896254-a9963fda-794c-469c-a883-aa140a7ffd63.gif)

# Expected behavior

![chrome_vHM5CGk2jY](https://user-images.githubusercontent.com/94840334/214896564-e45cd86c-9dfa-4fe2-be15-ffedd908afb2.gif)

### Device

Desktop

### OS

Windows

### Browser

Chrome

**Comment by yomotsu** [comment]
Both `setTarget()` and `setPosition()` are alias of `setLookAt()` and you are calling the same function at the same time eventually.
see: https://github.com/yomotsu/camera-controls/blob/2014f469a5de866035e2bca206dd2b4278b89c7c/src/CameraControls.ts#L1909-L1950

Thus, you are overwriting the first one with the second one. Therefore, `setPosition()` is not working in your code.
What about using `setLookAt()` instead?

**Comment by VegarRingdalAibel** [comment]
setPosition worked perfectly combined with setTarget in 1.37.5 so I though it was a bug. 😄 
Ill give the setLookAt a try, from the code sample above it looks to solve my issue

**Comment by yomotsu** [comment]
> I though it was a bug
TBH...I thought so...
But according to the code, the current version is more expected behavior.

**Comment by VegarRingdalAibel** [comment]
thx
