### ISSUE TITLE
Is it possible to implement lookAt() using cameraControls in the first person?

### ISSUE THREAD

**Issue by VLASSSAR** [yomotsu/camera-controls#348]
### Is your feature request related to a problem? Please describe.

Hi yomotsu! I recently encountered the problem of rotating the camera in a certain direction. I want that when you click on a certain area in the scene, the camera turns to the object in first person mode. As I understand it, the rotate() function allows you to rotate by degrees, but this option does not suit me. SetTarget() turns the camera to the desired object, but also completely changes the orbit of the camera, which also does not suit me. How is it possible to change the camera look in the first person without changing the orbit?

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
FPS mode is actually a bonus feature and not really supported.
Basically, camera-controls is an orbit-rotation-controls see https://github.com/yomotsu/camera-controls#orbit-rotations
and FPS is like 0 distance orbit.

If you wish "look from camera to the point", I encourage you to make it your own with some math.
`Math.atan()` should help in your case I think.

**Comment by yomotsu** [comment]
I will add a new method likely called `lookPoint( x, y, z )`;

Looks good?
<video src="https://user-images.githubusercontent.com/212837/215112459-fa7eecab-af4e-483d-af59-eb5b2e7009fb.mp4"></video>

```ts
lookPoint( x: number, y: number, z: number, enableTransition: boolean = false ): Promise<void> {

	const point = _v3A.set( x, y, z );
	const direction = point.sub( this._targetEnd ).normalize();
	const position = direction.multiplyScalar( - this._sphericalEnd.radius );
	return this.setPosition( position.x, position.y, position.z, enableTransition );

}
```

**Comment by VLASSSAR** [comment]
OMG, MAN! IT LOOKS AMAZING! Thank you very much! I really apprectiate your help!!!

**Comment by yomotsu** [comment]
Thanks for the request too.

[`lookInDirectionOf()`](https://github.com/yomotsu/camera-controls#lookindirectionof-x-y-z-enabletransition-) has been added with camera-controls v2.0.0.
See the changes https://github.com/yomotsu/camera-controls/releases/tag/v2.0.0
Available on NPM as well.

let me close the issue

**Comment by matrix-root** [comment]
Dear @yomotsu, thanks for your library!

Could you help how can I use `lookInDirectionOf()` in case of updating target position each frame?

In shorts, I have point which moving each frame via custom path and I want camera to follow that point and look at that from "back"

I achieved following with `.moveTo(x, y, z, true)` on each frame (not sure is it ok for performance to call that each frame), but if I'm trying to follow it with rotation via `lookInDirectionOf` before updating position - I'll got strange behaviour - camera just start going to the sky

```
export default function CameraController({root}) {
  const ref = useRef<CameraControls>(null)
  const position = new THREE.Vector3
  useFrame(() => {
    root.getWorldPosition(position) // Getting position of my point
    const {x, y, z} = position
    ref.current.lookInDirectionOf(x, y, z) // not sure is it correct
    ref.current.moveTo(x, y + 0.7, z, true)
  })
  return <CameraControls ref={ref} smoothTime={0.1} />
}
```
