### ISSUE TITLE
Resizing the window crashes the render

### ISSUE THREAD

**Issue by rafaelbuiu** [yomotsu/camera-controls#35]
Is there any reason why resizing the window cause the crash of the render?

I noticed that it is also not possible to resize the window on your examples.

**Comment by yomotsu** [comment]
I can't reproduce the problem.
Do you mind sharing a simple example on jsfiddle or so?

**Comment by rafaelbuiu** [comment]
@yomotsu Hi again! We are about to release the project but I am still facing this issue. 
When I resize the window (or rotate the phone) and the window resize event is triggered the render is crashed not showing anything else in the scene.
What I could notice is that it happens when I run the camera.updateProjectionMatrix()
Any ideias? 
Thanks in advance

**Comment by yomotsu** [comment]
How do I reproduce the problem?
Can you share a simple example?
