### ISSUE TITLE
truck/pan with trackpad only

### ISSUE THREAD

**Issue by abernier** [yomotsu/camera-controls#353]
Using a macbook without a mouse, it seems not possible to pan/truck.

OrbitControls supports ctrl+left_click (which corresponds to a right_click), for that.

What do you think of this for camera-controls?

**Comment by yomotsu** [comment]
CC support 2-fingers-drag to pan its position, and it's configurable.
https://yomotsu.github.io/camera-controls/examples/config.html

That is the same as OC (because I referred to OC at that time).
https://threejs.org/examples/#misc_controls_orbit

OC also supports key combinations which I didn't know...
It seems that was added last year...
https://github.com/mrdoob/three.js/commit/4f23d857b15b40fd5afd8a6bccaf761812efd70e

**Comment by abernier** [comment]
> OC also supports key combinations which I didn't know... It seems that was added last year... [mrdoob/three.js@4f23d85](https://github.com/mrdoob/three.js/commit/4f23d857b15b40fd5afd8a6bccaf761812efd70e)

Oh yes, this is the one! It would be useful for users that only have a trackpad (without physical right_click)

**Comment by yomotsu** [comment]
Right-click is mapped to two-finger tap on a macbook trackpad.
https://github.com/yomotsu/camera-controls/blob/8ffa364ced022befa2549ff9eb9ae223cc2f4774/src/CameraControls.ts#L630-L634

We also provide a "drag + key" example.
Although it's not simple, more configurable in userland I think.
https://yomotsu.github.io/camera-controls/examples/mouse-drag-with-modifier-keys.html

**Comment by abernier** [comment]
> Right-click is mapped to two-finger tap on a macbook trackpad.

omg, never realized I could click the trackpad with 2 fingers WHILE draging and maintaining those 2 fingers pressed 🤯

**Comment by abernier** [comment]
> We also provide a "drag + key" example.
> Although it's not simple, more configurable in userland I think.
> https://yomotsu.github.io/camera-controls/examples/mouse-drag-with-modifier-keys.html

this is great, closing this false-issue

**Comment by yomotsu** [comment]
Thank you for understanding😊
Looking forward to seeing your next feedback.
