### ISSUE TITLE
setPosition does not set position

### ISSUE THREAD

**Issue by stam** [yomotsu/camera-controls#368]
### Describe the bug

Both setPosition and setLookAt don't reliably set a camera position.

### To Reproduce

1. Go to https://codesandbox.io/s/camera-controls-setposition-7dl2e3?file=/src/index.js
2. Click the "Move camera" button
3. Truck the camera position using middle mouse button
4. Click the "Move camera" button again
5. Location after 4 is not the same location after 2

### Code

```js
const newCameraPosition = new Vector3(1, 2, 3);

cameraControls.setLookAt(
    newCameraPosition.x,
    newCameraPosition.y,
    newCameraPosition.z,
    0,
    0,
    0,
    false
  );
```

### Live example

https://codesandbox.io/s/camera-controls-setposition-7dl2e3?file=/src/index.js:3164-3214

### Expected behavior

Setposition after 2 and 4 use the same vector3, so they should use the same camera position

**Comment by yomotsu** [comment]
Thanks for your report.
Actually, it is caused by clicking the green box.
If you don't click the green box, I think the problem never happens.

I think that is the same as a known issue: focalOffset( setOrbitPoint ) breaks setLookAt.
https://github.com/yomotsu/camera-controls/issues/303

**Comment by stam** [comment]
Hey, thanks for a pointer in the right direction, but setFocalOffset 0,0,0 doesn't solve my issue. I'm building a feature which saves the camera position and restores it.

If you save a cameraposition (with focaloffset), then restore that cameraposition by setting focalOffset (0,0,0), it's not going to be the same cameraposition as the one you saved.

Is there a way to get the actualCameraPosition which takes the focalOffset into account?

**Comment by yomotsu** [comment]
focalOffset is like a post process.
The actual position cannot be got as long as using focalOffset...
Unfortunately, problems caused by focalOffset can't be fixed I think...

**Comment by yomotsu** [comment]
Even if we could have the _actualCameraPosition_ and move the amount of negative _actualCameraPosition_ to collapse, it doesn't move the expected point. Because focalOffset moves to the point right forcibly after the position update.

**Comment by stam** [comment]
Okay, if this is the same bug as 303 I'll close this issue
