### ISSUE TITLE
How to restrict mouse wheel max zoom out

### ISSUE THREAD

**Issue by eric-blue** [yomotsu/camera-controls#371]
### Is your feature request related to a problem? Please describe.

Essentially trying to set an upper limit of how far the user can scroll out via mousewheel/other means. Same goes for zooming in.

### Describe the solution you'd like

just some guidance, I couldn't find an example that did quite what I'm asking.

**Comment by abernier** [comment]
I guess you are probably looking for [`.minDistance`/`.maxDistance`](https://camera-controls.pages.dev/classes/CameraControls#minDistance)

See ex: https://codesandbox.io/s/epic-chaplygin-1pedbd?file=/src/index.js:583-648

**Comment by eric-blue** [comment]
incredible thank you

**Comment by romankoho** [comment]
Hey @abernier thanks for your example. Seems pretty straight forward. Yet I can't get it to work with React three fiber and the camera-controls implementation of react three drei.

```typescript
 <Canvas
      frameloop={'demand'}
      camera={{ position: new THREE.Vector3(10, 2, 10) }}
    >
      <CameraControls
        minZoom={1}
        makeDefault={true}
        minDistance={1}
        maxDistance={5}
        truckSpeed={2}
        dollyToCursor={true}
        infinityDolly={true}
      />
    </Canvas>
```

Do you have an idea what it could be?

https://github.com/user-attachments/assets/3fb9d2f9-733c-4ff2-9338-d2a2f928dc95
