### ISSUE TITLE
Dragging outside the canvas with right-click causes various issues 

### ISSUE THREAD

**Issue by Canpake** [yomotsu/camera-controls#372]
### Describe the bug

When dragging with right-click, if the mouse is released while outside the canvas, a number of issues appear to occur with future camera movement as well as the events reported by the mouse. 

In my case, trucking movement became much slower and would first snap to the position of where the mouse was dragging from. Additionally, `onPointerMove` events also stopped being sent entirely. 

The video attached demonstrates this on the [`basic` ](https://yomotsu.github.io/camera-controls/examples/basic.html) example. Repeatedly performing this action seems to make the effects of this issue more prominent, and it can be seen that the camera rotation and trucking is much slower afterward. 

The `reset` button does not solve this issue; reloading the webpage was the only way I found to resolve this issue.

I originally found this bug in the `CameraControls` component of the `@react/drei` library, but it seems to affect examples outside of React as well.

### To Reproduce

1. Go to any example that uses `camera-controls`
2. Drag with right-click, beginning within the canvas area and releasing outside of it (several times)
3. Try any further mouse dragging actions; they should feel much less responsive.

### Expected behavior

This does not appear happen when dragging with left-click; dragging and releasing the mouse outside the canvas should not impact future behaviour.

### Screenshots or Video

[Video](https://drive.google.com/file/d/1yCAk5-fx3fMrP7j9QLpUWjVTQQYp-_AF/view?usp=share_link)

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by yomotsu** [comment]
Thanks for your report.
I reproduced the problem, and have made a PR to fix it!

**Comment by yomotsu** [comment]
this has been fixed and published.
closing the issue.
