### ISSUE TITLE
Update Orbit while position is in transition

### ISSUE THREAD

**Issue by henriandrade** [yomotsu/camera-controls#376]
### Is your feature request related to a problem? Please describe.

I am trying to create a first person experience, that while the user goes from A to B would be desirable to still allow orbiting without canceling the transition. 

The problem is that orbiting while the transition is active makes the effect change speed, ruining the experience.

Video showing the problem I'm having: https://www.loom.com/share/998b451bf9e0469ba59d99df0c170ee1

### Describe the solution you'd like

A proper solution would be to allow orbiting without interfering on the position transition animation.

### Additional context

```
  useEffect(() => {
    if (!cameraControls || !walkTo) return
    const EPILSON = 1e-6
    const currentPos = cameraControls.getPosition(new THREE.Vector3())
    const fromCurrentToNewPosVec = new THREE.Vector3().subVectors(walkTo, currentPos)
    const distance = fromCurrentToNewPosVec.length()
    const LookTo = walkTo.clone().addScaledVector(fromCurrentToNewPosVec, EPILSON)

    cameraControls.smoothTime = distance / 5
    cameraControls.setLookAt(walkTo.x, 1.75, walkTo.z, LookTo.x, 1.75, LookTo.z, true)

    return () => {
      cameraControls.removeEventListener('update', () => {})
    }
  }, [cameraControls, walkTo])
```

**Comment by yomotsu** [comment]
Unfortunately, that is intended.
both programmable and user-dragging rotations are merged into the same rotation state.
then, camera-controls uses `draggingSmoothTime` to change the rotation state while user-dragging.
copy `smoothTime` to `draggingSmoothTime` may reduce the problem.

**Comment by abernier** [comment]
@henriandrade another approach used in `@react-three/xr` is wrapping the camera in a player object: https://github.com/pmndrs/react-xr/blob/master/src/XR.tsx#L159

It's like someone with a gopro. `player` can move and the `camera` rotate.

**Comment by henriandrade** [comment]
@yomotsu I understand that, but would not be wise to differentiate position transformation from lookTo transformation?

I've tested many solutions, unfortunately none solved this case.

**Comment by yomotsu** [comment]
> player and rotate the camera independently

I think so.

You don't really need camera-controls smooth transition for the player's position movement.
You can consider using a playerControler or a tween lib for fixed position tween.
see the following example. (this one disabled user camera rotation, but can enable it)
https://yomotsu.github.io/camera-controls/examples/path-animation.html

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
