### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by abernier** [yomotsu/camera-controls#379]
### Is your feature request related to a problem? Please describe.

Since documentation is now deployed with Github Pages (beta) since https://github.com/yomotsu/camera-controls/pull/365 we may not need the Cloudflare build that is now failing:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/76580/220321905-0e58ae33-f614-41ba-9485-6ccacc05e605.png">

@yomotsu what about disabling it?

**Comment by yomotsu** [comment]
Ah, that's right.
The error is because of node.js version (we recently updated the node version from v16 to v18), but we must get rid of Cloudflare anyway.

**Comment by yomotsu** [comment]
deleted the Cloudflare pages project.
