### ISSUE TITLE
CC homepage link

### ISSUE THREAD

**Issue by abernier** [yomotsu/camera-controls#384]
### Is your feature request related to a problem? Please describe.

Since documentation is now generated with GitHub Pages (beta), we could use this to display the link to the doc:
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/76580/222956248-b0bd5b03-fa52-462a-a9ef-e911a5df4cab.png">

**Comment by yomotsu** [comment]
Sorry for the delay. And thank you for your advice as usual.
I just set the homepage!
