### ISSUE TITLE
Switch between the orthogonal camera or perspective camera after initializing the instance

### ISSUE THREAD

**Issue by GhostCatcg** [yomotsu/camera-controls#386]
### Is your feature request related to a problem? Please describe.

Currently, I want to make a similar view-helper to the upper right corner of blender. When switching to the front view, I need to change the camera to the orthogonal camera, but how do I change the camera in the space after controller instantiation?

### Describe the solution you'd like

Switch camera function

### Additional context

![blender](https://user-images.githubusercontent.com/33864029/223613965-1e6d56a7-2e19-4655-a11f-09b9a9694989.jpg)

**Comment by yomotsu** [comment]
Thanks for using camera-controls.

I think it's technically possible. make both Perspective and Ortho camera instances in your app, then switch between them with `cameraControls.camera`, then use the camera in `renderer.render()`.

Altho I can't give a detailed answer but hope this helps.
(If you wish more dedicated support, consider becoming a sponsor)
