### ISSUE TITLE
Controls for changing default target position that the camera orbits around

### ISSUE THREAD

**Issue by kitaedesigns** [yomotsu/camera-controls#388]
### Is your feature request related to a problem? Please describe.

The camera's orbit target seems to default to a certain location in front of the camera but this variable seems inaccessible as it is buried in CameraControls.ts if I am not mistaken.

### Describe the solution you'd like

 It would be useful to expose this publicly to make navigation of the camera easier and more flexible for different scenarios, i.e. switching between first-person vs third-person, vs object in scene to orbit around etc.

**Comment by yomotsu** [comment]
Do you mean `.getTarget()` and `.setTarget()`?

**Comment by kitaedesigns** [comment]
I mean specifically for the default camera target settings like in keyboard.html where the orbit target is some arbitrary unit in front of the camera

**Comment by yomotsu** [comment]
Sorry for the delay, and I still don't get the point of "target".
as explained [here](https://github.com/yomotsu/camera-controls#orbit-rotations), the orbit revolves around the target.
If you wish to change the distance to the target, you can change it with `.distance` or `.dollyTo( distance )`.

**Comment by kitaedesigns** [comment]
So if I wanted to make the camera act like a First-Person camera where it rotates from its POV, I would just change .distance to 0? I'm essentially trying to make the keyboard.html example be like a First-Person navigation game

**Comment by yomotsu** [comment]
Closing due to lack of feedback.

**Comment by zrooda** [comment]
I'm using this with `@react-three/drei` and the absence of default target property makes it pretty difficult to avoid sometimes seeing the camera twitch from its default [0,0,0] target position to a different position you set with `setPosition` as soon as the instance is available. IMO the issue title is real even though the description is something else.
