### ISSUE TITLE
fitToBox doesn't work correctly when camera up vector is not (0, 1, 0)

### ISSUE THREAD

**Issue by smolentsevdn** [yomotsu/camera-controls#389]
### Describe the bug

After changing the camera up vector and calling updateCameraUp(), fitToBox stops working correctly.
Moreover, it works correctly with BoxGeometry and incorrectly with ExtrudeGeometry.
I prepared a small example to demonstrate this problem.
I found a workaround, but maybe this is the expected behavior?

### To Reproduce

1. Go to provided example on codesandbox.io
2. Click on fitToBox button, works correctly. Then change up vector to (1,0,0), click fitToBox again.
3. Make sure ExtrudeGeometry is selected as the mesh.

### Live example

https://codesandbox.io/s/purple-https-423uz0?file=/src/App.tsx

### Expected behavior

fitToBox should fit the viewport to the box

### Device

Desktop

### Browser

Chrome

**Comment by yomotsu** [comment]
Thanks for your report.
I reproduced the problem thanks to your working example and I just fixed it.
https://github.com/yomotsu/camera-controls/pull/391
