### ISSUE TITLE
Saving state toJSON and loading fromJSON not as expected

### ISSUE THREAD

**Issue by vincent-azumuta** [yomotsu/camera-controls#390]
### Describe the bug

I am currently using react-three-fiber and cameracontrols. 
I want to store the state for later usage. I'm using the JSON flow to achieve this.

When applying the saved state it does not work as expected. 

### To Reproduce

1. move/dolly/zoom camera
2. save state
3. move/dolly/zoom camera
4. reset

### Code

```js
let lastJson

// save button:
() => lastJson = cameraControlsRef.current?.toJSON()

// reset button
() => cameraControlsRef.current?.fromJSON(lastJson, true)

```
```


### Live example

https://codesandbox.io/s/cameracontrols-basic-forked-7rfu9p

### Expected behavior

Reset the view exactly like the `saveState()` and `reset()` flow

### Screenshots or Video

_No response_

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by yomotsu** [comment]
thanks for your report.
the problem should be fixed by https://github.com/yomotsu/camera-controls/pull/392

**Comment by vincent-azumuta** [comment]
Thank you for the quick reply and solution!

**Comment by vincent-azumuta** [comment]
Hi sorry to reopen but dollying is also not reapplied in the JSON flow.
