### ISSUE TITLE
Minimum and maximum polar angle

### ISSUE THREAD

**Issue by chrislarcombe** [yomotsu/camera-controls#393]
### Describe the bug

Setting the minimum and maximum polar angle does not seem to change behaviour of the controls.

Controls always behave as though min and max are set to 0 and PI (despite minPolarAngle and maxPolarAngle being set differently, for example -Infinity and Infinity).

For azimuth it works fine, but for polar angle setting the min and max does not seem to change anything.

### To Reproduce

Set params: 

minPolarAngle = -Infinity
maxPolarAngle = Infinity

Controls still behave as though min and max are set to 0 and PI.

### Expected behavior

Being able to rotate controls along polar axis infinitely in either direction when min and max polar angle are set to -Infinity and Infinity respectively (as with azimuth).

**Comment by yomotsu** [comment]
thanks for using camera-controls.
actually, that is intended. the range is `0` to `Math.PI` radians.

**Comment by chrislarcombe** [comment]
Thanks for the fast reply! :+1 

In that case I offer this as a feature request/suggestion, to expand the functionality.

Ideally it would be good if it behaved in the same way as the azimuth rotation? (which supports infinity and variable limits).

In my use-case I need to be able to avoid the rotation being blocked, so it can continuously rotate or infinitely rotate... (along the polar axis)... 

Thanks! :+1: :heart:

**Comment by yomotsu** [comment]
https://github.com/yomotsu/camera-controls/issues/385 might be related to your issue.

**Comment by yomotsu** [comment]
Closing due to lack of feedback.

**Comment by ericcirone** [comment]
> Thanks for the fast reply!
> 
> In that case I offer this as a feature request/suggestion, to expand the functionality.
> 
> Ideally it would be good if it behaved in the same way as the azimuth rotation? (which supports infinity and variable limits).
> 
> In my use-case I need to be able to avoid the rotation being blocked, so it can continuously rotate or infinitely rotate... (along the polar axis)...
> 
> Thanks! 👍 ❤️

I would second this.

I just went to add this in my project, changing the min and max Polar angle only to see that it does nothing. It would be great if we were able to use the options.
