### ISSUE TITLE
After restoring state from json, dolly information is lost

### ISSUE THREAD

**Issue by vincent-azumuta** [yomotsu/camera-controls#396]
### Describe the bug

When using the json state saving / restoring flow the dolly position is lost. 

### To Reproduce

1. move/dolly/zoom camera
2. save state
3. move/dolly/zoom camera
4. reset

### Code

```js
let lastJson

// save button:
() => lastJson = cameraControlsRef.current?.toJSON()

// reset button
() => cameraControlsRef.current?.fromJSON(lastJson, true)
```

### Live example

https://codesandbox.io/s/cameracontrols-basic-forked-7rfu9p

### Expected behavior

Reset the view exactly like the `saveState()` and `reset()` flow

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by yomotsu** [comment]
Thanks for your report.
I fixed it in PR https://github.com/yomotsu/camera-controls/pull/398
and will merge this weekend.

**Comment by vincent-azumuta** [comment]
Awesome thanks a lot again
