### ISSUE TITLE
Camera rotation

### ISSUE THREAD

**Issue by GhostCatcg** [yomotsu/camera-controls#402]
### Is your feature request related to a problem? Please describe.

How do you do the rotation of the camera, and how do you apply a matrix to the camera, and you can't operate the camera directly, you have to go through the controller, but the controller doesn't have that way

### Describe the solution you'd like

Can it be manipulated by converting the camera rotation and matrix into position and target points?

**Comment by yomotsu** [comment]
Thanks for using camera-controls.

Sorry, I'm not able to answer questions from all users.
If it is a unique question, I might answer it, but your question seems to be sort of basic.
(Please understand that this is not a well-sponsored project nor a contract work.)

Also, please note that our Issues section is for bug reports or feature requests.

If you require further support, please consider becoming a patron: the "You may get additional support" tier.
