### ISSUE TITLE
Automatically begin pan on mouseover

### ISSUE THREAD

**Issue by mokargas** [yomotsu/camera-controls#404]
### Is your feature request related to a problem? Please describe.

Not sure if this is a feature request or my unfamiliarity with camera-controls.

Basically, the controls seem to require mouse clicks to kick off various modes. For my use cases, I only want panning between a boundary (achieved with setBoundary), but I want panning to be immediately enabled on mouseover rather than click. Is this possible?

**Comment by yomotsu** [comment]
I'm not sure but you can attach `_truckInternal` to your mouse move in user-land for a workaround.

https://github.com/yomotsu/camera-controls/blob/58123bc19643f699c90229bdcfb3df25817ddecd/src/CameraControls.ts#L2938

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
