### ISSUE TITLE
Zoom to Region

### ISSUE THREAD

**Issue by homegrowncoder10** [yomotsu/camera-controls#409]
### Is your feature request related to a problem? Please describe.

I was interested in implementing a "zoom to region" feature similar to that in Blender where you can click and drag on the screen and create a 2d rectangle in screen space. After releasing the mouse the camera would then zoom/dolly to fit that region of the screen. 

I feel like the functionality is really close to allow this, I was considering using the FitToBox or FitToSphere method, but I am unsure of the best way to find the size of the bounding box based off of the screen locations of the rectangle. I've tried projecting the mouse coordinates into world space using the x/y locations with z values of 0/1 to get world space coordinates but that didn't seem to work right.

### Describe the solution you'd like

Binding that allows for a click draw mode to draw a rectangle on screen and have the camera zoom/dolly to that region in space.

### Additional context

Here's a video of the feature in blender.

https://user-images.githubusercontent.com/38308169/235832289-3f591377-5895-411d-8f4a-467761116fb1.mp4

**Comment by yomotsu** [comment]
@homegrowncoder10

Sorry for the long delay...
I've added a new example https://github.com/yomotsu/camera-controls/commit/404110fb201c819bff49e9ececf0cc97468f5175

I hope this is helpful.
→ https://github.com/yomotsu/camera-controls/assets/212837/84f92587-d39e-4e52-bd51-b6aa25015dac

**Comment by yomotsu** [comment]
I think this has been solved with the example code.
Let me close this issue.

**Comment by homegrowncoder10** [comment]
Thank you for taking the time to create the example. It is very helpful. 

If I'm understanding correctly, in your example you are fitting the camera to a rectangle defined in world space. In my implementation I'm trying to create this rectangle based on the user drawing a rectangle in screen space. 

Maybe this is really obvious, but what would you say is the best way to calculate the model space coordinates based on the screen space rectangle? I find that when I project the coordinates of the screen space rectangle into world space I sometimes get unexpected results.

Thank you again for your assistance.

**Comment by yomotsu** [comment]
I think you can use the math in the example code.
Even if the rect is in screen space, that should have 4 projected corners in vector3 in world coordinates.

And sorry I can't answer app-specific questions.
If you really wish, please consider becoming a patron for this project via github sponsors.
