### ISSUE TITLE
Using forward() and resetting orbit point moving to target 

### ISSUE THREAD

**Issue by andrew-mackin** [yomotsu/camera-controls#415]
### Describe the bug

I am trying to select a point on the screen and move to it, with some offset, and orbit around it until a new item was selected. I originally achieved this by using setTarget and setPosition in tandem to move to the area clicked on. However, once I started calling the forward() (or dolly()) methods to move the camera, my orbit point reset. To fix this, I reset the orbit point after I have completed any calls to forward() (or dolly()). However, this causes the "moving" to a new object to behave erratically. 

### To Reproduce

In the live example,
1. Hold the 'w' key to call the foward() method, usually for awhile
2. Double click on a square towards the edge (this is not required but generally gets it to occur more frequently)

### Code
See Live example

### Live example

[Code Sandbox](https://codesandbox.io/s/happy-river-hwou3b?file=/src/index.js)

### Expected behavior

The user should be moved to the position of the 3D area clicked on, zoomed out to some relatively small offset.

### Screenshots or Video

In this video, I double click an object before moving forward using the forward() method. The object is highlighted (for clarity) and I am moved towards it as expected. Then I move using the forward() method a few times to navigate the scene, double click on another object and am thrown forward erratically.

https://github.com/yomotsu/camera-controls/assets/129075800/9285f310-4096-4781-aabe-7a062c5393fc

In the live, example:

https://github.com/yomotsu/camera-controls/assets/129075800/5a92b2ba-81cd-4693-8162-240a8c7d0b6e

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
Would it be possible to provide a simplified working example to just reproduce the problem without any app-specific implementation?

**Comment by andrew-mackin** [comment]
Sure! I've updated the issue with a live example. I also realized that resetting the orbit point is part of what causes the issue.
