### ISSUE TITLE
Set the screen width and height as the boundary

### ISSUE THREAD

**Issue by front-refined** [yomotsu/camera-controls#416]
### Is your feature request related to a problem? Please describe.

https://yomotsu.github.io/camera-controls/examples/boundary.html

This is a great project. :+1: 

I used the boundary function and wanted to realize the screen size as the boundary.  Could you please help to have a look.

:heart:

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
However, this is out-of-scope for the project so far, and sorry, I can't answer app-specific questions from all users.

---

Actually, screen width and height depend on the depth of the scene and the vertical FoV angle of the camera.
You could calculate the width and height at the target depth using

- `Math.tan()`
- half `camera.fov` in radians
- distance between the camera and target depth.

FYI: https://www.google.com/search?q=How+to+calculate+height+in+surveying+with+angle+and+distance

Then get the height of the canvas in WebGL seen unit,

![Untitled-1](https://github.com/yomotsu/camera-controls/assets/212837/37c3164d-f4c6-48b8-a7a7-c41e671064e6)

Then you can get width using the height and `camera.aspect`.

As a result, you will have width and height.

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
