### ISSUE TITLE
Orbit point is lost after dolly to cursor

### ISSUE THREAD

**Issue by AyaHelmy9** [yomotsu/camera-controls#420]
### Describe the bug

I edited the `click-to-set-orbit-point` example to allow dolly to cursor on mouse wheel. After scrolling in/out, the orbit point seems to be lost and I must click on it again for it to take effect.

### To Reproduce

1. Go to [this sandbox](https://codesandbox.io/s/set-orbit-point-zoom-to-cursor-d8tkt2)
2. Select an orbit point
3. Dolly to cursor using mouse wheel
4. Rotate - orbit point is not respected

### Live example

https://codesandbox.io/s/set-orbit-point-zoom-to-cursor-d8tkt2

### Expected behavior

Orbit point is maintained after dolly to cursor action

**Comment by yomotsu** [comment]
Thanks for your report.
I think it's actually intended behavior.
Dolly to cursor will change the target which is the orbit center.
You need to set the orbit point right after dolly control via an event callback or so.
