### ISSUE TITLE
Question: did 2.3.5 or higher bring breaking changes?

### ISSUE THREAD

**Issue by VegarRingdalAibel** [yomotsu/camera-controls#425]
### Describe the bug

Did last version bring breaking changes?
Looks like like setTarget is behaving really weird compared to before after using scrollwheel.

Was on 2.3.4 and everything was working great.

Im using infinityDolly and dollyToCursor.

### To Reproduce

is question only

### Code

```js
is question only
```

### Live example

is question only

### Expected behavior

is question only

### Screenshots or Video

is question only

**Comment by VegarRingdalAibel** [comment]
Ill try and make a bug issue within next week.

**Comment by yomotsu** [comment]
It seems, `setTarget()` has been broken since [v1.37.6](https://github.com/yomotsu/camera-controls/releases/tag/v1.37.6)
it works [v1.37.5](https://github.com/yomotsu/camera-controls/releases/tag/v1.37.5)

Maybe we should revert this commit: https://github.com/yomotsu/camera-controls/pull/336/files

**Comment by yomotsu** [comment]
I found the probrem! In this line:
https://github.com/yomotsu/camera-controls/blob/bd824ac2bdc507063bbce740fe51d92d1c681d10/src/CameraControls.ts#LL2208C1-L2208C1

has to be:
```diff
- this._sphericalEnd.phi = clamp( this.polarAngle, this.minPolarAngle, this.maxPolarAngle );
+ this._sphericalEnd.phi = clamp( this._sphericalEnd.phi, this.minPolarAngle, this.maxPolarAngle );
```

**Comment by VegarRingdalAibel** [comment]
@yomotsu 
Very nice. 🥇 
Ill try and get some time to try it out tomorrow.

**Comment by VegarRingdalAibel** [comment]
Just gave it a try, sorry for the slow follow up on my part.

Camera moves very differently when setting target compared to 3.4.
Its like it moves the camera more in 3.4.
If I dolly to same place I set target, that place is no longer the current target, its like it pushes the target
Looks like I get a side effect where controller is all over the place after. 😄 

Have not managed to create a demo yet, but size of models is 100*100*100 in size, so maybe it a bug that get more clear when movement large.


Im using infinityDolly and dollyToCursor.

**Comment by yomotsu** [comment]
Sorry for your confusion,
I actually changed so without a major version update with https://github.com/yomotsu/camera-controls/pull/423 (Very sorry)
`infinityDolly` pushes the target into the heading direction and keeps the same distance between the target and the camera.
Because `dollyIn` uses the `distance` value internally, and can't compute the dolly amount if `minDistance` is too small, therefore, I changed `infinityDolly` to use the current distance as min and max distance, as the result, `distance` is fixed for `infinityDolly`.

Still setting dollyToCursor to false can preserve the target position through.
Should I revert the dollyToCursor behavior to use min and max values...?

**Comment by VegarRingdalAibel** [comment]
Maybe there could be 2 dollyToCursor options.
* `dollyToCursor` with `false` or `0` disabled
* `dollyToCursor` with `true` or `1` with old behavior 
* `dollyToCursor` with `2` with new behavior where it keeps distance between target and the camera

This way its not really a breaking change anymore, just give user more option depending on their need.
Since the dolly to cursor like it was was really nice.
And when you move to version 3.0.0 later you can remove the true/false as input.

**Comment by yomotsu** [comment]
Working on it and I think almost there.
`dollyToCursor` will be the old behavior. to enable the new behavior, set min/maxDistance to the same values.

https://github.com/yomotsu/camera-controls/pull/431

**Comment by VegarRingdalAibel** [comment]
@yomotsu 

Really appreciate you taking the time to fix the breaking changes.

have 2 videos where I use your controller in a app at work here:
https://www.youtube.com/@voffknur

just incase you wanted to see you module in work 🥇 

Been really nice to work with. 
Im sure I do some weird stuff when I navigate between normal navigation to WASD keys 😂 
Been using your hold events module

Section of my code (se below)...some part is a mess... so much on my need to improve list...

But its working really nicly on 2.3.4.
When user needs to exit walk mode they just use the scroll when/dolly to get out


````ts
   // offset is to stop it get lock in position
    async function updateCenter(offset = 0.0001) {
        const camera = getCanvasController().getActiveCamera();
        const controller = getCanvasController().getActiveControls();
        const azimuthAngle = controller.azimuthAngle;
        const polarAngle = controller.polarAngle;

        // in order to archive FPS look, set EPSILON for the distance to the center
        camera.position.set(
            camera.position.x + offset,
            camera.position.y + offset,
            camera.position.z + offset
        );

        await controller.setTarget(camera.position.x, camera.position.y, camera.position.z);
        controller.azimuthAngle = azimuthAngle;
        controller.polarAngle = polarAngle;
        

    }

    const KEYCODE = {
        W: 87,
        A: 65,
        S: 83,
        D: 68,
        Q: 81,
        E: 69,
        ARROW_LEFT: 37,
        ARROW_UP: 38,
        ARROW_RIGHT: 39,
        ARROW_DOWN: 40
    };

    const wKey = new holdEvent.KeyboardKeyHold(KEYCODE.W, 16.666);
    const aKey = new holdEvent.KeyboardKeyHold(KEYCODE.A, 16.666);
    const sKey = new holdEvent.KeyboardKeyHold(KEYCODE.S, 16.666);
    const dKey = new holdEvent.KeyboardKeyHold(KEYCODE.D, 16.666);
    const eKey = new holdEvent.KeyboardKeyHold(KEYCODE.E, 16.666);
    const qKey = new holdEvent.KeyboardKeyHold(KEYCODE.Q, 16.666);

    let shiftKey = false;
    const keys = new Set<string>();

    window.addEventListener("keydown", (e: KeyboardEvent) => {
        shiftKey = e.shiftKey;
        keys.add(e.key);
    });
    window.addEventListener("keyup", (e: KeyboardEvent) => {
        shiftKey = e.shiftKey;
        keys.delete(e.key);
    });

    wKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLD_START, () => {
        updateCenter();
    });

    eKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLD_START, () => {
        if (!keys.has("w")) {
            updateCenter();
        }
    });

    qKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLD_START, () => {
        if (!keys.has("w")) {
            updateCenter();
        }
    });

    aKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLD_START, () => {
        updateCenter();
    });

    sKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLD_START, () => {
        updateCenter();
    });

    dKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLD_START, () => {
        updateCenter();
    });

    const slowSpeed = 0.002;
    const runSpeed = 0.006;

    aKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLDING, (event: any) => {
        const speed = shiftKey ? runSpeed : slowSpeed;
        cc.__controls3d.truck(-speed * event.deltaTime, 0, false);
    });

    dKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLDING, (event: any) => {
        const speed = shiftKey ? runSpeed : slowSpeed;
        cc.__controls3d.truck(speed * event.deltaTime, 0, false);
    });

    eKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLDING, (event: any) => {
        const speed = shiftKey ? runSpeed : slowSpeed;
        const distance = speed * event.deltaTime;
        cc.__controls3d.elevate(-distance, false);
    });

    qKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLDING, (event: any) => {
        const speed = shiftKey ? runSpeed : slowSpeed;
        const distance = speed * event.deltaTime;
        cc.__controls3d.elevate(+distance, false);
    });

    wKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLDING, (event: any) => {
        const speed = shiftKey ? runSpeed : slowSpeed;
        cc.__controls3d.forward(speed * event.deltaTime, false);
    });

    sKey.addEventListener(holdEvent.HOLD_EVENT_TYPE.HOLDING, (event: any) => {
        const speed = shiftKey ? runSpeed : slowSpeed;
        cc.__controls3d.forward(-speed * event.deltaTime, false);
    });

````

**Comment by yomotsu** [comment]
Thanks for sharing the video and code.
I'm glad to see that since lib authors never get to see the real product using the lib.
Also helpful to understand the problem and be motivated.

and, thanks for using the holdEvent lib too. I recently received a bug report https://github.com/yomotsu/camera-controls/issues/419#issuecomment-1585432025 for holdEvent, and I should fix that as well then.

**Comment by VegarRingdalAibel** [comment]
> I'm glad to see that since lib authors never get to see the real product using the lib.

Here is some more motivation then 😄 
Here is another product with a lot of users using your module.
https://github.com/IFCjs/web-ifc-viewer

So your work is loved and appreciated 🥇

**Comment by yomotsu** [comment]
Thanks for more info.
I've felt like working for nothing...sometime😅

Aside from that, version 2.6.0 has been published with both old and new behavior.
Use with min/max distance when you enable `infinityDolly`.
- to emulate the previous "new behavior", set the min/max distance to the same value.
- not so, it just works as the old behavior.

Please check the example too.
https://yomotsu.github.io/camera-controls/examples/infinity-dolly.html

**Comment by VegarRingdalAibel** [comment]
Awesome, I will try out the new version now in my project.

Btw, you can see all repositories /packages using your module here:
And it is ALOT! 👍 

![image](https://github.com/yomotsu/camera-controls/assets/94840334/0d9af5a4-3875-4f08-a44c-7c2892f5b44f)

**Comment by VegarRingdalAibel** [comment]
@yomotsu 

Just tested it, works really good. Was not able find any unexpected behavior.
Closing issue.
Thank you 🥇

**Comment by yomotsu** [comment]
Good to hear that.
If you find other problems or requests, feel free to post issues again.

Also, thanks for the deps screen😊
got motivated💪
