### ISSUE TITLE
pinch disable y-axis

### ISSUE THREAD

**Issue by djayboy007** [yomotsu/camera-controls#43]
Hi, 

I disable the minPolarAngle and maxPolarAngle so that when i pinch the polar angle is lock and it will just move forward and backward. But is there a way when you move forward and backwards the y-axis will remain at y = 0 ? Now when i pinch here is a increase or decrease on y-axis .

thanks

**Comment by yomotsu** [comment]
I'm not sure your problem exactly, because of the lack of example. But I think you can just overwrite y value of camera after camera-controls updated.

**Comment by yomotsu** [comment]
or if you don't need the "orbit" feature, you may not need to rely on camera-controls too.

**Comment by djayboy007** [comment]
minPolarAngle and maxPolarAngle is ok already, but how to disable and enable the truck? sometimes i just want to orbit the camera, thanks

**Comment by SHT** [comment]
You can try setting `controls.truckSpeed` to `0`.

**Comment by edsilv** [comment]
@yomotsu Is it possible at the moment to constrain trucking on x and y? So for example you could disable trucking on x so only trucking on y is available, and vice versa?

**Comment by edsilv** [comment]
I've created a PR here: https://github.com/yomotsu/camera-controls/pull/205
