### ISSUE TITLE
Multiple camera render

### ISSUE THREAD

**Issue by xuchaozou** [yomotsu/camera-controls#432]
### Is your feature request related to a problem? Please describe.

When will it be possible to pass multiple cameras in, multiple viewports in, and automatically render according to those cameras, like three views

**Comment by xuchaozou** [comment]
examples : 
` // render first view
  renderer.setViewport(0, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor(0, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera1);


  //  render second view
  renderer.setViewport(window.innerWidth / 3, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor(window.innerWidth / 3, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera2);


  //render thrid view
  renderer.setViewport((window.innerWidth / 3) * 2, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissor((window.innerWidth / 3) * 2, 0, window.innerWidth / 3, window.innerHeight);
  renderer.setScissorTest(true);
  renderer.render(scene, camera3);`
i need to you help 
thanks!

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
I'm working on it and will be possible with a new feature called intaractiveArea
see the PR for more details: https://github.com/yomotsu/camera-controls/pull/433

**Comment by xuchaozou** [comment]
I just passed the test. When will the new version be released with this new feature? Thank you

**Comment by yomotsu** [comment]
Sorry for the delay.
I just published v2.7.0 with the feature.

**Comment by xuchaozou** [comment]
Thank you for your support. I am going to try to update the latest version in the project. If there are any other bugs, I will mention them to you

**Comment by yomotsu** [comment]
The issue seems to be solved. closing.
