### ISSUE TITLE
If pointer is held down without any movement "updated" keeps firing

### ISSUE THREAD

**Issue by vis-prime** [yomotsu/camera-controls#450]
### Describe the bug

I'm using the on demand rendering method since model is static , it works great

one thing i noticed

if I keep left click held down , cameraControls.update(delta) return true continuously

my use case:
I want to render the final frame with full device pixel ratio after "sleep" event 
When mouse is held down it's continuously firing 'sleep' and 'updated' 
On mouse up everything is fine

### To Reproduce

console.log the updated value in the render loop

### Code

```js
cameraControls.addEventListener("sleep", (e) => {
    console.log(e)
  })

  renderer.setAnimationLoop(() => {
    const delta = clock.getDelta()
    const hasControlsUpdated = cameraControls.update(delta)

    // on demand
    if (hasControlsUpdated) {
      console.log("render")
      render()
    }
  })
```

### Live example

[Sandbox to showcase the issue](https://codesandbox.io/s/camera-controls-on-pointer-pressed-down-fjnflx)

### Expected behavior

if the hold the mouse button down and do not move it at all , 'hasControlUpdated' should return false

### Screenshots or Video

https://github.com/yomotsu/camera-controls/assets/119810373/96f20997-ae97-4f96-88f0-b96e39e77764

### Device

Desktop

### OS

Windows

### Browser

Chrome

**Comment by yomotsu** [comment]
Thanks for using camera-controls, and your report.
Your demo and video are really helpful.

I tested on your demo, but It seems I can't reproduce the problem.
Does it happen to other devices too? Might be some mouse devices are too sensitive.
<video src="https://github.com/yomotsu/camera-controls/assets/212837/1cd71a31-0303-4a61-ace4-ae29a41f5e90"></video>

**Comment by vis-prime** [comment]
Strange , does not happen on phone too, 

on sandbox and my vite js project it's happening even if mouse is lifted off the surface

https://github.com/yomotsu/camera-controls/assets/119810373/4ba2f670-d2f6-4ffc-b6ed-1fe6d7b16a73

will check if it's the mouse causing the issue !

**Comment by vis-prime** [comment]
uh, it somehow fixed it self !

now idea how ! both sandbox and my local project seems to working correctly 

will close this for now !

thanks!

https://github.com/yomotsu/camera-controls/assets/119810373/0862c845-780d-4a68-ace3-c7bde0265b8d
