### ISSUE TITLE
Changing camera up vector significantly causes weird behavior

### ISSUE THREAD

**Issue by a3ng7n** [yomotsu/camera-controls#452]
### Describe the bug

After changing the camera's up vector more than 45deg and running updateCameraUp the "click to rotate" behavior doesn't seem to follow: e.g. if the up vector is changed 90 deg, dragging left and right causes the camera to tilt instead of pan - and vice versa with dragging up and down.

### To Reproduce

1. Go to camera-up example
2. Click on rotate polar by 90 deg
3. Click on apply camera up
4. Try dragging on the screen left and right, and see the camera tilting up/down.

### Expected behavior

Expect that after changing the camera's up vector, dragging orthogonal to the new up vector will cause azimuth rotation / panning, and dragging in parallel with the new up vector will cause polar rotation / tilting.

### Device

Desktop

### OS

Linux

### Browser

Chrome

**Comment by a3ng7n** [comment]
Don't know if I have the ability to link issues and pull requests, but #453 resolved this for me.

**Comment by yomotsu** [comment]
Oh thanks for your PR (and sorry for the delay)
I'll take a look!
