### ISSUE TITLE
Drag sensitivity on dolly movement

### ISSUE THREAD

**Issue by MiguelG97** [yomotsu/camera-controls#457]
### Describe the bug

Dear developer,

When I use the dolly and move towards the scene the drag sensitivity decrease. Is there a set up that can allow me to do infinity movements toward the camera while conserving the original drag sensitivity?

### To Reproduce

1. Move towards the scene for a good time
2. Drag the camera and the sensitivity is different
3. See error

### Expected behavior

conserving the original/default drag sensitivity

**Comment by MiguelG97** [comment]
thanks!

**Comment by wangkai942901902** [comment]
> 谢谢！

How was this problem solved?

**Comment by MiguelG97** [comment]
I didnt fix it. It still an issue for me. Drop off three js projects for now

**Comment by wangkai942901902** [comment]
> 我没修好。这对我来说仍然是一个问题。暂时放下三个js项目

I ran into this problem recently and haven't found a solution yet, if I do, I'll get back to you here

**Comment by MiguelG97** [comment]
@wangkai942901902 Solution is to set the minDistance and maxDistance as well
