### ISSUE TITLE
Callback on finish method like fitTo, setLookAt, DollyTo etc..

### ISSUE THREAD

**Issue by gino8080** [yomotsu/camera-controls#46]
I need a way to intercept with a callback or a promise resolution, when the camera finished the movement,
it is possible, or I have to implement by myself on render or something like that?

**Comment by yomotsu** [comment]
How about dispatching an event instead?
Maybe here:
https://github.com/yomotsu/camera-controls/blob/master/src/camera-controls.js#L867

**Comment by gino8080** [comment]
please can you give me some more hints, I really want to implement this feature on your great library!

thank you

**Comment by yomotsu** [comment]
Sorry for the delay.

Actually, I've added the event recently, called 'sleep'.
This might be usefull for you.
```
cameraControls.addEventListener( 'sleep', callbackFn );
```
