### ISSUE TITLE
Bug with setting interactiveArea top position.

### ISSUE THREAD

**Issue by timothyallan** [yomotsu/camera-controls#464]
### Describe the bug

My interactive area was never in the correct top position, and I believe this line is the culprit.

Should be interactiveArea.y, not  interactiveArea.x

### To Reproduce

look at this line 
https://github.com/yomotsu/camera-controls/blob/58e4db36d923a5755e236d114d73abd0f56ad3bd/src/CameraControls.ts#L1556C10-L1556C10

### Expected behavior

Should set to the y variable.

**Comment by yomotsu** [comment]
Thank you for pointing it out.
It seems you are right.
Would it be possible to open a PR to fix the line?
