### ISSUE TITLE
would you make a component of A-FRAME?

### ISSUE THREAD

**Issue by qq2956218657** [yomotsu/camera-controls#47]
I had try to use camera-controls.js to make a component of aframe-v8.0.js
but I get some difficulty at aframe-v9.0.js

**Comment by yomotsu** [comment]
Sorry, I'm not good at Aframe. Could I hear about your problem?

**Comment by qq2956218657** [comment]
> Sorry, I'm not good at Aframe. Could I hear about your problem?

oh,thank you,I had found another way to deal my problem.
