### ISSUE TITLE
fitTo method for orthographic camera

### ISSUE THREAD

**Issue by partynikko** [yomotsu/camera-controls#48]
Hi 👋 
First of all thanks for these controls. I find that it works really well, even with an orthographic camera!

I noticed that there is no solution for using the `fitTo` method when using an orthographic camera. I actually have a solution that I'm currently using and I wonder if you'd like me to make a PR out of it?

It's a calculation that sets the `camera.zoom` value so that it fits perfectly with the boundaries.
If you'd like I'll make a PR out of it 👍

**Comment by yomotsu** [comment]
That would be very nice.
Please make a PR for it when you have time.

**Comment by partynikko** [comment]
Sorry for my late reply. I've been on vacation and stuff 😎 
I will create a PR for it, sure! Just need to dig into the code base a bit and see. Expect one soon!

**Comment by yomotsu** [comment]
No problem, enjoy your vacation🏝
If you have any question, feel free to ask us.

**Comment by partynikko** [comment]
Thank you 🌴☀️.

Instead of doing a PR I'll supply the calculation and hopefully you can implement it 😊 
This have worked perfectly for me in my setup with an orthographic camera.

This will calculate a zoom value for the camera with respect to the set `minZoom` and `maxZoom`. 

`width` and `height` are those of the canvas, `AABB` is that of the Object3D/Box3 and and `PADDING` is a percentage padding ranging from 0 to 1.

```javascript
// minZoom < zoom < maxZoom
const zoom = Math.max(
  Math.min(
    Math.min(
      width / (AABB.max.x - AABB.min.x),
      height / (AABB.max.y - AABB.min.y)
    ) * PADDING // i.e. 0.95 = 5% padding,
    maxZoom
  ),
  minZoom
);
```

It can of course also be used without respecting the `minZoom` and `maxZoom` of the controls:
```javascript
const zoom = Math.min(
  width / (AABB.max.x - AABB.min.x),
  height / (AABB.max.y - AABB.min.y)
) * PADDING;
```

Let me know what you think and if we can figure out a good way to get it implemented! :)

**Comment by yomotsu** [comment]
Thanks! I will take a look

**Comment by yomotsu** [comment]
the feature has been merged at https://github.com/yomotsu/camera-controls/pull/98
closing
