### ISSUE TITLE
Invalid "main" entry in v2.8.x

### ISSUE THREAD

**Issue by AER-Quinten** [yomotsu/camera-controls#481]
The package.json sets the main entry to `dist/camera-controls.js` which was changed into `dist/camera-controls.module.js` in 89cad76

https://github.com/yomotsu/camera-controls/blob/a8e1ef1780b23707bf7bc22619b43d8b2fd17035/package.json#L6

This causes our project with `@react-three/drei` to fail during build.

**Comment by AngyDev** [comment]
I'm having the same issue

**Comment by jsuhncc3d** [comment]
I'm also having the same issue.

**Comment by Seb-GRAF** [comment]
Same here

**Comment by Erwol** [comment]
We also ran into the same issue with `@react-three/drei@^9.96.5`. As a temporary solution you can add the following `resolution` to your `package.json`:
```
  "resolutions": {
    "camera-controls": "2.7.4"
  }
```

**Comment by Erwol** [comment]
*This is most likely related to https://github.com/yomotsu/camera-controls/compare/v2.7.4...v2.8.0#diff-47407fecafdf5f5cd55403c3de457833ddf9b6fab45253c04e1dc4c7cb4495b1L17, from yesterday's `[v2.8.0](https://github.com/yomotsu/camera-controls/releases/tag/v2.8.0)` changelog:
> Drop support for UMD, add module.min.js ([89cad76](https://github.com/yomotsu/camera-controls/commit/89cad76e9dec1dd905670060e8f7c664fd50e386))

**Comment by yomotsu** [comment]
Very sorry for the problem.
I fixed it with https://github.com/yomotsu/camera-controls/pull/482 and v2.8.2 has been published.

**Comment by AER-Quinten** [comment]
> (Do we still need UMD or CJS as well...?

Seems like `@react-three/drei` builds to CJS and tries to import your package using `require`, which throws a syntax error. My guess is that CJS will be required for `drei` to work, I don't know if there are any other CJS packages that depend on yours that have the same issue.

**Comment by w00khyung** [comment]
> (Do we still need UMD or CJS as well...?

I'm using @react-three/drei v9.80.3 and getting build errors after the v2.8.2 update. having trouble with the `require` syntax, and I think need CJS support.

**Comment by AER-Quinten** [comment]
> Looks good now?

Build succeeded. Thanks!

**Comment by w00khyung** [comment]
> Looks good now?

it works good. thanks!
