### ISSUE TITLE
Add focus function

### ISSUE THREAD

**Issue by WREQI** [yomotsu/camera-controls#484]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/yomotsu/camera-controls/assets/35467304/8126144c-c15c-4492-97f9-ec66ea57ad5e)
![image](https://github.com/yomotsu/camera-controls/assets/35467304/77606d2d-9378-4d7c-b44a-78a7ae21a80a)
The editor of three.js has an EditorControls and a focus function that can automatically and quickly locate the model

**Comment by yomotsu** [comment]
Thanks for your request.
CameraControls already has fitToBox and fitToSphere.
Do you still need another feature?

**Comment by WREQI** [comment]
![image](https://github.com/yomotsu/camera-controls/assets/35467304/82e4f8e1-6509-449b-9536-b38e3e1f200e)
@yomotsu What should I do if I need to be at a certain distance from the object instead of completely filling it, which means that the distance can be set?

**Comment by yomotsu** [comment]
There are several methods such as `dolly()` and `dollyTo()`, and also can be combined with `fitToXXX()`.
Please read the docs for more details.

https://github.com/yomotsu/camera-controls?tab=readme-ov-file#dolly-distance-enabletransition-
https://github.com/yomotsu/camera-controls?tab=readme-ov-file#dollyto-distance-enabletransition-

**Comment by WREQI** [comment]
![image](https://github.com/yomotsu/camera-controls/assets/35467304/20bf6afe-41bd-4c2f-af8a-de43a65f0ddd)
Okay, thank you. @yomotsu 
The controller in three.js editor can bi-directional link an indicator in the bottom right corner. If CameraControls is used, how can it correctly bi-directional link an indicator? Is there a good example?

**Comment by yomotsu** [comment]
> a good example?

Did you check all the examples in the readme?
So far, there are no such examples, but you can try it yourself with CameraControls.

**Comment by WREQI** [comment]
MinZoom only supports orthogonal cameras? @yomotsu

**Comment by yomotsu** [comment]
Sorry, but please read and check the docs for further details.
