### ISSUE TITLE
Error 'ThreeCameraControls.install is not a function'

### ISSUE THREAD

**Issue by dmurvihill** [yomotsu/camera-controls#485]
### Describe the bug

A basic GraphCanvas on a new T3 app is throwing an import error.

```
TypeError: ThreeCameraControls.install is not a function
    at file:///Users/dolan/IdeaProjects/reagraph-import-issue/node_modules/reagraph/dist/index.js:1829:21
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
```

### To Reproduce

Check out the [reproduction repo](https://github.com/dmurvihill/reagraph-import-issue). `npm install; npm run dev`

You will see the error in your terminal and at http://localhost:3000/.

### Live example

https://codesandbox.io/p/github/dmurvihill/reagraph-import-issue/main?workspaceId=7cceb122-1e10-4fbd-ace4-220700ef6443

### Expected behavior

An empty GraphCanvas should be rendered.

### Device

Desktop

### OS

MacOS

### Browser

Firefox

**Comment by yomotsu** [comment]
Just so you know, our examples work without the error you reported.
https://github.com/yomotsu/camera-controls?tab=readme-ov-file#examples

Please double check your app or dependencies.

**Comment by dmurvihill** [comment]
Sorry, wrong repo. This was meant for downstream.
