### ISSUE TITLE
Not update in worker

### ISSUE THREAD

**Issue by RyugaRyuzaki** [yomotsu/camera-controls#490]
### Describe the bug

I tried with worker, it did't update in worker

### To Reproduce

			( function anim() {

				const delta = clock.getDelta();
				// const elapsed = clock.getElapsedTime();
				const updated = cameraControls.update( delta );

				// if ( elapsed > 30 ) return;

				requestAnimationFrame( anim );

				if ( updated ) {

					renderer.render( scene, camera );
					self.postMessage( 'rendered' );

				}

			} )();

### Expected behavior

Runs stably on worker

### Device

Desktop

### Browser

Chrome

**Comment by yomotsu** [comment]
How do I reproduce that?
Can you please elaborate on your problem, using a SIMPLIFIED demo using Codesandbox or so?

**Comment by RyugaRyuzaki** [comment]
> How do I reproduce that? Can you please elaborate on your problem, with a SIMPLIFIED demo using Codesandbox or so?

Hi, i ran in example here :https://github.com/yomotsu/camera-controls/blob/dev/examples/worker.html . It did't work

**Comment by yomotsu** [comment]
It works on my devices.
Can you please double check your setup?

**Comment by RyugaRyuzaki** [comment]
> It works on my devices. Can you please double check your setup?

Well, i cloned the repo and run, not any change. so i referenced this :https://github.com/pmndrs/react-three-offscreen/blob/main/src/render.ts and it works

**Comment by yomotsu** [comment]
Sorry but without being able to reproduce the problem, I can't investigate the cause...
