### ISSUE TITLE
delta?

### ISSUE THREAD

**Issue by ManuelGraf** [yomotsu/camera-controls#5]
In your update method, what is delta exactly? frame time delta? Because this gives me NaN on the camera position if left blank and if I set it to the time that passed since last frame it just goes crazy spinning anywhere (mostly to the poles tho, although i restricted polarangle the same way i did with orbitcontrols...)

I have to mention I am working on THREE r78, so i had to replace spherical.copy() as this threw me errors.

I am using your src and compile it myself with babel, so i can still make some adjustments.

Here is my "config" for orbitControls:

    this.orbitControls.minPolarAngle = Math.PI / 2 - Math.PI / 4;
    this.orbitControls.maxPolarAngle = Math.PI / 2 + Math.PI / 4;
    this.orbitControls.maxDistance = 2.5;
    this.orbitControls.minDistance = 1;
    this.orbitControls.enableDamping = true;
    this.orbitControls.dampingFactor = 0.1;
    this.orbitControls.rotateSpeed = 0.05;
    this.orbitControls.autoRitate = true;

the funny thing is, everything seems to work when i drag only slightly (so delta is below EPSILON). so obviously i am doing somthing wrong with the dampening?!

**Comment by yomotsu** [comment]
I should have added the meaning of [delta](  https://github.com/yomotsu/camera-controls/blob/master/src/camera-controls.js#L443) in the doc

`delta` the first argument for update method is the diff time between prev frame. You can get the delta time with `THREE.Clock`.
