### ISSUE TITLE
Make mouse buttons configurable.

### ISSUE THREAD

**Issue by DaanVandenBosch** [yomotsu/camera-controls#51]
Would you accept a pull request that makes mouse buttons configurable? What should the API look like?

In my specific case I want to use the left mouse button to translate and the right button to rotate.

In case anyone is looking for a workaround, this works:

```js
CameraControls.install({
    // Hack to make panning and orbiting work the way we want.
    THREE: {
        ...THREE,
        MOUSE: { ...THREE.MOUSE, LEFT: THREE.MOUSE.RIGHT, RIGHT: THREE.MOUSE.LEFT },
    },
});
```

**Comment by yomotsu** [comment]
Yes, PRs are always welcome.

We could do something like the OrbitControls of three.js https://threejs.org/docs/#examples/en/controls/OrbitControls.mouseButtons

<img width="868" alt="Screen Shot 2019-07-27 at 10 43 53 PM" src="https://user-images.githubusercontent.com/212837/61995201-1a1f9e80-b0c0-11e9-8ecf-f6479e0b7838.png">

**Comment by DaanVandenBosch** [comment]
Personally I'm not a fan of that option because it doesn't communicate exactly what the buttons will do. What do you think of the following?

```js
CameraControls.TOUCH = {
    ONE_FINGER: 1,
    TWO_OR_THREE_FINGER: 2
};

controls.mouseButtons.orbit = THREE.MOUSE.LEFT;
controls.mouseButtons.dolly = THREE.MOUSE.MIDDLE;
controls.mouseButtons.truck = THREE.MOUSE.RIGHT;

controls.touch.orbit = CameraControls.TOUCH.ONE_FINGER;
controls.touch.dolly = true; // Just true or false, either you want to pinch to dolly in/out or not.
controls.touch.truck = CameraControls.TOUCH.TWO_OR_THREE_FINGER;
```

**Comment by yomotsu** [comment]
Thanks for your reply. Separating orbit/dolly/truck looks better for me too.

I was also thinking about whether we should support advanced input, such as hold-then-move to truck or, double click then move to dolly (like google maps on mobile).
But I guess this kind of advanced inputs should be done in user-land.

So, I agree with your idea.

Just in case, what do you think about this, @FMS-Cat ?

**Comment by yomotsu** [comment]
@DaanVandenBosch Would you make a PR for this? or should I do?

**Comment by DaanVandenBosch** [comment]
My apologies, I'll do it sometime this week.

As for more advanced input, I think that should go into another issue. Personally I don't need it so I don't want to work on it at the moment.

**Comment by yomotsu** [comment]
You don't need to apologize. It would be helpful 😁

> As for more advanced input, 

I agree with you and look forward to the PR, or if you don't have much time, I could do sometime. Feel free to ask me.

**Comment by FMS-Cat** [comment]
whoa I didn't noticed to this!

> I'm not a fan of that option because it doesn't communicate exactly what the buttons will do

I totally agree with that, we should avoid altering our interface from the OrbitControl way too much though.
We should consult about it to original OrbitControl devs first!

**Comment by FMS-Cat** [comment]
also, possibly, some people might want keyboard combinations like RIGHT+SHIFT or MIDDLE+CTRL ...

**Comment by yomotsu** [comment]
mouse buttons and touches config feature was just added
see: https://yomotsu.github.io/camera-controls/examples/config.html

**Comment by dguayrobotiq** [comment]
@yomotsu Is there a way to configure keyboard event to camera controls? With OrbitControls you can move the camera with arrows.

**Comment by yomotsu** [comment]
@dguayrobotiq So far there are no features for it. But could be added.
Do you mind opening a new issue? since this was already closed.

**Comment by dguayrobotiq** [comment]
See #79
