### ISSUE TITLE
Behavior similar to three.js Trackball Controls

### ISSUE THREAD

**Issue by guido5544** [yomotsu/camera-controls#518]
### Is your feature request related to a problem? Please describe.

It would be nice if there was a setting to turn off maintaining a fixed camera up vector, similar to how the TrackBallControls behave.

**Comment by yomotsu** [comment]
Thanks for your request, however, please refer to https://github.com/yomotsu/camera-controls/issues?q=is%3Aissue+Trackball+Controls
