### ISSUE TITLE
Truck/Controls Event Listener Disappears after Clicking Twice

### ISSUE THREAD

**Issue by babophett** [yomotsu/camera-controls#523]
### Describe the bug

I upgraded an old project from version 1.33.1 to camera-controls@latest. I changed all the deprecated code, and almost all the behavior remained except for my previous trucking behavior. Previously I would right click to truck, complete the trucking operation, and then right click again to truck. Now if I truck and want to truck again, the operation won't happen, and the controls event listener doesn't trigger. If I scroll in or out, or left click on some item on the scene, the trucking operation and controls event listener comes back. Any assistance would be greatly appreciated!

### To Reproduce

1. Go to latest version
2. Right click to pan
3. Right click to pan again

### Expected behavior

I would like to be able to continuously truck, by right clicking multiple times in a row.

**Comment by babophett** [comment]
There's even stranger behavior, if I switch the truck to left pan, it behaves normally and the controls event listener doesn't disappear.

**Comment by VictorGaiva** [comment]
What was it? I'm having a similar issue 😅
