### ISSUE TITLE
Use CSS to complete the screen flip, and the camera is adapted

### ISSUE THREAD

**Issue by Jinxishihenian** [yomotsu/camera-controls#527]
### Is your feature request related to a problem? Please describe.

https://discourse.threejs.org/t/r3f-canvas-rotate/63865

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
Hwoever, as @mjurczyk responded, you should not rotate the canvas using CSS.

**Comment by Jinxishihenian** [comment]
I think what you're saying is reasonable
