### ISSUE TITLE
how can we implement autorotate ?

### ISSUE THREAD

**Issue by mustafaarun** [yomotsu/camera-controls#53]
is there a way to implement autorotate as orbit controls ?

**Comment by yomotsu** [comment]
you can just rotate constantly at the animation loop,

```
function yourAnimationLoop() {

  // snip...
  cameraControls.rotate( delta, 0, true );

}
```

**Comment by mustafaarun** [comment]
thank you, but this way it waits for previous movement/command (for example setLookAt) to complete

**Comment by mustafaarun** [comment]
thank you

**Comment by yomotsu** [comment]
seems this has been solved.
closing the issue.
