### ISSUE TITLE
updateCameraUp() method does not expose in ts 

### ISSUE THREAD

**Issue by Huang77** [yomotsu/camera-controls#54]
i used ts version of camera-controls, when i need to change the up of camera, do i need to call updateCameraUp() ?

**Comment by yomotsu** [comment]
Yes, that's right.
You need to call `updateCameraUp()` every time when you change camera.up. then sync them.

I don't recommend but you could call `updateCameraUp` in your animation loop. Be aware of that, it could be an unnecessary load.  updateCameraUp causes  [some calculation](https://github.com/yomotsu/camera-controls/blob/master/src/camera-controls.js#L834).

**Comment by Huang77** [comment]
ok thanks~~~
