### ISSUE TITLE
Fixed wheel_update

### ISSUE THREAD

**Issue by octopoulos** [yomotsu/camera-controls#57]
I don't have permission to create a PR, so here's the code I changed:
```
		this.dollySpeed = 1.0;
		this.dollyTransition = false;
```
in dollyInternal:
```
scope.dolly( distance, scope.dollyTransition );
```
in onMouseWheel:
```
				dollyInternal( - delta, x, y );
				scope.dispatchEvent( {
					type: 'control',
					originalEvent: event,
				} );
```
=> now if we use dollyTransition = true, the wheel up/down is smooth, and it also dispatches an event, which is useful if we only want to render the 3d when something has changed.

**Comment by yomotsu** [comment]
Thanks for your contribution.
I think it works well in Windows. however, mouse wheel dolly in macOS is already smooth and `dollyTransition` may conflict with it😢
Can we leave it as it is?

> dispatches an event

Nice find. it was missing.

**Comment by octopoulos** [comment]
Hi, you're welcome. I made additional changes, because I needed them:
1)
     case THREE.MOUSE.MIDDLE:
                if (scope.dollySpeed > 0)
         scope._state = STATE.DOLLY;
     break;

     case THREE.MOUSE.RIGHT:
                if (scope.truckSpeed > 0)
         scope._state = STATE.TRUCK;
     break;

This is useful to disable DOLLY or TRUCK, just set the speed to 0 and they
won't be enabled.

2) yes on Windows, the dollyTransition is useful, and maybe it's already
fine on Mac, but that's why it's an optional setting, by default, it's
false, so it won't change anything.

Anyway, the library is good as it is, I just needed to make some changes
for myself, so those are just suggestions for you, feel free to do what you
want :)

By the way, now I need to do something else, but it's similar to your
library: I need to move an object instead of the camera, using the same
kind of controls. It would be great if the same library could be used for
both.  What do you think?
