### ISSUE TITLE
rotateTo method reverting all rotations if multiple were made before

### ISSUE THREAD

**Issue by puresick** [yomotsu/camera-controls#58]
I am using `camera-controls` on a sphere acting as an earth globe with different POIs put onto it.
The `rotateTo` method is being used to rotate to one of the POIs after the user clicks on them.

If the sphere has been rotated multiple times and the user clicks on one POI, all the rotations will be reverted on moving to the point, resulting in the sphere being rotated multiple times.
This should be fine as a default expected behavior, because it is logical correct, but in my case, I would like to animate `rotateTo` using the smallest relative distance from the current position to the POIs position.
I resolved this by firing the `saveState` and `reset` methods on user input which seem to reset the "rotation value/state", but this solution feels a bit hacky.

Maybe it might be useful to implement some kind of option parameter to toggle between the current behavior and the "relative" one. Or is there another way to handle this which I am currently overseeing?

**Comment by yomotsu** [comment]
Thanks for using and your feedback
I think what you need is to normalize rotating, isn't it?
If so we could have kinda normalizeRotation method

**Comment by puresick** [comment]
Yes that would be one possible solution. :)

**Comment by yomotsu** [comment]
Actually, there is already [`_sanitizeSphericals`](https://github.com/yomotsu/camera-controls/blob/master/src/camera-controls.js#L1038) but private use.
I'll make it public and rename.

**Comment by yomotsu** [comment]
`normalizeRotations()` method has been added.
https://github.com/yomotsu/camera-controls#normalizerotations
