### ISSUE TITLE
Why is dolly disabled for OrthographicCamera?

### ISSUE THREAD

**Issue by cjamin** [yomotsu/camera-controls#60]
Hi,

Thank you for the library!
I'm wondering why dolly is disabled for orthographic cameras, while we can dolly in/out using the mouse wheel?

Thanks!

**Comment by yomotsu** [comment]
Sorry for the delay.
Because orthographic uses zoom rather than dolly.

I'm planning to make another method called zoom sometime soon!

**Comment by yomotsu** [comment]
BTW, you can directly set `zoom` to the camera if you use Orthographic.

```
camera.zoom = 10
```

**Comment by cjamin** [comment]
Thanks for the answer.
Ok, I meant zoom. Actually, I wanted to be able to zoom with a transition, so I'll wait for the new function.

**Comment by Jesusbill** [comment]
@yomotsu I may be able to work on this feature during Christmas. I am using this great library for a project and currently I have the Orthographic camera disabled as I would like it to have the same functionalities as the Perspective one.
I will contact you before to verify what needs to be done.

**Comment by yomotsu** [comment]
@Jesusbill Thank you so much! I really appreciate it❤️ And thanks for using.
Actually I also started adding zooming feature on [feature/zoom branch](https://github.com/yomotsu/camera-controls/tree/feature/zoom) and kinda working for now

![3](https://user-images.githubusercontent.com/212837/70713537-9510eb00-1d29-11ea-984f-28d2f6b58ffd.gif)

**Comment by Jesusbill** [comment]
Sounds great @yomotsu I will be following your development
