### ISSUE TITLE
Orbiting by drag feels weird under extreme aspect ratios

### ISSUE THREAD

**Issue by FMS-Cat** [yomotsu/camera-controls#64]
We might want to see its fov instead of just seeing its ratio between resolution and mouse movement

**Comment by yomotsu** [comment]
Aww, that's right...
![4](https://user-images.githubusercontent.com/212837/71448803-94923e80-2784-11ea-8e2c-3abab6047efb.gif)
![5](https://user-images.githubusercontent.com/212837/71448805-965c0200-2784-11ea-9636-c4706927a1c9.gif)

**Comment by FMS-Cat** [comment]
yes I think so.
I'm not sure we should consider the `camera.aspect` as well

**Comment by yomotsu** [comment]
I think this was fixed with cb7fbac 👍
