### ISSUE TITLE
firing multiple methods at once

### ISSUE THREAD

**Issue by bw1984** [yomotsu/camera-controls#7]
I really like the way the 'reset' motion works whereby the camera swoops back into position and rotates around the object if necessary. Is there any way to emulate this but for a specific coordinate? What im looking to do is basically combine the rotate function with the moveTo function so i can navigate the scene by moving the camera in spirals. Im struggling to figure out if its possible with this library, any suggestions?

**Comment by yomotsu** [comment]
sorry for late response.
I think moving to the specific should be handled by other function, such as tween.js. then, once it has done, enable the cameraControl.

so far, no plan to support that feature, but I guess I will add an example for it.

**Comment by gino8080** [comment]
yeah totally agree, so we can set a duration and a callback, i'll try on work on this

**Comment by gino8080** [comment]
I'm trying to implement tween camera movement,
I finally got that I have to disable the controls AND also check in the render if is enabled,

so I finally can move camera with tween..BUT i got a problem, 

if i rotate (orbit) or zoom with mouse wheel (truck) and then make another tween IS OK

BUT if I Pan (dragging with right mouse button) the camera jump to the previous position,
it seems that the position is not update

[working stackblitz example here](https://stackblitz.com/edit/three-camera-tween)
please help!
