### ISSUE TITLE
Error: [Intervention] Unable to preventDefault inside passive even listener

### ISSUE THREAD

**Issue by omararturo** [yomotsu/camera-controls#74]
Detected in Chrome in the device view. Chrome Version 79.0.3945.117 (Official Build) (64-bit).

![image](https://user-images.githubusercontent.com/3682957/72657808-0bcb8480-3977-11ea-8c8d-b57162110c2b.png)

**Comment by yomotsu** [comment]
Does not reproduce here
![5](https://user-images.githubusercontent.com/212837/72658043-e8442080-39ee-11ea-94d1-b26c3ce6213e.gif)

**Comment by omararturo** [comment]
Simulate Mobile Devices with Device Mode in Chrome DevTools.

Start **Chrome**, navigate to the web page you want to test and open the **Developer Tools** (Menu > Tools > Developer Tools, Cmd+Opt+I on Mac or F12 / Ctrl+Shift+I on Windows and Linux). The dimensions of the emulated screen can be changed when Responsive is selected as the **device** type.

...and tray again!

**Comment by yomotsu** [comment]
Thanks. Confirmed the problem.

**Comment by yomotsu** [comment]
should be fixed with https://github.com/yomotsu/camera-controls/pull/75

**Comment by yomotsu** [comment]
solved with v1.18.3
