### ISSUE TITLE
Mouse Objekt Click Event after Camera move?

### ISSUE THREAD

**Issue by stasioman** [yomotsu/camera-controls#78]
How
Mouse Objekt Click Event after Camera move?

**Comment by stasioman** [comment]
renderer.domElement.addEventListener("click", onClick, false);

      function onClick(event) {
        mouse.x = (event.clientX / window.innerWidth) * 2 - 1;
        mouse.y = -(event.clientY / window.innerHeight) * 2 + 1;
        raycaster.setFromCamera(mouse, camera);
        intersects = raycaster.intersectObject(mesh);
        if (intersects.length > 0) {
          console.log('ok');
        }
      }

After " ... cameraControls.setPosition( -5, 2, 1, true )"
Click on Object in old Position not in new

**Comment by yomotsu** [comment]
What do you mean by "after"?

**Comment by stasioman** [comment]
camera.position.set(0, 0, 5); after Camera change position  "cameraControls.setPosition( -5, 2, 1, true )"

**Comment by yomotsu** [comment]
Sorry, I don't get your point.

**Comment by stasioman** [comment]
https://raw.githubusercontent.com/stasioman/treejs/master/1.jpg

https://raw.githubusercontent.com/stasioman/treejs/master/2.jpg

**Comment by stasioman** [comment]
var raycaster = new THREE.Raycaster();
      var mouse = new THREE.Vector2();

**Comment by yomotsu** [comment]
I think that is not a camera-controls problem of camera-contorls.

**Comment by stasioman** [comment]
Do you have a functional example with object click function?

**Comment by stasioman** [comment]
camera-controls +  object click function

**Comment by yomotsu** [comment]
No I don't.
Please use issues for a bug report or feature request.
