### ISSUE TITLE
Control camera with keyboard

### ISSUE THREAD

**Issue by dguayrobotiq** [yomotsu/camera-controls#79]
With OrbitControls you can map keyboard keys to pan the camera (see https://threejs.org/docs/#examples/en/controls/OrbitControls.keys). What I'd like to be able to do with CameraControls is bind WASD keys to pan/truck the camera. Could also add the possibility to bind keys to any camera action to be more flexible.

**Comment by yomotsu** [comment]
I think it should be better to have keyboard handling separately.

So I just added a new example for keyboard events, rather than as a part of the lib.
check to see below: 
https://raw.githack.com/yomotsu/camera-controls/dev/examples/keyboard.html

**Comment by dguayrobotiq** [comment]
@yomotsu Indeed this is probably better. Thanks for the example !

**Comment by maksnester** [comment]
Would be nice to have some oneliner though. Maybe even as a separate package? I just think something like `enableWASD(cameraControls)` would be really convenient. 

But thank you for the example anyway 🙏

**Comment by yomotsu** [comment]
@maksnester 
> Maybe even as a separate package?

Maybe..but it depends on the user.

- Someone may want WASD for movement
- Another guy may want arrow keys for movement
- Another may want arrow keys for rotation

That's why I believe this would be done in user-land.
