### ISSUE TITLE
use different pivot point and focalpoint

### ISSUE THREAD

**Issue by bw1984** [yomotsu/camera-controls#8]
I would like to be able to pass a Vector3 to some of the functions (e.g. rotate) as an argument to allow me to set what point the camera will pivot/dolly around, whilst being able to control the focalPoint of the camera separately. Currently it seems like there is no way to change the camera lookAt coordinates without changing the target for the transitions. Is this possible?

**Comment by yomotsu** [comment]
@bw1984 

basically, camera-controls just provide an orbit-control feature so far, and there are no function to it.
but this might be workaround to change the pivot.

```
const lookAt = new THREE.Vector3( x, y, z );
control._target.copy( lookAt );
control._targetEnd.copy( lookAt );
```
