### ISSUE TITLE
Cannot add keyboard event listener on the same domElement as CameraControls

### ISSUE THREAD

**Issue by dguayrobotiq** [yomotsu/camera-controls#80]
Given `canvas` my renderer's domElement which is used when creating CameraControls, when adding an event listener on `keydown` like so:
```
canvas.addEventListener("keydown", () => {
  console.log("This is not working");
});
```

Then the console.log is never logged. I tried adding a click event listener just to be sure it works and it does. Only the keyboard related events (keydown, keyup, keypress) don't work. 

Any idea why?

**Comment by yomotsu** [comment]
Actually, that is not a bug at all.

Please read [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event) first, or you can just use my keyboard event lib which is used in the example.

**Comment by dguayrobotiq** [comment]
@yomotsu Why do you say it is not a bug? When using OrbitControls instead of CameraControls,  the code above works when binding keyboard event on canvas.

**Comment by yomotsu** [comment]
Long story short:

1. canvas.setAttribute( 'tabindex', '0' );
2.canvas.focus(); 

then KeyboradEvent works.

**Comment by eviltik** [comment]
On my side, i'm using threejs InteractiveGroup with CameraControls.

Note that the InteractiveGroup is instanciated after CameraControls.

To make it work i found 2 tricks ( tests ) :

* in InteractiveGroup.js, comment the line `event.stopPropagation()` https://github.com/mrdoob/three.js/blob/01e4eaf0c17c5906a73628576fbe27609ac82618/examples/jsm/interactive/InteractiveGroup.js#L28

OR

* replace `this._domElement.ownerDocument` with `this._domElement` in theses 4 lines https://github.com/yomotsu/camera-controls/blob/d63e9b80897a00893c78b8566ef9132505459298/src/CameraControls.ts#L550
