### ISSUE TITLE
removeEventListener missing

### ISSUE THREAD

**Issue by amcdnl** [yomotsu/camera-controls#84]
Need to un-comment the code for remove event listener.

**Comment by yomotsu** [comment]
Uh oh, sorry I will.

**Comment by yomotsu** [comment]
Solved with https://github.com/yomotsu/camera-controls/commit/5b3a9114bdf29081f36d2e78f25d39a451bf964e

Also here is the doc
https://github.com/yomotsu/camera-controls#removeeventlistener-type-string-listener-function-

**Comment by amcdnl** [comment]
Thank you!
