### ISSUE TITLE
compatability with react-three-fiber?

### ISSUE THREAD

**Issue by kurosh-z** [yomotsu/camera-controls#85]
hi ;)
I gave it a try with react-three-fiber and it got very laggy! specially as I try to rotate things!
here is the piece of Code that I wrote to make it work with react-three-fiber:
``` TSX
import React, { useRef } from 'react';
import * as THREE from 'three';
import { ReactThreeFiber, extend, useFrame, useThree } from 'react-three-fiber';
import CameraControls from 'camera-controls';
CameraControls.install({ THREE: THREE });

extend({ CameraControls });

declare global {
  namespace JSX {
    interface IntrinsicElements {
      cameraControls: ReactThreeFiber.Object3DNode<
        CameraControls,
        typeof CameraControls
      >;
    }
  }
}

const CControls: React.FC<any> = () => {
  const ccontrolRef = useRef<any>(null);
  const { camera, gl, clock, scene } = useThree();
  useFrame(() => {
    if (ccontrolRef.current) {
      const delta = clock.getDelta();
      const hasControlsUpdated = ccontrolRef.current.update(delta);
      if (hasControlsUpdated) gl.render(scene, camera);
    }
  });
  return <cameraControls ref={ccontrolRef} args={[camera, gl.domElement]} />;
};

export default CControls;

```

am I doing something wrong here? or its not somehow compatible with react-three?

**Comment by yomotsu** [comment]
Did you try without camera controls?
Did you also try with threejs official orbit controls?

Then if still it happens, can you provide a simplified working example on jsfiddle or somewhere?

**Comment by kurosh-z** [comment]
Thank you for the speedy reply!
yes I have used OrbitControls and it works fine!
here is the codesanbox version with some simplifications. you can click on the button to switch  the controllers.
https://codesandbox.io/s/blissful-chandrasekhar-ew99r

**Comment by yomotsu** [comment]
I don't know why but `delta` of every frame in your app is too small. `delta` supposet to be `0.016` millisec or so.
<img width="193" alt="Screen Shot 2020-02-29 at 10 38 09 AM" src="https://user-images.githubusercontent.com/212837/75598535-b212ba00-5adf-11ea-9928-2982dd6d1fbf.png">

maybe you can try kind of this,
```diff
- const hasControlsUpdated = ccontrolRef.current.update(delta);
+ const hasControlsUpdated = ccontrolRef.current.update(delta * 1000);
```

**Comment by kurosh-z** [comment]
I don't know about internals of react-three-fiber  but I don't use getDelta() in my app yet!
anyway that definitely solved the problem!
thanks again for investigating the issue.

**Comment by jfabraxas** [comment]
FYI: Second arg of useFrame callback is delta:
```
 useFrame((state, delta) => {
    if (ccontrolRef.current) {
      const hasControlsUpdated = ccontrolRef.current.update(delta);
      if (hasControlsUpdated) gl.render(scene, camera);
    }
  });
```
[rf3 doc](https://github.com/react-spring/react-three-fiber/blob/master/api.md#useframe)

**Comment by yaroslavnikiforov** [comment]
You don't need this line:
`if (hasControlsUpdated) gl.render(scene, camera);`

**Comment by ammanvedi** [comment]
just got this working here is my final code, seems to be working nicely thank you to both above i was trying to get a nice solution for dollyToCursor with OrbitControls with no luck and this one is perfect, i can go to bed now XD

```typescript
import React from 'react';
import * as THREE from 'three';
import { extend, ReactThreeFiber, useFrame, useThree } from '@react-three/fiber';
import CameraControls from 'camera-controls';

CameraControls.install({ THREE: THREE });

extend({ CameraControls });

declare global {
    namespace JSX {
        interface IntrinsicElements {
            cameraControls: ReactThreeFiber.Object3DNode<
                CameraControls,
                typeof CameraControls
            >;
        }
    }
}

export const CustomOrbitControls: React.FC<any> = React.forwardRef((props, ref) => {
    const { camera, gl } = useThree();
    useFrame((state, delta) => {
        if (ref.current) {
            ref.current.update(delta);
        }
    });
    return (
        <cameraControls
            ref={ref}
            args={[camera, gl.domElement]}
            dollyToCursor
            mouseButtons={{
                left: CameraControls.ACTION.TRUCK,
                middle: CameraControls.ACTION.NONE,
                right: CameraControls.ACTION.NONE,
                shiftLeft: CameraControls.ACTION.NONE,
                wheel: CameraControls.ACTION.ZOOM,
            }}
        />
    );
});

```
