### ISSUE TITLE
Include zoom in JSON state?

### ISSUE THREAD

**Issue by paulmelnikow** [yomotsu/camera-controls#87]
Hi, I was thinking the zoom probably should be included in the JSON state, since it's critical for the orthographic camera.

For completeness, I could also imagine adding an accessor to the camera controls to get this value. Though that isn't essential. I'm able to pick the zoom from the camera directly.

What do you think?

**Comment by yomotsu** [comment]
Absolutely sure!

I've been not caring JSON state since I don't use...
Do you mind sending a pull request for it?
