### ISSUE TITLE
saveState issue

### ISSUE THREAD

**Issue by ksabariraj** [yomotsu/camera-controls#9]
Hi,

Thanks for the plugin.

I am getting the below error on save state.

<img width="548" alt="screen shot 2018-06-09 at 6 20 16 pm" src="https://user-images.githubusercontent.com/3765085/41191788-4ced60ca-6c12-11e8-9ce8-c5a31f5b122e.png">
<img width="411" alt="screen shot 2018-06-09 at 6 20 36 pm" src="https://user-images.githubusercontent.com/3765085/41191790-4db4857e-6c12-11e8-9532-5b752bd2121f.png">

 FYI, I thinks we need to use _target instead of target.

Thanks,
Sabari.

**Comment by yomotsu** [comment]
Thanks for your report. I updated and It has solved with v1.2.2

**Comment by ksabariraj** [comment]
Thanks.

**Comment by ksabariraj** [comment]
Hi,

I saved the state and tried to apply that after reload. But, the camera position is completely changed. Could you please help on this?

Please see the code below.

Get State
`cameraControls.saveState();
  var position = cameraControls._position0.toArray();
  var target = cameraControls._target0.toArray()`

Apply
`  cameraControls._target0.fromArray(target);
    cameraControls._position0.fromArray(position);
    cameraControls.reset();`

Thanks,
Sabari.
