### ISSUE TITLE
Exposing _spherical

### ISSUE THREAD

**Issue by paulmelnikow** [yomotsu/camera-controls#93]
I've got an application where the user would like to see the polar angle. What do you think about exposing `_spherical` as a public property?

Either it could be unprotected (and marked readonly) or an accessor could be added which copies it.

**Comment by yomotsu** [comment]
How about providing `radius`, `theta` and `phi` of `_spherical ` as getters of the instance?

**Comment by yomotsu** [comment]
related to https://github.com/yomotsu/camera-controls/issues/33#issuecomment-456793209

**Comment by yomotsu** [comment]
Does https://github.com/yomotsu/camera-controls/pull/94 look good to you?
