### ISSUE TITLE
Unlock polar rotation 

### ISSUE THREAD

**Issue by Houssk** [yomotsu/camera-controls#95]
First of all, thanks for this very useful asset! 
i just look for unlock polar rotation (update camera up vector) like TrackballControls, any way to fix that ?

Thanks !

**Comment by yomotsu** [comment]
Thanks for using the lib.

you can update the up-vector with `updateCameraUp`
https://github.com/yomotsu/camera-controls#updatecameraup

**Comment by Houssk** [comment]
@yomotsu  Thanks !!
